# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=resolve_model_string_a0b7673a83
ROOST_METHOD_SIG_HASH=resolve_model_string_0b97f1219c


Scenario 1: Resolve a fully-qualified model string that exists
Details:
  TestName: test_resolve_valid_fully_qualified_string_returns_model
  Description: Verify that a correct "app_label.model_name" input is translated into the corresponding Django model class.
Execution:
  Arrange: Ensure Django is configured; pick a guaranteed model such as "auth.User".
  Act: Call resolve_model_string("auth.User").
  Assert: The function returns the exact class django.contrib.auth.models.User.
Validation:
  Confirms the core happy-path behaviour — translating a valid dotted string to a model object.

Scenario 2: Resolve an unqualified model name when default_app is provided
Details:
  TestName: test_resolve_unqualified_string_with_default_app
  Description: Check that, when the string lacks a dot, the helper uses the supplied default_app to build the lookup.
Execution:
  Arrange: Choose "User" and default_app="auth".
  Act: Call resolve_model_string("User", default_app="auth").
  Assert: The return value equals django.contrib.auth.models.User.
Validation:
  Ensures the fallback mechanism works and that the caller can shorten model references inside its own app.

Scenario 3: Unqualified model string without default_app raises ValueError
Details:
  TestName: test_unqualified_string_without_default_app_raises_value_error
  Description: The function should refuse to guess the app if default_app is missing.
Execution:
  Arrange: Provide "User" and omit default_app.
  Act: Invoke resolve_model_string("User") inside a `pytest.raises(ValueError)` context.
  Assert: A ValueError is raised and the message mentions the expected "app_label.model_name" format.
Validation:
  Guards against silent mis-resolution and enforces explicitness as designed.

Scenario 4: Malformed string with more than one dot and no default_app
Details:
  TestName: test_string_with_too_many_dots_without_default_app_raises_value_error
  Description: A string like "a.b.c" cannot be unpacked into exactly two parts; without default_app the function must fail.
Execution:
  Arrange: Use input "a.b.c".
  Act: Call resolve_model_string("a.b.c") expecting a ValueError.
  Assert: ValueError is raised.
Validation:
  Checks the defensive coding path that traps `ValueError` from tuple-unpacking and re-emits it when default_app is absent.

Scenario 5: Malformed string with too many dots but with default_app falls back to default_app
Details:
  TestName: test_string_with_too_many_dots_with_default_app_uses_entire_string_as_model_name
  Description: When default_app is supplied, the catch block treats the entire original string as model_name and attempts a lookup.
Execution:
  Arrange: Use default_app="auth" and model_string="User.Profile" (which produces unpacking ValueError).
  Act: Call resolve_model_string("User.Profile", default_app="auth") inside `pytest.raises(LookupError)`.
  Assert: LookupError is raised because "auth.User.Profile" is not a valid model.
Validation:
  Demonstrates that the fallback actually executes and hands control to Django’s registry, proving path coverage beyond the happy-path.

Scenario 6: Passing an actual model class returns the same class unchanged
Details:
  TestName: test_direct_model_class_pass_through
  Description: The helper should return the object it was given when that object is already a type.
Execution:
  Arrange: From django.contrib.auth.models import User.
  Act: result = resolve_model_string(User).
  Assert: result is User (identity comparison).
Validation:
  Confirms the short-circuit optimisation for pre-resolved classes.

Scenario 7: Non-string, non-type input raises ValueError
Details:
  TestName: test_invalid_input_type_raises_value_error
  Description: An arbitrary object (e.g., integer, list) is not resolvable and must trigger a ValueError.
Execution:
  Arrange: Choose input 42 (or []).
  Act: Call resolve_model_string(42) inside `pytest.raises(ValueError)`.
  Assert: ValueError is raised.
Validation:
  Ensures robust error handling for unsupported input categories.

Scenario 8: Fully-qualified string with correct app but unknown model raises LookupError
Details:
  TestName: test_unknown_model_with_valid_app_raises_lookup_error
  Description: Provide an existing app_label with a deliberately nonexistent model name to verify the function forwards Django’s LookupError.
Execution:
  Arrange: Use "auth.NonexistentModel".
  Act: Call resolve_model_string("auth.NonexistentModel") inside `pytest.raises(LookupError)`.
  Assert: LookupError is raised.
Validation:
  Checks that the helper does not mask registry errors and that failures propagate correctly to the caller.

"""

# ********RoostGPT********
import functools  # noqa: F401 – imported as instructed
import inspect  # noqa: F401
import logging  # noqa: F401
import re  # noqa: F401
import unicodedata  # noqa: F401
from collections.abc import Iterable  # noqa: F401
from hashlib import md5  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

import pytest
from anyascii import anyascii  # noqa: F401
from django.apps import apps
from django.conf import settings  # noqa: F401
from django.conf.locale import LANG_INFO  # noqa: F401
from django.core.cache import cache  # noqa: F401
from django.core.cache.utils import make_template_fragment_key  # noqa: F401
from django.core.exceptions import ImproperlyConfigured, SuspiciousOperation  # noqa: F401
from django.core.signals import setting_changed  # noqa: F401
from django.db.models import Model  # noqa: F401
from django.db.models.base import ModelBase  # noqa: F401
from django.dispatch import receiver  # noqa: F401
from django.http import HttpRequest  # noqa: F401
from django.test import RequestFactory  # noqa: F401
from django.utils.encoding import force_str  # noqa: F401
from django.utils.text import capfirst, slugify  # noqa: F401
from django.utils.translation import check_for_language, get_supported_language_variant  # noqa: F401
from wagtail.coreutils import resolve_model_string
from wagtail.models import Locale  # noqa: F401
from wagtail.models import Site  # noqa: F401

# ---------------------------------------------------------------------------
# NOTE:
#   All tests assume a functioning Django context (e.g. via pytest-django).
#   If your project uses a custom AUTH_USER_MODEL, replace "auth.User"
#   with the correct dotted path and update the assertions accordingly.  # TODO
# ---------------------------------------------------------------------------


class Test_CoreutilsResolveModelString:
    @pytest.mark.smoke
    @pytest.mark.valid
    def test_resolve_valid_fully_qualified_string_returns_model(self):
        """
        Scenario 1:
        A correctly-qualified string should be translated into the matching model
        class (happy-path).
        """
        from django.contrib.auth.models import User

        result = resolve_model_string("auth.User")

        assert result is User, "resolve_model_string failed to return the User model class"

    @pytest.mark.regression
    @pytest.mark.positive
    def test_resolve_unqualified_string_with_default_app(self):
        """
        Scenario 2:
        An unqualified model name combined with `default_app` should resolve
        successfully.
        """
        from django.contrib.auth.models import User

        result = resolve_model_string("User", default_app="auth")

        assert result is User, "Default app lookup did not return the expected User model"

    @pytest.mark.negative
    def test_unqualified_string_without_default_app_raises_value_error(self):
        """
        Scenario 3:
        Omitting `default_app` for an unqualified name must raise ValueError.
        """
        with pytest.raises(ValueError) as exc_info:
            resolve_model_string("User")

        # The error message should mention the required format
        assert "app_label.model_name" in str(
            exc_info.value
        ), "Error message did not reference the required 'app_label.model_name' format"

    @pytest.mark.negative
    def test_string_with_too_many_dots_without_default_app_raises_value_error(self):
        """
        Scenario 4:
        A malformed string containing more than one dot without default_app must
        raise ValueError.
        """
        with pytest.raises(ValueError):
            resolve_model_string("a.b.c")

    @pytest.mark.negative
    def test_string_with_too_many_dots_with_default_app_uses_entire_string_as_model_name(
        self,
    ):
        """
        Scenario 5:
        When default_app is supplied and splitting fails, the function should
        attempt to look up the whole string as model_name – which will raise
        LookupError for non-existent models.
        """
        with pytest.raises(LookupError):
            resolve_model_string("User.Profile", default_app="auth")

    @pytest.mark.smoke
    def test_direct_model_class_pass_through(self):
        """
        Scenario 6:
        Passing an actual model class should return the same object unchanged.
        """
        from django.contrib.auth.models import User

        result = resolve_model_string(User)

        assert result is User, "Model class should be returned unchanged"

    @pytest.mark.negative
    def test_invalid_input_type_raises_value_error(self):
        """
        Scenario 7:
        Non-string, non-type inputs are invalid and should raise ValueError.
        """
        with pytest.raises(ValueError):
            resolve_model_string(42)  # type: ignore[arg-type]

    @pytest.mark.negative
    def test_unknown_model_with_valid_app_raises_lookup_error(self):
        """
        Scenario 8:
        A real app with a non-existent model should propagate Django's LookupError.
        """
        with pytest.raises(LookupError):
            resolve_model_string("auth.NonexistentModel")
