# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=BatchProcessor.extend_d1fe8173f7
ROOST_METHOD_SIG_HASH=BatchProcessor.extend_85a04f7f91


Scenario 1: Adding a typical list when no max_size is configured
Details:
  TestName: test_extend_appends_items_without_max_size
  Description: Verify that every element from the provided list is appended to self.items and that added_count increases by the exact length of the list when self.max_size is None.
Execution:
  Arrange: Create an instance with self.items = [] , self.added_count = 0 , and self.max_size = None. Prepare iterable = ["a", "b", "c"].
  Act: Invoke instance.extend(iterable).
  Assert: Check that self.items equals ["a", "b", "c"] and that self.added_count equals 3. Confirm that self.process is never called.
Validation: Confirms the core responsibility of extend—delegating each element to add—under the most common configuration.

Scenario 2: Extending with an empty iterable
Details:
  TestName: test_extend_with_empty_iterable_does_nothing
  Description: Ensure that passing an empty iterable leaves state untouched and does not call self.process.
Execution:
  Arrange: Instantiate with some pre-existing items and set added_count to its current value. Provide iterable = [].
  Act: Call instance.extend(iterable).
  Assert: Verify self.items and added_count remain unchanged, and self.process is not invoked.
Validation: Guarantees safe no-op behavior, preventing unnecessary side-effects when no data is supplied.

Scenario 3: Reaching max_size exactly once during the call
Details:
  TestName: test_extend_triggers_process_exactly_at_capacity
  Description: Confirm that self.process is invoked exactly once when the cumulative item total matches self.max_size for the first time.
Execution:
  Arrange: Stub/mount a spy on self.process. Prepare self.items with length 0, self.max_size = 5, iterable = range(5).
  Act: Call instance.extend(iterable).
  Assert: Assert that self.process was called once, len(self.items) == 5, and added_count == 5.
Validation: Validates the boundary condition where extend should switch from filling to processing.

Scenario 4: Crossing the capacity threshold multiple times in one go
Details:
  TestName: test_extend_multiple_process_triggers_when_batches_fit_evenly
  Description: If iterable length is an exact multiple of max_size, process should be triggered repeatedly—once per full batch.
Execution:
  Arrange: Spy on self.process. Set self.max_size = 3, iterable = ["a", "b", "c", "d", "e", "f"] (length 6).
  Act: Execute instance.extend(iterable).
  Assert: self.process called twice, added_count == 6. The internal state of self.items depends on what self.process does; if it clears the list, ensure it is empty, otherwise length == 6.
Validation: Demonstrates extend’s ability to handle bulk additions that overflow capacity multiple times, maintaining business throughput.

Scenario 5: Filling an almost-full buffer
Details:
  TestName: test_extend_triggers_process_when_pre_filled
  Description: When items already exist, extending should consider current length toward max_size.
Execution:
  Arrange: self.max_size = 4, self.items = [1, 2], iterable = [3, 4]. Attach spy to self.process.
  Act: instance.extend(iterable).
  Assert: self.process invoked once, added_count increased by 2, and final length of self.items assessed per process’s side-effects.
Validation: Confirms that extend is sensitive to existing state, not just the size of the incoming iterable.

Scenario 6: max_size set to None prevents process call
Details:
  TestName: test_extend_never_calls_process_when_max_size_none
  Description: Even with large iterables, process must not run if max_size is undefined.
Execution:
  Arrange: self.max_size = None, iterable = range(1000), spy on self.process.
  Act: Call instance.extend(iterable).
  Assert: self.process never called, len(self.items) == 1000, added_count == 1000.
Validation: Verifies configuration option where batching is disabled, an important business toggle.

Scenario 7: Handling a generator (lazy iterable)
Details:
  TestName: test_extend_accepts_generator_iterable
  Description: Ensure extend correctly exhausts generators and processes each yielded item.
Execution:
  Arrange: generator = (i for i in range(4)), self.max_size = None.
  Act: instance.extend(generator).
  Assert: self.items contains [0, 1, 2, 3], added_count == 4.
Validation: Demonstrates compatibility with all Python iterables, not only materialized sequences.

Scenario 8: Non-iterable input raises TypeError
Details:
  TestName: test_extend_raises_typeerror_for_non_iterable
  Description: Passing a non-iterable (e.g., an int) should raise TypeError during iteration.
Execution:
  Arrange: Provide non_iterable = 42.
  Act: Call instance.extend(non_iterable) within pytest.raises(TypeError) context.
  Assert: TypeError is raised, and state (items, added_count, process count) remains unchanged.
Validation: Protects against misuse and ensures robustness under invalid API calls.

Scenario 9: added_count integrity after internal process resets
Details:
  TestName: test_extend_added_count_cumulative_across_process_resets
  Description: Regardless of whether self.process clears items, added_count should still accumulate total items ever added.
Execution:
  Arrange: Implement a stub process that clears self.items but doesn’t touch added_count. self.max_size = 2, iterable = [1, 2, 3, 4].
  Act: instance.extend(iterable).
  Assert: added_count == 4, and self.process called twice. After execution, len(self.items) == 0 (because process cleared them).
Validation: Ensures accurate lifetime metrics—critical for monitoring and auditing—even when batching causes internal list resets.

"""

# ********RoostGPT********
import functools  # noqa: F401  (imported as required by instructions)
import inspect  # noqa: F401
import logging  # noqa: F401
import re  # noqa: F401
import unicodedata  # noqa: F401
from collections.abc import Iterable  # noqa: F401
from hashlib import md5  # noqa: F401
from typing import TYPE_CHECKING, Any  # noqa: F401

import pytest
from unittest.mock import MagicMock

# Optional / best-effort imports – guarded so the tests will still collect if Django/Wagtail
# are not available in the execution environment.
try:
    from anyascii import anyascii  # noqa: F401
    from django.apps import apps  # noqa: F401
    from django.conf import settings  # noqa: F401
    from django.conf.locale import LANG_INFO  # noqa: F401
    from django.core.cache import cache  # noqa: F401
    from django.core.cache.utils import make_template_fragment_key  # noqa: F401
    from django.core.exceptions import ImproperlyConfigured, SuspiciousOperation  # noqa: F401
    from django.core.signals import setting_changed  # noqa: F401
    from django.db.models import Model  # noqa: F401
    from django.db.models.base import ModelBase  # noqa: F401
    from django.dispatch import receiver  # noqa: F401
    from django.http import HttpRequest  # noqa: F401
    from django.test import RequestFactory  # noqa: F401
    from django.utils.encoding import force_str  # noqa: F401
    from django.utils.text import capfirst, slugify  # noqa: F401
    from django.utils.translation import (
        check_for_language,
        get_supported_language_variant,
    )  # noqa: F401
    from wagtail.models import Site, Locale  # noqa: F401
except Exception:  # pragma: no cover
    # Any import failure is acceptable for the purposes of these unit tests.
    pass

from wagtail.coreutils import BatchProcessor


class Test_BatchProcessorExtend:
    @pytest.mark.smoke
    def test_extend_appends_items_without_max_size(self):
        """Scenario 1: Adding a typical list when no max_size is configured."""
        processor = BatchProcessor(max_size=None)  # type: ignore[arg-type]
        processor.process = MagicMock()  # type: ignore[assignment]
        processor.items = []  # Reset explicitly for clarity
        processor.added_count = 0
        iterable = ["a", "b", "c"]

        processor.extend(iterable)

        assert processor.items == iterable
        assert processor.added_count == len(iterable)
        processor.process.assert_not_called()

    @pytest.mark.negative
    def test_extend_with_empty_iterable_does_nothing(self):
        """Scenario 2: Extending with an empty iterable should be a no-op."""
        processor = BatchProcessor(max_size=None)  # type: ignore[arg-type]
        processor.process = MagicMock()  # type: ignore[assignment]

        preexisting_items = ["x", "y"]
        processor.items = preexisting_items.copy()
        processor.added_count = len(preexisting_items)

        processor.extend([])  # Empty iterable

        assert processor.items == preexisting_items
        assert processor.added_count == len(preexisting_items)
        processor.process.assert_not_called()

    @pytest.mark.regression
    def test_extend_triggers_process_exactly_at_capacity(self):
        """Scenario 3: Process invoked exactly once when hitting capacity."""
        processor = BatchProcessor(max_size=5)
        processor.process = MagicMock()  # type: ignore[assignment]

        processor.extend(range(5))

        assert len(processor.items) == 5
        assert processor.added_count == 5
        assert processor.process.call_count == 1

    @pytest.mark.regression
    def test_extend_multiple_process_triggers_when_batches_fit_evenly(self):
        """Scenario 4: Process called once per full batch when iterable length
        is an exact multiple of max_size.
        """
        processor = BatchProcessor(max_size=3)

        # Spy that clears items to emulate real behaviour
        def _process():
            processor.items.clear()

        processor.process = MagicMock(side_effect=_process)  # type: ignore[assignment]

        processor.extend(["a", "b", "c", "d", "e", "f"])

        assert processor.process.call_count == 2
        assert processor.added_count == 6
        assert len(processor.items) == 0  # because _process clears the buffer

    @pytest.mark.regression
    def test_extend_triggers_process_when_pre_filled(self):
        """Scenario 5: Buffer already contains items before extend."""
        processor = BatchProcessor(max_size=4)

        # Pre-fill state
        processor.items = [1, 2]
        processor.added_count = len(processor.items)

        def _process():
            processor.items.clear()

        processor.process = MagicMock(side_effect=_process)  # type: ignore[assignment]

        iterable = [3, 4]
        processor.extend(iterable)

        assert processor.process.call_count == 1
        assert processor.added_count == len(iterable) + 2  # increased by 2
        assert len(processor.items) == 0  # cleared by _process

    @pytest.mark.performance
    def test_extend_never_calls_process_when_max_size_none(self):
        """Scenario 6: No processing should happen when max_size is None."""
        processor = BatchProcessor(max_size=None)  # type: ignore[arg-type]
        processor.process = MagicMock()  # type: ignore[assignment]

        data = range(1000)  # large iterable
        processor.extend(data)

        processor.process.assert_not_called()
        assert len(processor.items) == 1000
        assert processor.added_count == 1000

    @pytest.mark.valid
    def test_extend_accepts_generator_iterable(self):
        """Scenario 7: Ensure generators are fully consumed."""
        processor = BatchProcessor(max_size=None)  # type: ignore[arg-type]
        processor.process = MagicMock()  # type: ignore[assignment]

        processor.extend((i for i in range(4)))  # generator expression

        assert processor.items == [0, 1, 2, 3]
        assert processor.added_count == 4

    @pytest.mark.invalid
    def test_extend_raises_typeerror_for_non_iterable(self):
        """Scenario 8: Non-iterables should raise TypeError and leave state unchanged."""
        processor = BatchProcessor(max_size=None)  # type: ignore[arg-type]
        processor.process = MagicMock()  # type: ignore[assignment]

        pre_items = processor.items.copy()
        pre_count = processor.added_count

        with pytest.raises(TypeError):
            processor.extend(42)  # type: ignore[arg-type]

        assert processor.items == pre_items
        assert processor.added_count == pre_count
        processor.process.assert_not_called()

    @pytest.mark.regression
    def test_extend_added_count_cumulative_across_process_resets(self):
        """Scenario 9: added_count should reflect total items ever added."""
        processor = BatchProcessor(max_size=2)

        def _process():
            processor.items.clear()

        processor.process = MagicMock(side_effect=_process)  # type: ignore[assignment]

        processor.extend([1, 2, 3, 4])

        assert processor.added_count == 4
        assert processor.process.call_count == 2
        assert len(processor.items) == 0  # buffer cleared after last process
