# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=WorkflowLock.get_context_for_user_a578f79677
ROOST_METHOD_SIG_HASH=WorkflowLock.get_context_for_user_d74a922eb7


 
Scenario 1: Context returned unchanged when no parent_context is supplied
Details:
  TestName: test_context_unchanged_without_parent_context
  Description: Verify that the method simply returns the result from its superclass when parent_context is None, i.e., no lock–related keys are added or updated.
Execution:
  Arrange: 
    • Create a dummy subclass whose super().get_context_for_user returns a dictionary such as {"foo": "bar"}.  
    • Instantiate the subclass and construct a fake user object.
  Act: 
    • Call get_context_for_user(user, parent_context=None).
  Assert: 
    • The returned dict is exactly {"foo": "bar"}; keys "icon", "locked_by", and "description" must be absent.
Validation: 
  Ensures that the additional lock-specific enrichment happens only when a parent_context is passed, preventing accidental pollution of the base context.

Scenario 2: Context returned unchanged when parent_context lacks the “user_can_lock” key
Details:
  TestName: test_context_unchanged_without_user_can_lock_key
  Description: Confirm that the method leaves the base context intact if parent_context does not expose the “user_can_lock” flag.
Execution:
  Arrange: 
    • As in Scenario 1, but pass parent_context={"some": "value"}.
  Act:
    • Invoke get_context_for_user(user, parent_context).
  Assert:
    • The returned dict equals {"foo": "bar"} and still lacks "icon", "locked_by", "description".
Validation:
  Protects the business rule that enrichment only occurs when the explicit permission flag is present.

Scenario 3: Lock enrichment when user_can_lock is True
Details:
  TestName: test_lock_information_added_when_user_can_lock_true
  Description: Validate that, when “user_can_lock” is True, the method appends/updates the lock metadata using the subclass’s helper methods.
Execution:
  Arrange: 
    • Stub get_icon / get_locked_by / get_description to return "my_icon", "Me", "You can lock".  
    • Base context from super() is {"foo": "bar"}.  
    • parent_context={"user_can_lock": True}.
  Act:
    • Call get_context_for_user(user, parent_context).
  Assert:
    • Returned dict == {"foo": "bar", "icon": "my_icon", "locked_by": "Me", "description": "You can lock"}.
Validation:
  Proves the positive path where a user with lock permission receives enriched UI data.

Scenario 4: Lock enrichment when user_can_lock is False
Details:
  TestName: test_lock_information_added_when_user_cannot_lock
  Description: Ensure that the method still adds lock metadata but passes can_lock=False to icon/description helpers, enabling alternative wording/icons for users without permission.
Execution:
  Arrange:
    • Override helper methods to inspect the second argument; if False, return "locked_icon", "System", "Lock is engaged".
    • super() returns {"foo": "bar"}; parent_context={"user_can_lock": False}.
  Act:
    • Call get_context_for_user(user, parent_context).
  Assert:
    • Returned dict == {"foo": "bar", "icon": "locked_icon", "locked_by": "System", "description": "Lock is engaged"}.
Validation:
  Confirms correct behavior for users who may view but not lock the object.

Scenario 5: Existing keys from super() are overridden by lock enrichment
Details:
  TestName: test_enrichment_overrides_existing_keys
  Description: If super() already returns "icon", "locked_by", or "description", the method must override them with the values from the helper methods.
Execution:
  Arrange:
    • super() returns {"icon": "old_icon", "locked_by": "old", "description": "old description"}.
    • Helpers return "new_icon", "new_by", "new_description".
    • parent_context={"user_can_lock": True}.
  Act:
    • Invoke get_context_for_user.
  Assert:
    • Keys reflect the “new_” values, proving an update rather than merge-without-override.
Validation:
  Ensures UI presents the most accurate lock information even if the superclass supplied stale or generic data.

Scenario 6: Non-lock keys from parent_context propagate untouched
Details:
  TestName: test_parent_context_keys_preserved
  Description: Verify that unrelated keys from the base context survive the enrichment process.
Execution:
  Arrange:
    • super() returns {"foo": "bar"}.
    • parent_context={"user_can_lock": True, "irrelevant": 123}.
    • Helpers produce standard lock strings.
  Act:
    • Call get_context_for_user.
  Assert:
    • Returned context contains "foo": "bar" and preserves no copy of "irrelevant" (because only super() context is returned, not parent_context data).
Validation:
  Safeguards against accidental leakage of workflow-internal parent_context data into the user-facing context.

Scenario 7: Helper methods receive the correct can_lock argument
Details:
  TestName: test_helper_methods_called_with_can_lock_flag
  Description: Guarantee that the boolean derived from parent_context is passed verbatim to get_icon, get_locked_by, and get_description.
Execution:
  Arrange:
    • Replace helper methods with spies or lambdas capturing their second argument.
    • parent_context={"user_can_lock": False}.
  Act:
    • Call get_context_for_user.
  Assert:
    • Each helper was executed exactly once and received False.
  Validation:
    • Critical for ensuring that helper logic can reliably differentiate between permission states when generating UI elements.

"""

# ********RoostGPT********
import types
from unittest.mock import MagicMock

import pytest

# Mandatory imports declared by the task --------------------------------------
try:
    from django.conf import settings            # noqa: F401
    from django.utils.html import format_html   # noqa: F401
    from django.utils.safestring import mark_safe  # noqa: F401
    from django.utils.text import capfirst      # noqa: F401
    from django.utils.translation import gettext as _  # noqa: F401
    from wagtail.admin.utils import get_latest_str, get_user_display_name  # noqa: F401
    from wagtail.utils.timestamps import render_timestamp  # noqa: F401
    from wagtail.models import Page             # noqa: F401
except ModuleNotFoundError:
    # Provide fall-back stubs so that the tests can still run when
    # Django / Wagtail are not available in the execution environment.
    dummy_modules = {
        'django': types.ModuleType('django'),
        'django.conf': types.ModuleType('django.conf'),
        'django.utils': types.ModuleType('django.utils'),
        'django.utils.html': types.ModuleType('django.utils.html'),
        'django.utils.safestring': types.ModuleType('django.utils.safestring'),
        'django.utils.text': types.ModuleType('django.utils.text'),
        'django.utils.translation': types.ModuleType('django.utils.translation'),
        'wagtail': types.ModuleType('wagtail'),
        'wagtail.admin': types.ModuleType('wagtail.admin'),
        'wagtail.admin.utils': types.ModuleType('wagtail.admin.utils'),
        'wagtail.utils': types.ModuleType('wagtail.utils'),
        'wagtail.utils.timestamps': types.ModuleType('wagtail.utils.timestamps'),
        'wagtail.models': types.ModuleType('wagtail.models'),
    }
    import sys
    sys.modules.update(dummy_modules)
    from django.conf import settings            # noqa: F401
    from django.utils.html import format_html   # noqa: F401
    from django.utils.safestring import mark_safe  # noqa: F401
    from django.utils.text import capfirst      # noqa: F401
    from django.utils.translation import gettext as _  # noqa: F401
    from wagtail.admin.utils import get_latest_str, get_user_display_name  # noqa: F401
    from wagtail.utils.timestamps import render_timestamp  # noqa: F401
    from wagtail.models import Page             # noqa: F401
# -----------------------------------------------------------------------------


from wagtail.locks import WorkflowLock


class Test_WorkflowLockGetContextForUser:
    @pytest.mark.smoke
    @pytest.mark.valid
    def test_context_unchanged_without_parent_context(self):
        """
        Scenario 1 – ensure context is unchanged when parent_context is None.
        """
        class DummyBase:
            def get_context_for_user(self, user, parent_context=None):  # noqa: D401
                return {"foo": "bar"}

        class DummyWorkflowLock(WorkflowLock, DummyBase):
            pass

        dummy_lock = DummyWorkflowLock()

        # If any of these helpers are called the test must immediately fail.
        dummy_lock.get_icon = lambda *args, **kwargs: pytest.fail("get_icon must not be called")
        dummy_lock.get_locked_by = lambda *args, **kwargs: pytest.fail("get_locked_by must not be called")
        dummy_lock.get_description = lambda *args, **kwargs: pytest.fail("get_description must not be called")

        user = object()
        result = dummy_lock.get_context_for_user(user, parent_context=None)

        assert result == {"foo": "bar"}
        assert "icon" not in result and "locked_by" not in result and "description" not in result

    @pytest.mark.regression
    @pytest.mark.invalid
    def test_context_unchanged_without_user_can_lock_key(self):
        """
        Scenario 2 – ensure context remains the same when 'user_can_lock' key is missing.
        """
        class DummyBase:
            def get_context_for_user(self, user, parent_context=None):
                return {"foo": "bar"}

        class DummyWorkflowLock(WorkflowLock, DummyBase):
            pass

        dummy_lock = DummyWorkflowLock()
        dummy_lock.get_icon = lambda *args, **kwargs: pytest.fail("get_icon must not be called")
        dummy_lock.get_locked_by = lambda *args, **kwargs: pytest.fail("get_locked_by must not be called")
        dummy_lock.get_description = lambda *args, **kwargs: pytest.fail("get_description must not be called")

        user = object()
        parent_context = {"some": "value"}

        result = dummy_lock.get_context_for_user(user, parent_context=parent_context)

        assert result == {"foo": "bar"}
        assert "icon" not in result and "locked_by" not in result and "description" not in result

    @pytest.mark.positive
    def test_lock_information_added_when_user_can_lock_true(self):
        """
        Scenario 3 – enrichment when user_can_lock is True.
        """
        class DummyBase:
            def get_context_for_user(self, user, parent_context=None):
                return {"foo": "bar"}

        class DummyWorkflowLock(WorkflowLock, DummyBase):
            pass

        dummy_lock = DummyWorkflowLock()
        dummy_lock.get_icon = lambda user, can_lock: "my_icon"
        dummy_lock.get_locked_by = lambda user, can_lock: "Me"
        dummy_lock.get_description = lambda user, can_lock: "You can lock"

        user = object()
        parent_context = {"user_can_lock": True}

        expected = {
            "foo": "bar",
            "icon": "my_icon",
            "locked_by": "Me",
            "description": "You can lock",
        }

        assert dummy_lock.get_context_for_user(user, parent_context) == expected

    @pytest.mark.negative
    def test_lock_information_added_when_user_cannot_lock(self):
        """
        Scenario 4 – enrichment when user_can_lock is False.
        """
        class DummyBase:
            def get_context_for_user(self, user, parent_context=None):
                return {"foo": "bar"}

        class DummyWorkflowLock(WorkflowLock, DummyBase):
            pass

        def icon_fn(user, can_lock):
            return "locked_icon" if not can_lock else "unlocked_icon"  # pragma: no cover

        def locked_by_fn(user, can_lock):
            return "System" if not can_lock else "User"  # pragma: no cover

        def description_fn(user, can_lock):
            return "Lock is engaged" if not can_lock else "Lock is disengaged"  # pragma: no cover

        dummy_lock = DummyWorkflowLock()
        dummy_lock.get_icon = icon_fn
        dummy_lock.get_locked_by = locked_by_fn
        dummy_lock.get_description = description_fn

        user = object()
        parent_context = {"user_can_lock": False}

        expected = {
            "foo": "bar",
            "icon": "locked_icon",
            "locked_by": "System",
            "description": "Lock is engaged",
        }

        assert dummy_lock.get_context_for_user(user, parent_context) == expected

    @pytest.mark.regression
    def test_enrichment_overrides_existing_keys(self):
        """
        Scenario 5 – the lock enrichment must override any existing keys.
        """
        class DummyBase:
            def get_context_for_user(self, user, parent_context=None):
                return {
                    "icon": "old_icon",
                    "locked_by": "old",
                    "description": "old description",
                }

        class DummyWorkflowLock(WorkflowLock, DummyBase):
            pass

        dummy_lock = DummyWorkflowLock()
        dummy_lock.get_icon = lambda user, can_lock: "new_icon"
        dummy_lock.get_locked_by = lambda user, can_lock: "new_by"
        dummy_lock.get_description = lambda user, can_lock: "new_description"

        user = object()
        parent_context = {"user_can_lock": True}

        result = dummy_lock.get_context_for_user(user, parent_context)

        assert result["icon"] == "new_icon"
        assert result["locked_by"] == "new_by"
        assert result["description"] == "new_description"

    @pytest.mark.smoke
    def test_parent_context_keys_preserved(self):
        """
        Scenario 6 – unrelated keys from parent_context should not be propagated.
        """
        class DummyBase:
            def get_context_for_user(self, user, parent_context=None):
                return {"foo": "bar"}

        class DummyWorkflowLock(WorkflowLock, DummyBase):
            pass

        dummy_lock = DummyWorkflowLock()
        dummy_lock.get_icon = lambda user, can_lock: "icon"
        dummy_lock.get_locked_by = lambda user, can_lock: "by"
        dummy_lock.get_description = lambda user, can_lock: "desc"

        user = object()
        parent_context = {"user_can_lock": True, "irrelevant": 123}

        result = dummy_lock.get_context_for_user(user, parent_context)

        assert "foo" in result and result["foo"] == "bar"
        assert "irrelevant" not in result

    @pytest.mark.security
    def test_helper_methods_called_with_can_lock_flag(self):
        """
        Scenario 7 – helper methods must receive the correct 'can_lock' argument.
        """
        class DummyBase:
            def get_context_for_user(self, user, parent_context=None):
                return {"foo": "bar"}

        class DummyWorkflowLock(WorkflowLock, DummyBase):
            pass

        dummy_lock = DummyWorkflowLock()

        icon_mock = MagicMock(return_value="icon")
        locked_by_mock = MagicMock(return_value="by")
        description_mock = MagicMock(return_value="desc")

        dummy_lock.get_icon = icon_mock
        dummy_lock.get_locked_by = locked_by_mock
        dummy_lock.get_description = description_mock

        user = object()
        parent_context = {"user_can_lock": False}

        dummy_lock.get_context_for_user(user, parent_context)

        icon_mock.assert_called_once_with(user, False)
        locked_by_mock.assert_called_once_with(user, False)
        description_mock.assert_called_once_with(user, False)
