# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=BasicLock.get_description_67e6024e04
ROOST_METHOD_SIG_HASH=BasicLock.get_description_ac4a41e090


Scenario 1: Locked By Current User
Details:
  TestName: test_get_description_locked_by_current_user
  Description: Verify that when the page is locked by the same user who is requesting the description, the method returns a message beginning with “Only you can make changes …” and containing the correct model name.
Execution:
  Arrange: 
    • Create a mock page-like object with attributes:
        – locked_by_id set to 42  
        – locked_by pointing to a mock user object with pk 42 (not strictly required but keeps the fixture coherent)
        – model_name set to "blog post" (any meaningful string in lower-case to highlight capfirst)
    • Instantiate the view/permission helper that owns get_description, injecting the mock page object and stubbing super().get_description to raise if called.
    • Prepare a mock current_user object whose pk is also 42.
  Act: Call get_description(mock_current_user).
  Assert: 
    • The returned value equals "Only you can make changes while the blog post is locked".
    • No call is made to the superclass implementation.
Validation:
  This test guarantees the branch self.object.locked_by_id == user.pk is executed and that the personalised phrasing for “you” plus cap-first transformation of the model name works as required, protecting the business rule that the lock holder sees an exclusive-editing warning.

Scenario 2: Locked By Another User With Display Name
Details:
  TestName: test_get_description_locked_by_other_user
  Description: Confirm that when the page is locked by a different user, the method mentions that user’s display name and still embeds the correct model name.
Execution:
  Arrange:
    • Create a mock page object where:
        – locked_by_id is 7  
        – locked_by is a mock other_user whose get_full_name returns "Charlie Editor" and get_username returns "charlie".
        – model_name is "article".
    • Patch wagtail.admin.utils.get_user_display_name so that it returns "Charlie Editor" for other_user.
    • Stub super().get_description to raise if called.
    • Prepare a requesting_user with pk 42, different from 7.
  Act: Call get_description(requesting_user).
  Assert:
    • The result equals "Only Charlie Editor can make changes while the article is locked".
    • The patched get_user_display_name is invoked exactly once with other_user.
Validation:
  Ensures the alternative branch (locked but by someone else) executes, confirming that user attribution logic, string interpolation, and internationalisation placeholder handling operate together correctly.

Scenario 3: Locked By Another User Without Display Name
Details:
  TestName: test_get_description_locked_by_other_user_without_display_name
  Description: Validate fallback behaviour when get_user_display_name returns an empty string (e.g., user object is incomplete or anonymous). The produced sentence should still follow grammar even if the name is blank.
Execution:
  Arrange:
    • Mock page.locked_by_id = 7 and page.locked_by = other_user.
    • Patch get_user_display_name to return "" (empty string).
    • model_name set to "document".
    • Requesting user pk differs from 7.
  Act: Invoke get_description(requesting_user).
  Assert:
    • The resulting text equals "Only  can make changes while the document is locked" (two spaces between “Only” and “can” caused by missing name).
    • No exception is raised; function degrades gracefully.
Validation:
  Demonstrates resilience to edge-cases where user metadata is missing, ensuring that the UI doesn’t crash and still communicates that a lock exists.

Scenario 4: Unlocked Object Delegates To Super
Details:
  TestName: test_get_description_unlocked_delegates_to_super
  Description: Ensure that when the page is not locked (locked_by_id is None or 0), get_description defers entirely to the superclass implementation.
Execution:
  Arrange:
    • Mock page.locked_by_id = None and model_name = "report".
    • Provide a dummy user (pk any value).
    • Patch super().get_description to return "Default description".
  Act: Call get_description(dummy_user).
  Assert:
    • The return value is exactly "Default description".
    • The patched superclass method is invoked once.
Validation:
  Confirms correct control-flow: the function must not fabricate a lock-based message when no lock exists, upholding the principle of single responsibility and avoiding misleading feedback.

Scenario 5: Locked Flag Present But locked_by Missing
Details:
  TestName: test_get_description_locked_id_set_but_locked_by_none
  Description: Check robustness when locked_by_id is truthy but locked_by attribute is None (possible data inconsistency). The code should still attempt to fetch a display name, receive an empty string, and craft the generic “Only  can make changes …” response.
Execution:
  Arrange:
    • page.locked_by_id = 99
    • page.locked_by = None
    • model_name = "page"
    • Patch get_user_display_name to return "" even when given None.
    • Requesting user pk differs from 99.
  Act: Call get_description(requesting_user).
  Assert:
    • The produced message equals "Only  can make changes while the page is locked".
    • No AttributeError or other exception bubbles up.
Validation:
  Safeguards against partial database corruption or lazy-loading issues by proving the method still completes gracefully, a key non-functional requirement for administrative UX stability.

"""

# ********RoostGPT********
import sys
from types import SimpleNamespace
from unittest.mock import Mock, patch

import pytest

from wagtail.locks import BasicLock


def _make_test_lock(page_obj, model_name, parent_get_description_mock):
    """
    Build a lock instance whose super().get_description is controlled by the
    supplied mock.  We do this by creating an ad-hoc parent class that exposes
    the desired mock as its implementation so that BasicLock.get_description
    resolves it via super().
    """

    class _SuperStub:
        def get_description(self, user):
            return parent_get_description_mock(user)

    # MRO => (TestLock, BasicLock, _SuperStub)
    class TestLock(BasicLock, _SuperStub):
        pass

    # Avoid running BasicLock.__init__ (constructor signature is unknown / could
    # vary between versions).  Instantiating via __new__ lets us hand-craft the
    # attributes the real implementation expects.
    lock_instance = TestLock.__new__(TestLock)

    # Provide the minimal attributes referenced by BasicLock.get_description.
    lock_instance.object = page_obj
    lock_instance.model_name = model_name
    return lock_instance


class Test_BasicLockGetDescription:
    # ------------------------------------------------------------------ #
    # Scenario 1 – locked by current user
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    @pytest.mark.positive
    @pytest.mark.smoke
    def test_get_description_locked_by_current_user(self):
        page = SimpleNamespace()
        page.locked_by_id = 42
        page.locked_by = Mock(pk=42)

        # parent method must NOT be used in this branch
        parent_mock = Mock(side_effect=AssertionError("super().get_description should not be called"))

        lock = _make_test_lock(page, model_name="blog post", parent_get_description_mock=parent_mock)

        current_user = Mock(pk=42)

        result = lock.get_description(current_user)

        assert result == "Only you can make changes while the blog post is locked"
        parent_mock.assert_not_called()

    # ------------------------------------------------------------------ #
    # Scenario 2 – locked by another user with display name
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    @pytest.mark.regression
    @pytest.mark.positive
    def test_get_description_locked_by_other_user(self):
        other_user = Mock()
        other_user.pk = 7
        other_user.get_full_name.return_value = "Charlie Editor"
        other_user.get_username.return_value = "charlie"

        page = SimpleNamespace()
        page.locked_by_id = 7
        page.locked_by = other_user

        parent_mock = Mock(side_effect=AssertionError("super().get_description should not be called"))
        lock = _make_test_lock(page, model_name="article", parent_get_description_mock=parent_mock)

        requesting_user = Mock(pk=42)

        with patch("wagtail.admin.utils.get_user_display_name", return_value="Charlie Editor") as display_name_patch:
            result = lock.get_description(requesting_user)

        assert result == "Only Charlie Editor can make changes while the article is locked"
        parent_mock.assert_not_called()
        display_name_patch.assert_called_once_with(other_user)

    # ------------------------------------------------------------------ #
    # Scenario 3 – locked by another user without display name
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    @pytest.mark.edgecase
    @pytest.mark.negative
    def test_get_description_locked_by_other_user_without_display_name(self):
        other_user = Mock(pk=7)

        page = SimpleNamespace()
        page.locked_by_id = 7
        page.locked_by = other_user

        parent_mock = Mock(side_effect=AssertionError("super().get_description should not be called"))
        lock = _make_test_lock(page, model_name="document", parent_get_description_mock=parent_mock)

        requesting_user = Mock(pk=999)

        with patch("wagtail.admin.utils.get_user_display_name", return_value="") as display_name_patch:
            result = lock.get_description(requesting_user)

        assert result == "Only  can make changes while the document is locked"
        parent_mock.assert_not_called()
        display_name_patch.assert_called_once_with(other_user)

    # ------------------------------------------------------------------ #
    # Scenario 4 – unlocked object delegates to super
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    @pytest.mark.positive
    @pytest.mark.smoke
    def test_get_description_unlocked_delegates_to_super(self):
        page = SimpleNamespace()
        page.locked_by_id = None

        parent_mock = Mock(return_value="Default description")
        lock = _make_test_lock(page, model_name="report", parent_get_description_mock=parent_mock)

        dummy_user = Mock(pk=1)

        result = lock.get_description(dummy_user)

        assert result == "Default description"
        parent_mock.assert_called_once_with(dummy_user)

    # ------------------------------------------------------------------ #
    # Scenario 5 – locked flag present but locked_by missing
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    @pytest.mark.edgecase
    @pytest.mark.negative
    def test_get_description_locked_id_set_but_locked_by_none(self):
        page = SimpleNamespace()
        page.locked_by_id = 99
        page.locked_by = None

        parent_mock = Mock(side_effect=AssertionError("super().get_description should not be called"))
        lock = _make_test_lock(page, model_name="page", parent_get_description_mock=parent_mock)

        requesting_user = Mock(pk=123)

        with patch("wagtail.admin.utils.get_user_display_name", return_value="") as display_name_patch:
            result = lock.get_description(requesting_user)

        assert result == "Only  can make changes while the page is locked"
        parent_mock.assert_not_called()
        display_name_patch.assert_called_once_with(None)
