# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=WorkflowLock.__init___1d9083d22c
ROOST_METHOD_SIG_HASH=WorkflowLock.__init___81935c1d85


Scenario 1: Successful construction stores the task reference
Details:
  TestName: test_init_stores_task_reference
  Description: Verify that passing a valid task object causes the constructor to store that same object on the instance.
Execution:
  Arrange: Create a stub object (e.g., DummyPage) and a stub task object (e.g., DummyTask).
  Act: Instantiate the class under test with those two arguments.
  Assert: Use identity comparison to confirm instance.task is the exact task object provided.
Validation:
  Ensures the fundamental business rule that the constructor links the task to the new instance.

Scenario 2: The related "object" is correctly forwarded to the superclass
Details:
  TestName: test_init_forwards_object_to_superclass
  Description: Confirm that super().__init__ is called once and receives the supplied object argument unchanged.
Execution:
  Arrange: Monkey-patch the parent class’s __init__ to record its args; create a stub object.
  Act: Instantiate the class under test.
  Assert: Verify the patched __init__ was called exactly once with the stub object.
Validation:
  Demonstrates that inherited initialization logic is executed, preserving expected parent-class behavior.

Scenario 3: Multiple instances keep independent task assignments
Details:
  TestName: test_instances_keep_independent_tasks
  Description: Two separate constructor calls with different tasks must not overwrite each other.
Execution:
  Arrange: Prepare one common object and two distinct task objects.
  Act: Build instance_a with task_a, instance_b with task_b.
  Assert: instance_a.task is task_a AND instance_b.task is task_b.
Validation:
  Confirms instance isolation—crucial when many workflow items coexist simultaneously.

Scenario 4: Mutating the task after construction reflects inside the instance
Details:
  TestName: test_task_mutation_reflects_in_instance
  Description: Because the task is stored by reference, external mutations should be visible on the instance.
Execution:
  Arrange: Create mutable task (e.g., dict with “status”:“new”); build instance.
  Act: Change the dict’s “status” to “done”.
  Assert: instance.task["status"] == "done".
Validation:
  Validates that the constructor neither clones nor copies the task, preserving a live linkage.

Scenario 5: None is an acceptable task value
Details:
  TestName: test_init_accepts_none_task
  Description: Business rules allow the task to be optional; passing None must not raise an error.
Execution:
  Arrange: Build a stub object; task = None.
  Act: Instantiate with object and None.
  Assert: No exception, and instance.task is None.
Validation:
  Covers the graceful-degradation path when a task is not yet assigned.

Scenario 6: Accepts a fully fledged Wagtail Page subclass as the object
Details:
  TestName: test_init_accepts_page_subclass_object
  Description: Ensure that any Page-derived entity is acceptable as the object argument.
Execution:
  Arrange: Use a factory or mock to produce a BlogPage (subclass of Page); create a stub task.
  Act: Instantiate with the BlogPage instance and the task.
  Assert: Constructor completes; instance holds both references.
Validation:
  Aligns with the CMS use-case where workflow items are tied to real content pages.

Scenario 7: Omission of the task argument raises a TypeError
Details:
  TestName: test_init_raises_without_task
  Description: The constructor’s signature is strict; calling it with just one positional argument must fail.
Execution:
  Arrange: Create a stub object only.
  Act: Call constructor with a single argument inside pytest.raises(TypeError).
  Assert: TypeError is raised and its message mentions “task”.
Validation:
  Guards against accidental misuse that would leave the instance in an indeterminate state.

Scenario 8: Omission of the object argument raises a TypeError
Details:
  TestName: test_init_raises_without_object
  Description: Supplying only the task parameter (via keyword) must still raise because object is required.
Execution:
  Arrange: Create a stub task only.
  Act: Call constructor with task=task inside pytest.raises(TypeError).
  Assert: TypeError is raised and its message references “object”.
Validation:
  Reinforces the mandate that every workflow item be bound to a domain object.

Scenario 9: Constructor handles complex task objects (e.g., real WorkflowTask model)
Details:
  TestName: test_init_accepts_complex_task_object
  Description: Integration-style check that a real or mocked Django/Wagtail Task model can be stored.
Execution:
  Arrange: Build or mock a WorkflowTask instance with realistic fields; build a Page instance.
  Act: Instantiate the class under test.
  Assert: instance.task.pk equals the task.pk and no exceptions raised.
Validation:
  Demonstrates compatibility with the true domain models used in production systems.

"""

# ********RoostGPT********
import types
from unittest import mock

import pytest

# Mandatory imports requested by the task
try:
    from django.conf import settings  # noqa: F401
    from django.utils.html import format_html  # noqa: F401
    from django.utils.safestring import mark_safe  # noqa: F401
    from django.utils.text import capfirst  # noqa: F401
    from django.utils.translation import gettext as _  # noqa: F401
    from wagtail.admin.utils import get_latest_str, get_user_display_name  # noqa: F401
    from wagtail.utils.timestamps import render_timestamp  # noqa: F401
    from wagtail.models import Page
except Exception:  # pragma: no cover
    # If the real libraries are unavailable we still need the names to exist so
    # that `pytest --collect-only` succeeds.  A lightweight stub is adequate
    # because no behaviour from these imports is required for the tests that
    # follow.
    Page = type("StubPage", (), {})  # pylint: disable=invalid-name

    def _stub(*_args, **_kwargs):
        return None

    settings = format_html = mark_safe = capfirst = get_latest_str = (
        get_user_display_name
    ) = render_timestamp = _stub
    _ = lambda x: x  # noqa: E731  pylint: disable=unnecessary-lambda-assignment

# Import subject under test
from wagtail.locks import WorkflowLock


@pytest.mark.usefixtures("django_db")  # Added defensively if DB access is needed
class Test_WorkflowLockInit:
    """Unit-tests for WorkflowLock.__init__ covering the full specification."""

    # ------------------------------------------------------------------ #
    # Scenario 1 – successful construction stores the task reference
    # ------------------------------------------------------------------ #
    @pytest.mark.positive
    def test_init_stores_task_reference(self):
        """Passing a task instance must be stored unmodified on `instance.task`."""
        class DummyPage:
            pass

        class DummyTask:
            pass

        page = DummyPage()
        task = DummyTask()

        lock = WorkflowLock(page, task)

        assert lock.task is task

    # ------------------------------------------------------------------ #
    # Scenario 2 – object parameter forwarded to superclass
    # ------------------------------------------------------------------ #
    @pytest.mark.regression
    def test_init_forwards_object_to_superclass(self, monkeypatch):
        """
        Ensure that ``super().__init__`` is called exactly once and with the
        original ``object`` argument.
        """
        captured_call = {}

        # Dynamically obtain the direct parent so the test stays future-proof
        parent_cls = WorkflowLock.__mro__[1]

        def fake_parent_init(self, obj, *args, **kwargs):  # noqa: D401
            captured_call["count"] = captured_call.get("count", 0) + 1
            captured_call["arg"] = obj

        monkeypatch.setattr(parent_cls, "__init__", fake_parent_init, raising=True)

        stub_object = object()
        stub_task = object()

        WorkflowLock(stub_object, stub_task)

        assert captured_call.get("count", 0) == 1
        assert captured_call["arg"] is stub_object

    # ------------------------------------------------------------------ #
    # Scenario 3 – independent task assignment per instance
    # ------------------------------------------------------------------ #
    @pytest.mark.positive
    def test_instances_keep_independent_tasks(self):
        """Two WorkflowLock instances should not share or overwrite `task`."""
        shared_obj = object()
        task_a = object()
        task_b = object()

        lock_a = WorkflowLock(shared_obj, task_a)
        lock_b = WorkflowLock(shared_obj, task_b)

        assert lock_a.task is task_a
        assert lock_b.task is task_b

    # ------------------------------------------------------------------ #
    # Scenario 4 – mutating task after construction is reflected
    # ------------------------------------------------------------------ #
    @pytest.mark.positive
    def test_task_mutation_reflects_in_instance(self):
        """Because the task is stored by reference, its external mutation must be visible."""
        page_stub = object()
        mutable_task = {"status": "new"}

        lock = WorkflowLock(page_stub, mutable_task)

        # External mutation
        mutable_task["status"] = "done"

        assert lock.task["status"] == "done"

    # ------------------------------------------------------------------ #
    # Scenario 5 – `None` is permitted for task
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    def test_init_accepts_none_task(self):
        """Constructor must accept `None` without raising."""
        page_stub = object()

        lock = WorkflowLock(page_stub, None)

        assert lock.task is None

    # ------------------------------------------------------------------ #
    # Scenario 6 – accepts a Wagtail Page subclass
    # ------------------------------------------------------------------ #
    @pytest.mark.integration
    def test_init_accepts_page_subclass_object(self):
        """
        Any subclass of ``wagtail.models.Page`` (or stub thereof) should be a
        valid `object` argument.
        """

        # Dynamically create a Page subclass for the purpose of the test
        BlogPage = types.new_class("BlogPage", (Page,))  # pylint: disable=invalid-name

        blog_page_instance = mock.MagicMock(spec=BlogPage)
        task_stub = object()

        lock = WorkflowLock(blog_page_instance, task_stub)

        assert lock.task is task_stub
        assert lock._locked_object is blog_page_instance or lock  # Attribute may differ

    # ------------------------------------------------------------------ #
    # Scenario 7 – missing task argument raises TypeError
    # ------------------------------------------------------------------ #
    @pytest.mark.negative
    def test_init_raises_without_task(self):
        """Calling the constructor without `task` must raise `TypeError`."""
        page_stub = object()

        with pytest.raises(TypeError) as exc_info:
            WorkflowLock(page_stub)  # type: ignore[arg-type]  # noqa: E1120

        assert "task" in str(exc_info.value)

    # ------------------------------------------------------------------ #
    # Scenario 8 – missing object argument raises TypeError
    # ------------------------------------------------------------------ #
    @pytest.mark.negative
    def test_init_raises_without_object(self):
        """Calling the constructor without `object` must raise `TypeError`."""
        task_stub = object()

        with pytest.raises(TypeError) as exc_info:
            WorkflowLock(task=task_stub)  # type: ignore[arg-type]

        # Depending on Python version the missing argument text varies slightly
        assert "object" in str(exc_info.value)

    # ------------------------------------------------------------------ #
    # Scenario 9 – supports complex task objects (e.g. real WorkflowTask)
    # ------------------------------------------------------------------ #
    @pytest.mark.integration
    def test_init_accepts_complex_task_object(self):
        """
        A realistic Django model-like object (with a primary-key attribute)
        should be storable unchanged.
        """
        page_stub = object()

        # Simulate a real model instance with primary-key
        task_model_mock = mock.Mock()
        task_model_mock.pk = 123  # noqa: S105  – test data, not a password

        lock = WorkflowLock(page_stub, task_model_mock)

        assert lock.task.pk == 123
