# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=BatchCreator.initialize_instance_3df33a8302
ROOST_METHOD_SIG_HASH=BatchCreator.initialize_instance_902acced76


Scenario 1: Successful creation with all mandatory fields
Details:
  TestName: test_initialize_instance_returns_unsaved_model
  Description: Verify that the method returns an instance of the configured model, populated with the provided keyword arguments, and that the instance has not yet been persisted.
Execution:
  Arrange: Create a dummy class with its model attribute pointing to ExampleModel
           where ExampleModel defines fields `title` (char, required) and `views` (integer, default=0).
  Act: Call initialize_instance with kwargs {"title": "Hello", "views": 5}.
  Assert: Returned object is an ExampleModel instance; object.title == "Hello";
          object.views == 5; object.pk is None.
Validation:
  Confirms the happy path and that the method is only a constructor shortcut without implicit saving.

Scenario 2: Missing a required field should raise TypeError
Details:
  TestName: test_initialize_instance_missing_required_field_raises
  Description: Ensure that omitting a non-nullable, non-default field triggers Django’s constructor error.
Execution:
  Arrange: Stub model with required field `title` and optional field `views`.
  Act: Invoke initialize_instance with kwargs {"views": 3}.
  Assert: Use pytest.raises(TypeError).
Validation:
  Demonstrates that the wrapper does not swallow or alter Django’s native validation behavior.

Scenario 3: Unknown field name results in TypeError
Details:
  TestName: test_initialize_instance_unknown_field_raises
  Description: Providing a kwarg that is not a declared model field should be rejected.
Execution:
  Arrange: Same ExampleModel as in Scenario 1.
  Act: Call initialize_instance with {"title": "Hi", "bogus": 123}.
  Assert: pytest.raises(TypeError) as the constructor complains about an unexpected keyword.
Validation:
  Confirms that illegal attribute injection fails early and predictably.

Scenario 4: ForeignKey field accepts a related instance
Details:
  TestName: test_initialize_instance_accepts_foreign_key_instance
  Description: Validate that a related model instance can be supplied for a ForeignKey field.
Execution:
  Arrange: Create Author model, then Book model with ForeignKey to Author.
           Instantiate an Author object and save it to obtain a primary key.
           Set the owning class’s model attribute to Book.
  Act: Call initialize_instance with {"title": "Novel", "author": saved_author}.
  Assert: Returned Book instance.author is saved_author; book.pk is still None.
Validation:
  Ensures relational integrity and that initialize_instance does not prematurely persist either side.

Scenario 5: Default field values are applied when omitted
Details:
  TestName: test_initialize_instance_applies_model_defaults
  Description: Confirm that model-level default values populate fields not supplied in kwargs.
Execution:
  Arrange: ExampleModel has `views` with default=0; provide only {"title": "Untold"}.
  Act: initialize_instance(kwargs).
  Assert: instance.views == 0; instance.title == "Untold".
Validation:
  Proves that Django’s default mechanism survives the wrapper intact.

Scenario 6: Abstract model should raise TypeError on instantiation
Details:
  TestName: test_initialize_instance_abstract_model_raises
  Description: Attempting to instantiate a model marked `abstract = True` must fail.
Execution:
  Arrange: Define AbstractBase with Meta.abstract = True and set as self.model.
  Act: Call initialize_instance with empty kwargs.
  Assert: pytest.raises(TypeError).
Validation:
  Verifies safety against misconfiguration where the owning class accidentally points to an abstract model.

Scenario 7: Primary key provided but instance remains unsaved
Details:
  TestName: test_initialize_instance_with_explicit_pk_not_saved
  Description: Supplying a primary-key value should set the attribute but not contact the database.
Execution:
  Arrange: ExampleModel with AutoField id; choose arbitrary id=99.
  Act: initialize_instance({"id": 99, "title": "Manual PK"}).
  Assert: instance.id == 99; instance._state.adding is True; instance.pk == 99; querying DB confirms no row yet exists.
Validation:
  Confirms that initialize_instance mirrors Django semantics even with explicit PKs.

Scenario 8: Model attribute is None results in AttributeError
Details:
  TestName: test_initialize_instance_without_model_attribute
  Description: If the owning class forgot to set `model`, the method should fail fast.
Execution:
  Arrange: Create a bare class where `model = None`.
  Act: Call initialize_instance({}).
  Assert: pytest.raises(AttributeError).
Validation:
  Guards against developer misconfiguration and clarifies the contract that `model` must point to a valid class.

"""

# ********RoostGPT********
# pylint: disable=missing-docstring,unused-import,invalid-name,redefined-outer-name
# Standard library imports
import functools
import inspect
import logging
import re
import unicodedata
from collections.abc import Iterable
from hashlib import md5
from typing import TYPE_CHECKING, Any

# Third-party / optional imports – fall back gracefully if the real packages are absent
try:
    from anyascii import anyascii  # type: ignore
except ImportError:  # pragma: no cover
    anyascii = None  # type: ignore

try:
    from django.apps import apps  # type: ignore
    from django.conf import settings  # type: ignore
    from django.conf.locale import LANG_INFO  # type: ignore
    from django.core.cache import cache  # type: ignore
    from django.core.cache.utils import make_template_fragment_key  # type: ignore
    from django.core.exceptions import ImproperlyConfigured, SuspiciousOperation  # type: ignore
    from django.core.signals import setting_changed  # type: ignore
    from django.db.models import Model  # type: ignore
    from django.db.models.base import ModelBase  # type: ignore
    from django.dispatch import receiver  # type: ignore
    from django.http import HttpRequest  # type: ignore
    from django.test import RequestFactory  # type: ignore
    from django.utils.encoding import force_str  # type: ignore
    from django.utils.text import capfirst, slugify  # type: ignore
    from django.utils.translation import (
        check_for_language,
        get_supported_language_variant,
    )  # type: ignore
    from django.utils.translation import gettext as _  # type: ignore
except ImportError:  # pragma: no cover
    apps = settings = LANG_INFO = cache = make_template_fragment_key = None  # type: ignore
    ImproperlyConfigured = SuspiciousOperation = Exception  # type: ignore
    setting_changed = lambda *_, **__: None  # type: ignore
    Model = object  # type: ignore
    ModelBase = type  # type: ignore
    receiver = lambda *args, **kwargs: (lambda func: func)  # type: ignore
    HttpRequest = object  # type: ignore
    RequestFactory = object  # type: ignore
    force_str = str  # type: ignore
    capfirst = lambda s: s.capitalize()  # type: ignore
    slugify = lambda s: re.sub(r"[\s_]+", "-", str(s))  # type: ignore
    check_for_language = lambda code: True  # type: ignore
    get_supported_language_variant = lambda code: code  # type: ignore
    _ = lambda s: s  # type: ignore

# Application imports
import pytest
from wagtail.coreutils import BatchCreator


class Test_BatchCreatorInitializeInstance:
    @pytest.mark.smoke
    @pytest.mark.positive
    def test_initialize_instance_returns_unsaved_model(self):
        """Scenario 1 – happy path with all mandatory fields supplied."""

        class ExampleModel:
            def __init__(self, title: str, views: int = 0):
                self.title = title
                self.views = views
                self.pk = None  # Unsaved instance, mimicking Django behaviour
                self.id = self.pk  # Alias for convenience
                # Emulate Django ._state
                class _State:
                    adding = True

                self._state = _State()

        class ExampleCreator(BatchCreator):
            model = ExampleModel

        creator = ExampleCreator()
        instance = creator.initialize_instance({"title": "Hello", "views": 5})

        assert isinstance(instance, ExampleModel)
        assert instance.title == "Hello"
        assert instance.views == 5
        assert instance.pk is None
        assert instance._state.adding is True

    @pytest.mark.regression
    @pytest.mark.negative
    def test_initialize_instance_missing_required_field_raises(self):
        """Scenario 2 – omit required, non-defaulted field."""

        class ExampleModel:
            # 'title' has no default and is thus required
            def __init__(self, title: str, views: int = 0):
                self.title = title
                self.views = views

        class ExampleCreator(BatchCreator):
            model = ExampleModel

        creator = ExampleCreator()

        with pytest.raises(TypeError):
            creator.initialize_instance({"views": 3})

    @pytest.mark.regression
    @pytest.mark.negative
    def test_initialize_instance_unknown_field_raises(self):
        """Scenario 3 – supply an unexpected keyword argument."""

        class ExampleModel:
            def __init__(self, title: str, views: int = 0):
                self.title = title
                self.views = views

        class ExampleCreator(BatchCreator):
            model = ExampleModel

        creator = ExampleCreator()

        with pytest.raises(TypeError):
            creator.initialize_instance({"title": "Hi", "bogus": 123})

    @pytest.mark.regression
    @pytest.mark.positive
    def test_initialize_instance_accepts_foreign_key_instance(self):
        """Scenario 4 – ForeignKey receives a related instance."""

        class Author:
            def __init__(self, name: str, id_: int | None = None):
                self.name = name
                self.pk = id_
                self.id = id_

            def save(self):  # noqa: D401
                # Simple stand-in for Django save(); allocate a primary key
                if self.pk is None:
                    self.pk = 1  # TODO: Increment for successive calls if needed
                    self.id = self.pk

        class Book:
            def __init__(self, title: str, author: "Author"):  # noqa: F821
                self.title = title
                self.author = author
                self.pk = None

                class _State:
                    adding = True

                self._state = _State()

        class BookCreator(BatchCreator):
            model = Book

        saved_author = Author("Jane Austen")
        saved_author.save()  # Obtain a PK

        creator = BookCreator()
        book = creator.initialize_instance({"title": "Novel", "author": saved_author})

        assert book.author is saved_author
        assert book.pk is None
        assert book._state.adding is True

    @pytest.mark.smoke
    @pytest.mark.positive
    def test_initialize_instance_applies_model_defaults(self):
        """Scenario 5 – ensure model defaults propagate."""

        class ExampleModel:
            def __init__(self, title: str, views: int = 0):
                self.title = title
                self.views = views
                self.pk = None

        class ExampleCreator(BatchCreator):
            model = ExampleModel

        creator = ExampleCreator()
        instance = creator.initialize_instance({"title": "Untold"})

        assert instance.title == "Untold"
        assert instance.views == 0  # Default applied
        assert instance.pk is None

    @pytest.mark.security
    @pytest.mark.negative
    def test_initialize_instance_abstract_model_raises(self):
        """Scenario 6 – abstract models should not be instantiated."""

        class AbstractBase:
            class Meta:  # pylint: disable=too-few-public-methods
                abstract = True

            def __init__(self, *args, **kwargs):  # noqa: D401
                raise TypeError("Cannot instantiate abstract model")

        class AbstractCreator(BatchCreator):
            model = AbstractBase

        creator = AbstractCreator()

        with pytest.raises(TypeError):
            creator.initialize_instance({})

    @pytest.mark.regression
    @pytest.mark.positive
    def test_initialize_instance_with_explicit_pk_not_saved(self):
        """Scenario 7 – explicit primary key does not force immediate save."""

        class ExampleModel:
            def __init__(self, title: str, id: int | None = None):  # noqa: A002
                self.title = title
                self.id = id
                self.pk = id

                class _State:
                    adding = True

                self._state = _State()

        class ExampleCreator(BatchCreator):
            model = ExampleModel

        creator = ExampleCreator()
        instance = creator.initialize_instance({"id": 99, "title": "Manual PK"})

        assert instance.id == 99
        assert instance.pk == 99
        assert instance._state.adding is True

    @pytest.mark.invalid
    @pytest.mark.negative
    def test_initialize_instance_without_model_attribute(self):
        """Scenario 8 – missing ``model`` attribute triggers AttributeError."""

        class MisconfiguredCreator(BatchCreator):
            # Deliberately omitting 'model' attribute
            pass  # noqa: WPS420

        creator = MisconfiguredCreator()

        with pytest.raises(AttributeError):
            creator.initialize_instance({})
