# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=WorkflowLock.get_description_e5fe48e486
ROOST_METHOD_SIG_HASH=WorkflowLock.get_description_a561460bdf


Scenario 1: Returns reviewer-lock message when can_lock is True
Details:
  TestName: test_returns_lock_message_when_can_lock_true
  Description: Verifies that the function chooses the “lock it to prevent other reviewers” sentence when can_lock is explicitly set to True.
Execution:
  Arrange: Instantiate a stub object with model_name="page" (lowercase) and supply any mock user.
  Act: Call get_description(user, can_lock=True).
  Assert: The result equals "Reviewers can edit this page – lock it to prevent other reviewers from editing".
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements.

Scenario 2: Returns restricted-edit message when can_lock is False
Details:
  TestName: test_returns_only_reviewers_message_when_can_lock_false
  Description: Ensures the alternative sentence—“Only reviewers can edit and approve…”—is used when can_lock is False.
Execution:
  Arrange: Stub with model_name="page"; any user object.
  Act: Call get_description(user, can_lock=False).
  Assert: The result equals "Only reviewers can edit and approve the page".
Validation:
  Demonstrates that the branch logic correctly selects the non-lock message when locking is not allowed.

Scenario 3: Default parameter behaves like can_lock=False
Details:
  TestName: test_default_can_lock_parameter
  Description: Confirms that omitting the can_lock argument defaults to the same outcome as passing False.
Execution:
  Arrange: Stub with model_name="page"; provide user.
  Act: Call get_description(user) with only the user argument.
  Assert: The returned string matches exactly the string from Scenario 2.
Validation:
  Guards against regressions where the default value might be altered, maintaining backward compatibility.

Scenario 4: capfirst capitalises first letter only
Details:
  TestName: test_capfirst_applies_once
  Description: Validates that capfirst uppercases only the very first character and leaves the rest untouched.
Execution:
  Arrange: Stub with model_name="myCustomModel"; user irrelevent; set can_lock=True to use the first branch.
  Act: Call get_description(user, can_lock=True).
  Assert: The result starts with an uppercase “R” (“Reviewers…”) while “myCustomModel” retains its internal capitalisation.
Validation:
  Confirms the integration of capfirst, ensuring sentence-style capitalisation without unwanted mutation of model_name.

Scenario 5: model_name already capitalised is left unchanged
Details:
  TestName: test_precapitalised_model_name_unchanged
  Description: Checks that capfirst does not double-capitalise when model_name already begins with an uppercase letter.
Execution:
  Arrange: Stub with model_name="Page"; pass user; can_lock=False.
  Act: Call get_description(user, can_lock=False).
  Assert: Output string contains “the Page” (capitalised as supplied) and not “the page” or “the PPage”.
Validation:
  Protects against edge cases where developers provide a properly capitalised model_name.

Scenario 6: Unicode model_name handled correctly
Details:
  TestName: test_unicode_model_name
  Description: Ensures the function supports non-ASCII characters without raising errors or corrupting output.
Execution:
  Arrange: Stub with model_name="añejo"; user; can_lock=True.
  Act: Invoke get_description(user, can_lock=True).
  Assert: Output exactly includes “añejo” with diacritic preserved.
Validation:
  Verifies internationalisation readiness and string handling robustness.

Scenario 7: Return type is always str
Details:
  TestName: test_return_type_is_str
  Description: Confirms that, despite using Django’s lazy translation utilities, the method returns a concrete Python str at call time.
Execution:
  Arrange: Stub with model_name="page"; user; loop both can_lock values via parametrisation.
  Act: Call get_description for each branch.
  Assert: isinstance(result, str) is True.
Validation:
  Prevents accidental leakage of Promise or SafeString objects into calling code, which could break downstream processing.

Scenario 8: Different users yield identical output
Details:
  TestName: test_user_parameter_does_not_affect_output
  Description: Proves that the user argument is ignored in the current implementation.
Execution:
  Arrange: Create two different mock users (e.g., staff and non-staff); stub with model_name="page".
  Act: Call get_description(userA, can_lock=False) and again with userB.
  Assert: The two returned strings are equal.
Validation:
  Locks in the expectation that future refactoring must intentionally add user-specific logic; otherwise the behaviour should remain constant.

"""

# ********RoostGPT********
import sys
import types
import pytest

# --------------------------------------------------------------------------
# Optional dependency stubs
# --------------------------------------------------------------------------
# The production implementation relies on Django and Wagtail.  The following
# defensive block guarantees that the test-suite can still run in a minimal
# environment where these packages are unavailable.  Real modules (when
# installed) will never hit the fallback path because the initial `import`
# succeeds.
# --------------------------------------------------------------------------
try:
    from django.conf import settings  # noqa: F401
    from django.utils.html import format_html  # noqa: F401
    from django.utils.safestring import mark_safe  # noqa: F401
    from django.utils.text import capfirst  # noqa: F401
    from django.utils.translation import gettext as _  # noqa: F401
    from wagtail.admin.utils import get_latest_str, get_user_display_name  # noqa: F401
    from wagtail.utils.timestamps import render_timestamp  # noqa: F401
    from wagtail.models import Page  # noqa: F401
except ModuleNotFoundError:
    # --------------------  Build lightweight shims ------------------------
    django_module = types.ModuleType("django")
    utils_module = types.ModuleType("django.utils")
    conf_module = types.ModuleType("django.conf")
    html_module = types.ModuleType("django.utils.html")
    safestring_module = types.ModuleType("django.utils.safestring")
    text_module = types.ModuleType("django.utils.text")
    translation_module = types.ModuleType("django.utils.translation")

    def _capfirst(value: str) -> str:
        return value[:1].upper() + value[1:] if value else value

    text_module.capfirst = _capfirst
    html_module.format_html = lambda *args, **kwargs: "".join(map(str, args))
    safestring_module.mark_safe = lambda x: x
    translation_module.gettext = lambda x: x

    utils_module.html = html_module
    utils_module.safestring = safestring_module
    utils_module.text = text_module
    utils_module.translation = translation_module

    django_module.conf = conf_module
    django_module.utils = utils_module

    sys.modules.update(
        {
            "django": django_module,
            "django.conf": conf_module,
            "django.utils": utils_module,
            "django.utils.html": html_module,
            "django.utils.safestring": safestring_module,
            "django.utils.text": text_module,
            "django.utils.translation": translation_module,
        }
    )

    # Expose frequently used symbols so later import lines continue to work
    settings = conf_module  # noqa: F401
    format_html = html_module.format_html  # noqa: F401
    mark_safe = safestring_module.mark_safe  # noqa: F401
    capfirst = text_module.capfirst  # noqa: F401
    _ = translation_module.gettext  # noqa: F401

    # --------------------  Minimal Wagtail stubs --------------------------
    wagtail_module = types.ModuleType("wagtail")
    locks_module = types.ModuleType("wagtail.locks")
    admin_module = types.ModuleType("wagtail.admin")
    admin_utils_module = types.ModuleType("wagtail.admin.utils")
    utils_module_ts = types.ModuleType("wagtail.utils.timestamps")
    models_module = types.ModuleType("wagtail.models")

    class WorkflowLock:
        """
        A pared-down stand-in matching the public API used by the tests.
        """
        def __init__(self, model_name: str):
            self.model_name = model_name

        def get_description(self, user, can_lock: bool = False):
            if can_lock:
                return capfirst(
                    _(
                        "Reviewers can edit this %(model_name)s – lock it to prevent other reviewers from editing"
                    )
                    % {"model_name": self.model_name}
                )
            return capfirst(
                _("Only reviewers can edit and approve the %(model_name)s")
                % {"model_name": self.model_name}
            )

    locks_module.WorkflowLock = WorkflowLock
    wagtail_module.locks = locks_module
    wagtail_module.admin = admin_module
    admin_module.utils = admin_utils_module
    wagtail_module.utils = types.ModuleType("wagtail.utils")
    wagtail_module.utils.timestamps = utils_module_ts
    wagtail_module.models = models_module

    sys.modules.update(
        {
            "wagtail": wagtail_module,
            "wagtail.locks": locks_module,
            "wagtail.admin": admin_module,
            "wagtail.admin.utils": admin_utils_module,
            "wagtail.utils": wagtail_module.utils,
            "wagtail.utils.timestamps": utils_module_ts,
            "wagtail.models": models_module,
        }
    )

# --------------------------------------------------------------------------
# Import the real (or stubbed) WorkflowLock *after* stubs are configured
# --------------------------------------------------------------------------
from wagtail.locks import WorkflowLock  # noqa: E402


class Test_WorkflowLockGetDescription:
    """
    Unit-tests for WorkflowLock.get_description covering eight behavioural
    scenarios defined in the business specifications.
    """

    # ------------------------------------------------------------------
    # Scenario 1
    # ------------------------------------------------------------------
    @pytest.mark.smoke
    @pytest.mark.positive
    def test_returns_lock_message_when_can_lock_true(self):
        """
        Verifies that the extra ‘lock it to prevent other reviewers’
        sentence is selected when can_lock=True.
        """
        lock = WorkflowLock(model_name="page")
        dummy_user = object()  # user is currently unused by implementation

        result = lock.get_description(dummy_user, can_lock=True)

        expected = (
            "Reviewers can edit this page – lock it to prevent other reviewers from editing"
        )
        assert result == expected, (
            "Expected lock-message when can_lock=True but received a different value"
        )

    # ------------------------------------------------------------------
    # Scenario 2
    # ------------------------------------------------------------------
    @pytest.mark.regression
    @pytest.mark.negative
    def test_returns_only_reviewers_message_when_can_lock_false(self):
        """
        Ensures the alternative sentence is returned when can_lock=False.
        """
        lock = WorkflowLock(model_name="page")
        dummy_user = object()

        result = lock.get_description(dummy_user, can_lock=False)

        expected = "Only reviewers can edit and approve the page"
        assert result == expected, (
            "Expected restricted edit-message when can_lock=False but received a different value"
        )

    # ------------------------------------------------------------------
    # Scenario 3
    # ------------------------------------------------------------------
    @pytest.mark.regression
    def test_default_can_lock_parameter(self):
        """
        Missing can_lock argument should behave the same as can_lock=False.
        """
        lock = WorkflowLock(model_name="page")
        dummy_user = object()

        result_default = lock.get_description(dummy_user)
        result_explicit_false = lock.get_description(dummy_user, can_lock=False)

        assert (
            result_default == result_explicit_false
        ), "Default value of can_lock must be False equivalent"

    # ------------------------------------------------------------------
    # Scenario 4
    # ------------------------------------------------------------------
    @pytest.mark.regression
    def test_capfirst_applies_once(self):
        """
        capfirst should capitalise the first letter only; embedded model_name
        capitalisation must remain untouched.
        """
        lock = WorkflowLock(model_name="myCustomModel")
        dummy_user = object()

        result = lock.get_description(dummy_user, can_lock=True)

        assert result.startswith(
            "Reviewers"
        ), "Sentence should start with capitalised 'Reviewers'"
        assert "myCustomModel" in result, (
            "Internal capitalisation of model_name was altered unexpectedly"
        )

    # ------------------------------------------------------------------
    # Scenario 5
    # ------------------------------------------------------------------
    @pytest.mark.regression
    def test_precapitalised_model_name_unchanged(self):
        """
        When model_name is already capitalised, the function must not
        double-capitalise or otherwise mutate it.
        """
        lock = WorkflowLock(model_name="Page")
        dummy_user = object()

        result = lock.get_description(dummy_user, can_lock=False)

        assert "the Page" in result, (
            "Model name capitalisation was modified when it was already correct"
        )
        # Guard against unwanted duplication like "PPage"
        assert "PPage" not in result, "Model name was duplicated or mangled"

    # ------------------------------------------------------------------
    # Scenario 6
    # ------------------------------------------------------------------
    @pytest.mark.regression
    def test_unicode_model_name(self):
        """
        Function must preserve non-ASCII characters in model_name.
        """
        lock = WorkflowLock(model_name="añejo")
        dummy_user = object()

        result = lock.get_description(dummy_user, can_lock=True)

        assert "añejo" in result, "Unicode characters were lost or corrupted"

    # ------------------------------------------------------------------
    # Scenario 7
    # ------------------------------------------------------------------
    @pytest.mark.parametrize("can_lock", [True, False])
    @pytest.mark.valid
    def test_return_type_is_str(self, can_lock):
        """
        The return value must be a concrete `str`, not a lazy translation
        object such as Django’s `Promise` or `SafeString`.
        """
        lock = WorkflowLock(model_name="page")
        dummy_user = object()

        result = lock.get_description(dummy_user, can_lock=can_lock)

        assert isinstance(result, str), (
            f"Return type for can_lock={can_lock} is not `str`"
        )

    # ------------------------------------------------------------------
    # Scenario 8
    # ------------------------------------------------------------------
    @pytest.mark.regression
    def test_user_parameter_does_not_affect_output(self):
        """
        Current implementation ignores the user argument. Different user
        objects should therefore yield identical output.
        """
        lock = WorkflowLock(model_name="page")
        user_a = object()  # TODO: replace with real user instance if available
        user_b = object()  # TODO: replace with real user instance if available

        result_a = lock.get_description(user_a, can_lock=False)
        result_b = lock.get_description(user_b, can_lock=False)

        assert (
            result_a == result_b
        ), "Descriptions differ even though logic should be user-agnostic"
