# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=BatchCreator.extend_d13c6b75de
ROOST_METHOD_SIG_HASH=BatchCreator.extend_4edda967be


Scenario 1: Extending with only model instances
Details:
  TestName: test_extend_with_models_only
  Description: Verifies that every element recognised as an instance of self.model is forwarded to self.add via the instance keyword-argument interface.
Execution:
  Arrange: 
    • Instantiate the concrete collection class with a dummy Django model (e.g., SampleModel).  
    • Build a list containing several SampleModel objects.  
    • Spy or monkeypatch self.add so that it records its call-count and the received kwargs.
  Act:  
    • Call collection.extend(model_list).
  Assert:  
    • self.add is called exactly len(model_list) times.  
    • On every call, the first positional argument is absent and the keyword “instance” is present, carrying the original model object.
Validation:  
  Confirms the branch which treats iterable items as model objects, ensuring correct delegation and the absence of unexpected positional/keyword parameters.

Scenario 2: Extending with only dictionaries
Details:
  TestName: test_extend_with_dicts_only
  Description: Ensures that when all iterable elements are mapping objects, extend forwards them to self.add as unpacked keyword arguments.
Execution:
  Arrange:  
    • Prepare a list of dictionaries containing realistic field/value pairs.  
    • Monkeypatch self.add to capture incoming **kwargs.
  Act:  
    • Invoke extend(dict_list).
  Assert:  
    • self.add is called once per dictionary.  
    • Each call receives exactly the key/value pairs from the originating dictionary (no “instance” key is present).
Validation:  
  Validates the code path that handles non-model input and confirms that **value expansion works as expected.

Scenario 3: Mixed models and dictionaries
Details:
  TestName: test_extend_with_mixed_iterable
  Description: Confirms that extend can process heterogeneous iterables, correctly distinguishing between model objects and mappings on an item-by-item basis.
Execution:
  Arrange:  
    • Construct a list like [SampleModel(), {"title": "A"}, SampleModel(), {"title": "B"}].  
    • Monkeypatch self.add to store each call’s argument signature in sequence.
  Act:  
    • Call extend(mixed_list).
  Assert:  
    • Exactly four calls occur.  
    • Calls 1 and 3 contain the “instance” keyword, calls 2 and 4 contain expanded dictionary keys.  
    • The chronological order of calls matches the original iterable order.
Validation:  
  Demonstrates that flow control inside the loop is performed per item and that ordering is preserved—critical for deterministic downstream behaviour.

Scenario 4: Empty iterable produces no side effects
Details:
  TestName: test_extend_with_empty_iterable
  Description: Checks that calling extend with an empty list results in no attempts to call self.add and leaves state counters untouched.
Execution:
  Arrange:  
    • Instantiate the collection with added_count initialised to zero.  
    • Monkeypatch self.add to raise if invoked.
  Act:  
    • Call extend([]).
  Assert:  
    • self.add is never called.  
    • added_count remains 0.  
Validation:  
  Protects against unnecessary work and guards counters from accidental mutation when nothing is supplied.

Scenario 5: Non-iterable input raises TypeError early
Details:
  TestName: test_extend_with_none
  Description: Passing None (or another non-iterable) should immediately raise a TypeError because the for-loop cannot iterate it.
Execution:
  Arrange:  
    • Have a ready instance of the collection class.
  Act:  
    • Wrap extend(None) inside pytest.raises(TypeError).
  Assert:  
    • A TypeError (or its subclass) is raised before self.add is ever reached.
Validation:  
  Ensures robustness against programmer mistakes and mirrors Python’s own iteration contract.

Scenario 6: Item of unsupported type inside iterable
Details:
  TestName: test_extend_with_invalid_item
  Description: Verifies that if an element is neither a model instance nor a mapping, extend fails loudly rather than silently ignoring the value.
Execution:
  Arrange:  
    • List contains a valid dict followed by an int.  
    • Spy on self.add to observe first successful call.
  Act:  
    • Execute extend(list_with_int) inside pytest.raises(TypeError).
  Assert:  
    • The first dict causes one successful self.add call.  
    • A TypeError arises at the int, terminating the loop.
Validation:  
  Confirms defensive programming by ensuring unknown item types are not swallowed, maintaining data integrity.

Scenario 7: Iterable supplied as a generator
Details:
  TestName: test_extend_with_generator_iterable
  Description: Checks that extend does not assume random access or length, functioning correctly with single-pass generator objects.
Execution:
  Arrange:  
    • Define a generator expression that yields alternating model instances and dictionaries.  
    • Spy on self.add.
  Act:  
    • Call extend(generator).
  Assert:  
    • self.add receives calls exactly matching the number of items yielded.  
    • The order matches the yield sequence.
Validation:  
  Provides confidence that extend adheres to Python’s iterable protocol broadly, enabling memory-efficient pipelines.

Scenario 8: added_count is incremented cumulatively
Details:
  TestName: test_extend_updates_added_count
  Description: After extend completes, the collection’s added_count should reflect the number of elements processed in addition to any previous value.
Execution:
  Arrange:  
    • Start with added_count preset to 5.  
    • Prepare an iterable with 3 dictionaries.  
  Act:  
    • Invoke extend(dicts).  
  Assert:  
    • added_count equals 8 (original 5 + 3 new).
Validation:  
  Validates integration between extend and self.add side effects, ensuring high-level counters stay consistent with actual insertions.

Scenario 9: max_size boundary triggers batch processing
Details:
  TestName: test_extend_triggers_process_on_max_size
  Description: When self.max_size is defined and extend crosses that boundary, the internal process() callback should be invoked automatically.
Execution:
  Arrange:  
    • Configure the collection with max_size=3 and monkeypatch process() to flag execution.  
    • Build iterable of exactly 3 model instances.
  Act:  
    • Call extend(models).  
  Assert:  
    • process() is called once once the third item is added.  
    • added_count becomes 3.  
Validation:  
  Ensures that extend + add work together to handle batching semantics crucial for performance or transactional grouping.

Scenario 10: Order preservation inside self.items
Details:
  TestName: test_extend_preserves_item_order
  Description: After extend, the sequence of items stored in self.items should match the sequence supplied, regardless of type.
Execution:
  Arrange:  
    • Provide a mixed iterable of identifiable payloads (e.g., dicts {"id": 1} … {"id": n}).  
  Act:  
    • Run extend.  
  Assert:  
    • self.items is in the exact same order as the original iterable values (the instance objects or the constructed objects, depending on implementation).
Validation:  
  Ordering often influences downstream logic such as user display or deterministic hashing; guaranteeing preservation is therefore business-critical.

"""

# ********RoostGPT********
import sys
import types
import functools
import inspect
import logging
import re
import unicodedata
from collections.abc import Iterable
from hashlib import md5
from typing import TYPE_CHECKING, Any

# Third-party / Django / Wagtail imports – stubbed when missing
optional_modules = [
    "anyascii",
    "django",
    "django.apps",
    "django.conf",
    "django.conf.locale",
    "django.core",
    "django.core.cache",
    "django.core.cache.utils",
    "django.core.exceptions",
    "django.core.signals",
    "django.db",
    "django.db.models",
    "django.db.models.base",
    "django.dispatch",
    "django.http",
    "django.test",
    "django.utils",
    "django.utils.encoding",
    "django.utils.text",
    "django.utils.translation",
    "wagtail",
    "wagtail.models",
    "wagtail.coreutils",
]
for name in optional_modules:
    if name not in sys.modules:
        sys.modules[name] = types.ModuleType(name)

# Ensure dotted-path attributes resolve on parents
for name in optional_modules:
    parts = name.split(".")
    for i in range(1, len(parts)):
        parent = ".".join(parts[:i])
        child = ".".join(parts[: i + 1])
        setattr(sys.modules[parent], parts[i], sys.modules[child])

import anyascii  # type: ignore  # noqa: E402
from django.apps import apps  # type: ignore  # noqa: E402
from django.conf import settings  # type: ignore  # noqa: E402
from django.conf.locale import LANG_INFO  # type: ignore  # noqa: E402
from django.core.cache import cache  # type: ignore  # noqa: E402
from django.core.cache.utils import make_template_fragment_key  # type: ignore  # noqa: E402
from django.core.exceptions import ImproperlyConfigured, SuspiciousOperation  # type: ignore  # noqa: E402
from django.core.signals import setting_changed  # type: ignore  # noqa: E402
from django.db.models import Model  # type: ignore  # noqa: E402
from django.db.models.base import ModelBase  # type: ignore  # noqa: E402
from django.dispatch import receiver  # type: ignore  # noqa: E402
from django.http import HttpRequest  # type: ignore  # noqa: E402
from django.test import RequestFactory  # type: ignore  # noqa: E402
from django.utils.encoding import force_str  # type: ignore  # noqa: E402
from django.utils.text import capfirst, slugify  # type: ignore  # noqa: E402
from django.utils.translation import (  # type: ignore  # noqa: E402
    check_for_language,
    get_supported_language_variant,
)
from wagtail.models import Site, Locale  # type: ignore  # noqa: E402

from wagtail.coreutils import BatchCreator  # type: ignore  # noqa: E402
import pytest  # noqa: E402


class Test_BatchCreatorExtend:
    # ------------------------------------------------------------------ #
    # Scenario 1
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    def test_extend_with_models_only(self, monkeypatch):
        class SampleModel:
            pass

        collection = BatchCreator(model=SampleModel)
        model_items = [SampleModel() for _ in range(4)]

        recorded_calls: list[tuple[tuple, dict]] = []

        def fake_add(*args, **kwargs):
            recorded_calls.append((args, kwargs))

        monkeypatch.setattr(collection, "add", fake_add)

        collection.extend(model_items)

        assert len(recorded_calls) == len(model_items)
        for positional, keyword in recorded_calls:
            assert positional == ()
            assert "instance" in keyword
            assert keyword["instance"] in model_items

    # ------------------------------------------------------------------ #
    # Scenario 2
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    def test_extend_with_dicts_only(self, monkeypatch):
        class SampleModel:
            def __init__(self, **kwargs):
                self.__dict__.update(kwargs)

        collection = BatchCreator(model=SampleModel)
        dict_items = [
            {"title": "A", "seq": 1},
            {"title": "B", "seq": 2},
            {"title": "C", "seq": 3},
        ]

        received_kwargs: list[dict] = []

        def spy_add(*args, **kwargs):
            received_kwargs.append(kwargs)

        monkeypatch.setattr(collection, "add", spy_add)

        collection.extend(dict_items)

        assert len(received_kwargs) == len(dict_items)
        for original, captured in zip(dict_items, received_kwargs, strict=True):
            assert captured == original
            assert "instance" not in captured

    # ------------------------------------------------------------------ #
    # Scenario 3
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    def test_extend_with_mixed_iterable(self, monkeypatch):
        class SampleModel:
            pass

        collection = BatchCreator(model=SampleModel)
        mixed_iterable = [
            SampleModel(),
            {"title": "Alpha"},
            SampleModel(),
            {"title": "Beta"},
        ]

        call_signatures: list[dict] = []

        def tracer(*args, **kwargs):
            call_signatures.append(kwargs.copy())

        monkeypatch.setattr(collection, "add", tracer)

        collection.extend(mixed_iterable)

        assert len(call_signatures) == 4
        assert "instance" in call_signatures[0] and "instance" in call_signatures[2]
        assert "instance" not in call_signatures[1] and "instance" not in call_signatures[3]
        # Ensure order preserved
        assert call_signatures[1]["title"] == "Alpha"
        assert call_signatures[3]["title"] == "Beta"

    # ------------------------------------------------------------------ #
    # Scenario 4
    # ------------------------------------------------------------------ #
    @pytest.mark.negative
    def test_extend_with_empty_iterable(self, monkeypatch):
        class SampleModel:
            pass

        collection = BatchCreator(model=SampleModel)
        collection.added_count = 0

        def fail_if_called(*args, **kwargs):
            raise AssertionError("add() should not be called for empty iterable")

        monkeypatch.setattr(collection, "add", fail_if_called)

        collection.extend([])

        assert collection.added_count == 0

    # ------------------------------------------------------------------ #
    # Scenario 5
    # ------------------------------------------------------------------ #
    @pytest.mark.invalid
    def test_extend_with_none(self, monkeypatch):
        class SampleModel:
            pass

        collection = BatchCreator(model=SampleModel)

        def sentinel(*args, **kwargs):
            raise AssertionError("add() must not be reached when input is None")

        monkeypatch.setattr(collection, "add", sentinel)

        with pytest.raises(TypeError):
            collection.extend(None)  # type: ignore[arg-type]

    # ------------------------------------------------------------------ #
    # Scenario 6
    # ------------------------------------------------------------------ #
    @pytest.mark.invalid
    def test_extend_with_invalid_item(self, monkeypatch):
        class SampleModel:
            def __init__(self, **kwargs):
                self.__dict__.update(kwargs)

        collection = BatchCreator(model=SampleModel)
        calls: list[dict] = []

        def spy_add(*args, **kwargs):
            calls.append(kwargs)

        monkeypatch.setattr(collection, "add", spy_add)

        data = [{"name": "valid"}, 42]  # int is invalid

        with pytest.raises(TypeError):
            collection.extend(data)

        # First dict should have been processed successfully
        assert len(calls) == 1
        assert calls[0] == {"name": "valid"}

    # ------------------------------------------------------------------ #
    # Scenario 7
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    def test_extend_with_generator_iterable(self, monkeypatch):
        class SampleModel:
            pass

        collection = BatchCreator(model=SampleModel)

        def generator():
            yield SampleModel()
            yield {"foo": "bar"}
            yield SampleModel()

        observed: list[dict] = []

        def record(*args, **kwargs):
            observed.append(kwargs)

        monkeypatch.setattr(collection, "add", record)

        collection.extend(generator())

        assert len(observed) == 3
        assert "instance" in observed[0] and isinstance(observed[0]["instance"], SampleModel)
        assert observed[1] == {"foo": "bar"}
        assert "instance" in observed[2] and isinstance(observed[2]["instance"], SampleModel)

    # ------------------------------------------------------------------ #
    # Scenario 8
    # ------------------------------------------------------------------ #
    @pytest.mark.regression
    def test_extend_updates_added_count(self):
        class SampleModel:
            def __init__(self, **kwargs):
                self.__dict__.update(kwargs)

        collection = BatchCreator(model=SampleModel)
        collection.added_count = 5  # preset value

        dicts = [{"idx": 1}, {"idx": 2}, {"idx": 3}]
        collection.extend(dicts)

        assert collection.added_count == 8  # 5 + 3

    # ------------------------------------------------------------------ #
    # Scenario 9
    # ------------------------------------------------------------------ #
    @pytest.mark.performance
    def test_extend_triggers_process_on_max_size(self, monkeypatch):
        class SampleModel:
            pass

        collection = BatchCreator(model=SampleModel)
        collection.max_size = 3  # activate batching

        process_called = {"count": 0}

        def fake_process():
            process_called["count"] += 1

        monkeypatch.setattr(collection, "process", fake_process)

        models = [SampleModel(), SampleModel(), SampleModel()]
        collection.extend(models)

        assert process_called["count"] == 1
        assert collection.added_count == 3

    # ------------------------------------------------------------------ #
    # Scenario 10
    # ------------------------------------------------------------------ #
    @pytest.mark.smoke
    def test_extend_preserves_item_order(self, monkeypatch):
        class SampleModel:
            pass

        collection = BatchCreator(model=SampleModel)
        collection.items = []  # ensure fresh list

        original_items: list[Any] = [
            {"id": 1},
            SampleModel(),
            {"id": 2},
            SampleModel(),
            {"id": 3},
        ]

        def order_preserving_add(*args, **kwargs):
            if "instance" in kwargs:
                collection.items.append(kwargs["instance"])
            else:
                collection.items.append(kwargs.copy())

        monkeypatch.setattr(collection, "add", order_preserving_add)

        collection.extend(original_items)

        assert len(collection.items) == len(original_items)
        # Compare object identity or dict equality in sequence
        for supplied, stored in zip(original_items, collection.items, strict=True):
            if isinstance(supplied, dict):
                assert supplied == stored
            else:
                assert supplied is stored
