# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=WorkflowLock.get_locked_by_3c4bf91e96
ROOST_METHOD_SIG_HASH=WorkflowLock.get_locked_by_dd5163f377


Scenario 1: Returns “Unlocked” when the caller has locking permission
Details:
  TestName: test_returns_unlocked_if_can_lock_true
  Description: Verify that the method outputs the word “Unlocked” whenever can_lock is True, confirming the positive branch of the business rule.
Execution:
  Arrange: Create a fake or real Django user (e.g., via django.contrib.auth.get_user_model) but do not grant or revoke any special permissions; set can_lock to True.
  Act: Call get_locked_by(user, can_lock=True).
  Assert: The returned value equals "Unlocked" (or its lazy equivalent) and contains no HTML characters.
Validation:
  This proves that the function correctly recognises the caller’s ability to unlock and surfaces the proper status label required by the Wagtail UI.

Scenario 2: Returns “Locked by workflow” when the caller cannot unlock the page
Details:
  TestName: test_returns_locked_when_can_lock_false
  Description: Validate the negative branch, ensuring that the status message reflects an ongoing workflow lock when can_lock is False.
Execution:
  Arrange: Instantiate a user object; leave can_lock as its default False.
  Act: Call get_locked_by(user).
  Assert: The returned value equals "Locked by workflow".
Validation:
  Demonstrates adherence to the business rule that pages remain reported as locked while the user lacks permission to unlock.

Scenario 3: Function ignores user argument when permission flag is True
Details:
  TestName: test_user_irrelevant_when_unlocked
  Description: Confirm that passing None instead of a user does not alter the “Unlocked” outcome.
Execution:
  Arrange: No user object is created; set user=None; set can_lock=True.
  Act: Call get_locked_by(None, can_lock=True).
  Assert: Response is "Unlocked".
Validation:
  Safeguards against future refactors that might unexpectedly depend on a valid user object for the success path.

Scenario 4: Different users yield identical “Locked by workflow” result
Details:
  TestName: test_same_locked_message_for_any_user
  Description: Ensure the output does not vary between two distinct authenticated users when neither can unlock the page.
Execution:
  Arrange: Create two separate user instances, alice and bob; keep can_lock=False.
  Act: Invoke get_locked_by(alice) and get_locked_by(bob).
  Assert: Both invocations return the same string object value "Locked by workflow".
Validation:
  Confirms that the lock status message is independent of who the current user is, fulfilling a consistent user-experience requirement.

Scenario 5: Output is correctly translated under a non-English locale
Details:
  TestName: test_translation_under_different_locale
  Description: Under a temporarily overridden locale (e.g., Spanish), verify that the returned text is translated while still mapping to the correct logical branch.
Execution:
  Arrange: Use django.utils.translation.override("es") as a context manager; create any user; set can_lock=False.
  Act: Call get_locked_by(user) within the override context.
  Assert: The result is not exactly "Locked by workflow" (English) but is still a string and differs from the English text, demonstrating translation; outside the context, the English value is restored.
Validation:
  Ensures the function honours Django’s i18n machinery, a critical business requirement for multilingual Wagtail installations.

"""

# ********RoostGPT********
import pytest
from django.contrib.auth import get_user_model
from django.utils.translation import override

from wagtail.locks import WorkflowLock


@pytest.mark.django_db
class Test_WorkflowLockGetLockedBy:
    @pytest.fixture()
    def lock(self):
        return WorkflowLock()

    # Scenario 1
    @pytest.mark.smoke
    @pytest.mark.positive
    def test_returns_unlocked_if_can_lock_true(self, lock):
        """
        Verify that the method outputs “Unlocked” whenever can_lock is True.
        """
        user_model = get_user_model()
        user = user_model.objects.create_user(
            username="tester", password="test123"  # TODO: update credentials if needed
        )

        result = lock.get_locked_by(user, can_lock=True)
        result_text = str(result)

        assert result_text == "Unlocked"
        # Ensure the string is plain text without any HTML characters.
        assert "<" not in result_text and ">" not in result_text and "&" not in result_text

    # Scenario 2
    @pytest.mark.regression
    @pytest.mark.negative
    def test_returns_locked_when_can_lock_false(self, lock):
        """
        Ensure that the status message reflects a workflow lock when can_lock is False.
        """
        user_model = get_user_model()
        user = user_model.objects.create_user(username="user_no_lock", password="pw")

        result = lock.get_locked_by(user)  # can_lock defaults to False
        assert str(result) == "Locked by workflow"

    # Scenario 3
    @pytest.mark.regression
    @pytest.mark.positive
    def test_user_irrelevant_when_unlocked(self, lock):
        """
        Passing None instead of a user does not alter the “Unlocked” outcome.
        """
        result = lock.get_locked_by(None, can_lock=True)
        assert str(result) == "Unlocked"

    # Scenario 4
    @pytest.mark.regression
    def test_same_locked_message_for_any_user(self, lock):
        """
        The output should not vary between two distinct users when neither can unlock.
        """
        user_model = get_user_model()
        alice = user_model.objects.create_user(username="alice", password="alice_pw")
        bob = user_model.objects.create_user(username="bob", password="bob_pw")

        result_alice = lock.get_locked_by(alice)
        result_bob = lock.get_locked_by(bob)

        assert str(result_alice) == "Locked by workflow"
        assert str(result_bob) == "Locked by workflow"
        # They should be identical strings
        assert str(result_alice) == str(result_bob)

    # Scenario 5
    @pytest.mark.security
    @pytest.mark.i18n
    def test_translation_under_different_locale(self, lock):
        """
        Verify that the returned text is translated under a Spanish locale.
        """
        user_model = get_user_model()
        user = user_model.objects.create_user(username="spanish_user", password="pw")

        with override("es"):
            result_es = lock.get_locked_by(user)  # can_lock defaults to False
            result_es_text = str(result_es)

            # If the translation catalog for this text exists, it will differ from English.
            # If it doesn't, the test is skipped to avoid false negatives.
            if result_es_text == "Locked by workflow":
                pytest.skip(
                    "Spanish translation not available for 'Locked by workflow'; "
                    "skipping locale-specific assertion."
                )

            assert isinstance(result_es_text, str)
            assert result_es_text != "Locked by workflow"

        # After exiting the override context, it should revert back to English
        result_en = lock.get_locked_by(user)
        assert str(result_en) == "Locked by workflow"
