# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=ScheduledForPublishLock.get_locked_by_d06e2d4ccf
ROOST_METHOD_SIG_HASH=ScheduledForPublishLock.get_locked_by_41b18b2414


Scenario 1: Constant message returned for a normal user and page
Details:
  TestName: test_locked_by_returns_constant_message
  Description: Verify that calling get_locked_by on a standard Page instance with a regular authenticated User returns the exact, untranslated message “Locked by schedule”.
Execution:
  Arrange: Create a Page-like dummy object (or use wagtail Page factory) and a standard django.auth User.
  Act: Invoke page.get_locked_by(user).
  Assert: The result equals "Locked by schedule" (string comparison).
Validation:
  Confirms that the business rule “always display the constant lock notification” is honored irrespective of typical caller context.

Scenario 2: Function is agnostic to the caller object
Details:
  TestName: test_locked_by_ignores_self_content
  Description: Demonstrate that the value of self has no influence on the return value by passing an arbitrary stub object instead of a real Page.
Execution:
  Arrange: Define a lightweight dummy class with get_locked_by bound as an instance method.
  Act: Call dummy_instance.get_locked_by(user) where user is any valid User.
  Assert: Result is "Locked by schedule".
Validation:
  Shows that the method’s implementation is self-independent, meeting the requirement that it always yield the constant message.

Scenario 3: Anonymous or None user produces the same output
Details:
  TestName: test_locked_by_with_anonymous_user
  Description: Ensure the lock message does not depend on user identity by passing django.contrib.auth.models.AnonymousUser or even None.
Execution:
  Arrange: Build a valid Page object (or stub) and obtain AnonymousUser() or set user = None.
  Act: Call page.get_locked_by(user).
  Assert: Result equals "Locked by schedule".
Validation:
  Strengthens confidence that the function’s logic is user-agnostic, complying with the specification that the text is unconditional.

Scenario 4: Execution inside a language override without translation file
Details:
  TestName: test_locked_by_language_override_no_translation
  Description: Within Django’s translation.override context set to a language code that lacks a message catalog (e.g., "xx"), ensure the fallback English string is delivered.
Execution:
  Arrange: Enter translation.override("xx") context; instantiate Page and User.
  Act: Call page.get_locked_by(user).
  Assert: Result is the English literal "Locked by schedule".
Validation:
  Verifies graceful degradation when no locale resource is present, guarding against missing-translation regressions.

Scenario 5: Execution with mocked translation returning a localized string
Details:
  TestName: test_locked_by_uses_gettext
  Description: Patch or monkeypatch the translation function _ to return a sentinel value (e.g., "Bloqueado por horario") and assert that get_locked_by propagates it unchanged.
Execution:
  Arrange: Monkeypatch module_scope._ to return "Bloqueado por horario"; create dummy page and user.
  Act: Invoke page.get_locked_by(user).
  Assert: Result equals the patched localized string.
Validation:
  Confirms the method delegates to Django’s i18n layer rather than hard-coding text, satisfying internationalization requirements.

Scenario 6: Return value is a plain string, not marked as safe HTML
Details:
  TestName: test_locked_by_returns_plain_string_not_safe
  Description: Make sure the result is not an instance of django.utils.safestring.SafeString, preventing accidental HTML auto-escape bypass.
Execution:
  Arrange: Instantiate Page and User.
  Act: res = page.get_locked_by(user)
  Assert: isinstance(res, str) is True AND not hasattr(res, "__html__")
Validation:
  Ensures that downstream templates remain protected from XSS because the function does not mark its output safe.

Scenario 7: Stress test with unusual self and user inputs
Details:
  TestName: test_locked_by_with_unexpected_inputs
  Description: Call get_locked_by with self=None or user objects missing typical attributes to confirm the method still returns the constant message without raising.
Execution:
  Arrange: self = None; user = object()  # generic Python object
  Act: get_locked_by(self, user)  # using the raw function rather than bound method
  Assert: Output equals "Locked by schedule".
Validation:
  Guards against accidental refactors that might start referencing self or user properties, ensuring robustness under edge conditions.

"""

# ********RoostGPT********
import importlib
import pytest
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AnonymousUser
from django.utils.translation import override
from django.utils.safestring import SafeString

from wagtail.locks import ScheduledForPublishLock

# Constant expected result used in multiple scenarios
EXPECTED_LOCK_MESSAGE = "Locked by schedule"


@pytest.mark.smoke
@pytest.mark.positive
@pytest.mark.django_db
class Test_ScheduledForPublishLockGetLockedBy:
    # --------------------------------------------------------------------- #
    # Scenario 1                                                            #
    # --------------------------------------------------------------------- #
    def test_locked_by_returns_constant_message(self):
        """
        Verify that calling get_locked_by on a standard Page-like instance
        with a regular authenticated User returns the exact message
        'Locked by schedule'.
        """
        user_model = get_user_model()
        user = user_model.objects.create_user(  # noqa: S106
            username="tester",
            password="password",  # TODO: Replace with stronger password policy if needed
        )
        lock = ScheduledForPublishLock()

        result = lock.get_locked_by(user)

        assert result == EXPECTED_LOCK_MESSAGE

    # --------------------------------------------------------------------- #
    # Scenario 2                                                            #
    # --------------------------------------------------------------------- #
    def test_locked_by_ignores_self_content(self):
        """
        Demonstrate that the value of self has no influence on the return
        value by passing an arbitrary stub object instead of a real Page.
        """
        class Dummy:  # lightweight stand-in object
            pass

        dummy_instance = Dummy()
        # Bind the method from ScheduledForPublishLock to the dummy instance
        dummy_instance.get_locked_by = ScheduledForPublishLock.get_locked_by.__get__(
            dummy_instance, Dummy
        )

        user_model = get_user_model()
        user = user_model(username="any")  # unsaved user is sufficient, no DB I/O

        result = dummy_instance.get_locked_by(user)

        assert result == EXPECTED_LOCK_MESSAGE

    # --------------------------------------------------------------------- #
    # Scenario 3                                                            #
    # --------------------------------------------------------------------- #
    @pytest.mark.regression
    def test_locked_by_with_anonymous_user(self):
        """
        Ensure the lock message does not depend on user identity by passing
        AnonymousUser or None.
        """
        lock = ScheduledForPublishLock()

        anonymous_result = lock.get_locked_by(AnonymousUser())
        none_result = lock.get_locked_by(None)

        assert anonymous_result == EXPECTED_LOCK_MESSAGE
        assert none_result == EXPECTED_LOCK_MESSAGE

    # --------------------------------------------------------------------- #
    # Scenario 4                                                            #
    # --------------------------------------------------------------------- #
    def test_locked_by_language_override_no_translation(self):
        """
        Within a language override where no translation file exists,
        ensure the fallback English string is delivered.
        """
        lock = ScheduledForPublishLock()

        with override("xx"):  # language code 'xx' unlikely to have translations
            result = lock.get_locked_by(None)

        assert result == EXPECTED_LOCK_MESSAGE

    # --------------------------------------------------------------------- #
    # Scenario 5                                                            #
    # --------------------------------------------------------------------- #
    def test_locked_by_uses_gettext(self, monkeypatch):
        """
        Patch the translation function `_` to return a localized string and
        assert that get_locked_by propagates it unchanged.
        """
        sentinel_translation = "Bloqueado por horario"
        locks_module = importlib.import_module("wagtail.locks")

        # Monkey-patch the global `_` used inside wagtail.locks
        monkeypatch.setattr(locks_module, "_", lambda msg: sentinel_translation)

        lock = ScheduledForPublishLock()
        result = lock.get_locked_by(None)

        assert result == sentinel_translation

    # --------------------------------------------------------------------- #
    # Scenario 6                                                            #
    # --------------------------------------------------------------------- #
    def test_locked_by_returns_plain_string_not_safe(self):
        """
        Ensure the result is a plain string, not marked as SafeString,
        preventing accidental HTML auto-escape bypass.
        """
        lock = ScheduledForPublishLock()
        res = lock.get_locked_by(None)

        assert isinstance(res, str)
        # It should NOT be a SafeString (i.e., not pre-marked safe)
        assert not isinstance(res, SafeString)
        # Additionally, SafeString exposes __html__; normal str should not.
        assert not hasattr(res, "__html__")

    # --------------------------------------------------------------------- #
    # Scenario 7                                                            #
    # --------------------------------------------------------------------- #
    def test_locked_by_with_unexpected_inputs(self):
        """
        Call get_locked_by with self=None or user objects missing
        typical attributes to confirm the method still returns the constant
        message without raising.
        """
        arbitrary_user_like_object = object()  # lacks auth attributes

        # Directly call the underlying function, bypassing instance binding
        result = ScheduledForPublishLock.get_locked_by(None, arbitrary_user_like_object)

        assert result == EXPECTED_LOCK_MESSAGE
