# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=BaseLock.get_icon_ee22150f0a
ROOST_METHOD_SIG_HASH=BaseLock.get_icon_1d49855096


Scenario 1: Constant icon for a standard authenticated user  
Details:  
  TestName: test_get_icon_returns_lock_for_authenticated_user  
  Description: Verify that an ordinary, authenticated Django User instance receives the hard-coded string "lock" from get_icon.  
Execution:  
  Arrange: Create or retrieve a typical django.contrib.auth.models.User marked as is_active=True and is_authenticated=True. Instantiate (or otherwise obtain) the class that owns get_icon.  
  Act: Call instance.get_icon(user).  
  Assert: Confirm the returned value is exactly the string "lock".  
Validation: This test guarantees that the primary business rule—always delivering the “lock” icon—holds true for the most common caller type (a logged-in user), ensuring UI consistency for every authenticated request.  

Scenario 2: Constant icon for an AnonymousUser  
Details:  
  TestName: test_get_icon_returns_lock_for_anonymous_user  
  Description: Ensure the function behaves identically when the caller supplies django.contrib.auth.models.AnonymousUser, which mimics an unauthenticated visitor.  
Execution:  
  Arrange: Instantiate AnonymousUser from Django auth, and create the object exposing get_icon.  
  Act: Call get_icon(anonymous_user).  
  Assert: Result should be the literal string "lock" with no exceptions raised.  
Validation: AnonymousUser surfaces in permission checks throughout Wagtail/Django; verifying support confirms the method is robust to common unauthenticated contexts.  

Scenario 3: Graceful handling of None as user  
Details:  
  TestName: test_get_icon_handles_none_user  
  Description: Check that passing None (instead of a user object) still returns "lock", demonstrating the method’s tolerance for missing or optional user information.  
Execution:  
  Arrange: Create owner object of get_icon; set user_reference = None.  
  Act: icon = get_icon(user_reference).  
  Assert: icon equals "lock"; no AttributeError or other exception is thrown.  
Validation: Defensive programming demands that utility functions cope with absent data; this test confirms business logic isn’t coupled to a fully-populated user instance.  

Scenario 4: Irrelevance of caller attributes (edge user object)  
Details:  
  TestName: test_get_icon_ignores_user_attributes  
  Description: Provide an object that is not a Django User at all—e.g., a wagtail.models.Page instance or a simple mock—proving the function does not inspect or depend on user attributes.  
Execution:  
  Arrange: Obtain any Page object (or mock) and the owning class instance.  
  Act: result = get_icon(page_instance)  
  Assert: result == "lock"  
Validation: Demonstrates that the helper truly ignores its argument’s shape, fulfilling the requirement that icon choice is unconditional and preventing accidental future coupling to user fields.  

Scenario 5: Return type integrity check  
Details:  
  TestName: test_get_icon_return_type_is_string  
  Description: Confirm that the function’s return value is of type str—not SafeString, Promise, or other lazy-translation proxy—ensuring predictable downstream handling in templates and serializers.  
Execution:  
  Arrange: Authenticated User (or any placeholder) plus get_icon provider.  
  Act: val = get_icon(user)  
  Assert: `isinstance(val, str)` is True and `val == "lock"`.  
Validation: Reinforces the contract that consumers receive a plain Python string, guarding against subtle bugs when concatenating or encoding values in HTML or APIs.  

Scenario 6: Idempotence across multiple invocations  
Details:  
  TestName: test_get_icon_is_idempotent  
  Description: Call get_icon repeatedly with the same or different user inputs and verify the output never changes, proving side-effect-free, stateless behavior.  
Execution:  
  Arrange: Prepare two diverse inputs (e.g., User and None) and the class instance.  
  Act: Collect outputs from several consecutive invocations.  
  Assert: All outputs are identical and equal to "lock".  
Validation: Affirms that the method is a pure function—critical for caching strategies and predictable view rendering within Wagtail admin.  

"""

# ********RoostGPT********
import pytest
from unittest import mock

# ---------------------------------------------------------------------------
# Soft-imports required by task description
# ---------------------------------------------------------------------------
try:
    from django.conf import settings  # noqa: F401
except ImportError:  # pragma: no cover
    settings = None  # type: ignore

try:
    from django.utils.html import format_html  # noqa: F401
except ImportError:  # pragma: no cover
    def format_html(s, *args, **kwargs):  # type: ignore
        return s.format(*args, **kwargs)

try:
    from django.utils.safestring import mark_safe  # noqa: F401
except ImportError:  # pragma: no cover
    def mark_safe(s):  # type: ignore
        return s

try:
    from django.utils.text import capfirst  # noqa: F401
except ImportError:  # pragma: no cover
    def capfirst(s):  # type: ignore
        return s.capitalize()

try:
    from django.utils.translation import gettext as _  # noqa: F401
except ImportError:  # pragma: no cover
    _ = lambda x: x  # type: ignore

try:
    from wagtail.admin.utils import get_latest_str, get_user_display_name  # noqa: F401
except ImportError:  # pragma: no cover
    def get_latest_str(*args, **kwargs):  # type: ignore
        return ""
    def get_user_display_name(*args, **kwargs):  # type: ignore
        return ""

try:
    from wagtail.utils.timestamps import render_timestamp  # noqa: F401
except ImportError:  # pragma: no cover
    def render_timestamp(*args, **kwargs):  # type: ignore
        return ""

try:
    from wagtail.models import Page  # noqa: F401
except ImportError:  # pragma: no cover
    class Page:  # type: ignore
        pass

# ---------------------------------------------------------------------------
# Import the system-under-test.  Skip whole test suite if Wagtail unavailable.
# ---------------------------------------------------------------------------
wagtail_locks = pytest.importorskip("wagtail.locks")  # noqa: F401
from wagtail.locks import BaseLock


class Test_BaseLockGetIcon:
    @pytest.mark.smoke
    @pytest.mark.valid
    @pytest.mark.positive
    def test_get_icon_returns_lock_for_authenticated_user(self):
        """
        Scenario 1:
        Confirm that an authenticated User receives the literal string 'lock'.
        """
        # Arrange
        try:
            from django.contrib.auth import get_user_model
            UserModel = get_user_model()
            user = UserModel(username="testuser")  # type: ignore
            user.is_active = True  # Ensure active
            # Django adds a dynamic property; guarantee truthiness for all cases.
            if not getattr(user, "is_authenticated", None):
                user.is_authenticated = True  # type: ignore
        except Exception:
            class DummyUser:
                is_active = True

                @property
                def is_authenticated(self):
                    return True
            user = DummyUser()
        lock_manager = BaseLock()

        # Act
        icon = lock_manager.get_icon(user)

        # Assert
        assert icon == "lock"

    @pytest.mark.regression
    @pytest.mark.valid
    @pytest.mark.positive
    def test_get_icon_returns_lock_for_anonymous_user(self):
        """
        Scenario 2:
        Ensure AnonymousUser still gets 'lock'.
        """
        # Arrange
        try:
            from django.contrib.auth.models import AnonymousUser
            user = AnonymousUser()  # type: ignore
        except Exception:
            class DummyAnonymous:
                is_active = False

                @property
                def is_authenticated(self):
                    return False
            user = DummyAnonymous()
        lock_manager = BaseLock()

        # Act
        icon = lock_manager.get_icon(user)

        # Assert
        assert icon == "lock"

    @pytest.mark.regression
    @pytest.mark.invalid
    @pytest.mark.negative
    def test_get_icon_handles_none_user(self):
        """
        Scenario 3:
        Passing None should still safely return 'lock'.
        """
        # Arrange
        user = None
        lock_manager = BaseLock()

        # Act
        icon = lock_manager.get_icon(user)

        # Assert
        assert icon == "lock"

    @pytest.mark.regression
    @pytest.mark.valid
    def test_get_icon_ignores_user_attributes(self):
        """
        Scenario 4:
        Supply a non-User object (e.g., Page) and confirm result is 'lock'.
        """
        # Arrange
        try:
            page_instance = Page()
        except Exception:
            page_instance = mock.Mock()
        lock_manager = BaseLock()

        # Act
        icon = lock_manager.get_icon(page_instance)

        # Assert
        assert icon == "lock"

    @pytest.mark.security
    @pytest.mark.valid
    def test_get_icon_return_type_is_string(self):
        """
        Scenario 5:
        Ensure the return value is a plain 'str' instance.
        """
        # Arrange
        lock_manager = BaseLock()

        # Act
        icon = lock_manager.get_icon(user=None)

        # Assert
        assert isinstance(icon, str)
        assert icon == "lock"

    @pytest.mark.performance
    @pytest.mark.valid
    def test_get_icon_is_idempotent(self):
        """
        Scenario 6:
        Multiple invocations with various inputs always yield the same result.
        """
        # Arrange
        lock_manager = BaseLock()
        try:
            from django.contrib.auth import get_user_model
            UserModel = get_user_model()
            user1 = UserModel(username="user1")  # type: ignore
        except Exception:
            user1 = object()

        inputs = [
            user1,
            None,
            "random string",  # type: ignore
            mock.Mock(),
        ]

        # Act
        results = [lock_manager.get_icon(u) for u in inputs] + [
            lock_manager.get_icon(user1)
        ]

        # Assert
        assert all(result == "lock" for result in results)
