# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=get_concrete_descendants_49c7c6d907
ROOST_METHOD_SIG_HASH=get_concrete_descendants_e29058780e


Scenario 1: Concrete root class without subclasses (inclusive=True)
Details:
  TestName: test_concrete_root_no_children_inclusive_true
  Description: Verifies that a concrete class with no subclasses is returned when inclusive is True.
Execution:
  Arrange: Create a dummy Django-style model class Root with _meta.abstract = False and no subclasses.
  Act: Call get_concrete_descendants(Root, inclusive=True) and convert the generator to a list.
  Assert: The list contains exactly [Root].
Validation:
  Ensures the base case works: the function must yield the class itself when it is concrete and inclusive=True.

Scenario 2: Concrete root class without subclasses (inclusive=False)
Details:
  TestName: test_concrete_root_no_children_inclusive_false
  Description: Confirms that the same concrete class is omitted when inclusive is False.
Execution:
  Arrange: Re-use the Root class from Scenario 1.
  Act: Call get_concrete_descendants(Root, inclusive=False) and list() the result.
  Assert: The resulting list is empty.
Validation:
  Demonstrates the impact of the inclusive flag on otherwise identical input.

Scenario 3: Abstract root with one concrete child
Details:
  TestName: test_abstract_root_single_concrete_child
  Description: Checks that an abstract parent is skipped while its concrete subclass is returned.
Execution:
  Arrange:
    • Create AbstractBase with _meta.abstract = True.  
    • Create ConcreteLeaf(AbstractBase) with _meta.abstract = False.
  Act: Call list(get_concrete_descendants(AbstractBase)).
  Assert: The list contains exactly [ConcreteLeaf]; AbstractBase is absent.
Validation:
  Confirms that the function honours the “non-abstract only” rule and ignores an abstract root.

Scenario 4: Mixed hierarchy containing abstract and concrete descendants
Details:
  TestName: test_mixed_hierarchy_filters_out_abstract_classes
  Description: Ensures that every level is walked recursively and that only non-abstract classes are yielded.
Execution:
  Arrange:
    • Build a tree:  
        RootConcrete (concrete)  
          ├─ ChildAbstract (abstract)  
          │    └─ GrandChildConcreteA (concrete)  
          └─ ChildConcreteB (concrete)
  Act: Call list(get_concrete_descendants(RootConcrete)).
  Assert: Returned list = [GrandChildConcreteA, ChildConcreteB, RootConcrete] (order discussed in Scenario 5).
Validation:
  Validates recursion depth, breadth, and correct abstract filtering in one compound case.

Scenario 5: Depth-first ordering with parent yielded last
Details:
  TestName: test_depth_first_yields_descendants_before_parent
  Description: The implementation visits subclasses first, so descendants must appear before their parent in the generator.
Execution:
  Arrange: Use the class tree from Scenario 4.
  Act: Generate a list and capture the order.
  Assert: Index of GrandChildConcreteA < index of RootConcrete AND  
          index of ChildConcreteB < index of RootConcrete.
Validation:
  Confirms the documented DFS behaviour, important when caller relies on order (e.g., migrations).

Scenario 6: Generator laziness and reusability
Details:
  TestName: test_returns_fresh_generator_each_call
  Description: Verifies two distinct aspects:  
    a) The function returns a generator (lazy evaluation).  
    b) Separate calls return independent generators.
Execution:
  Arrange: Use any simple concrete class SimpleModel.
  Act:
    • Call = get_concrete_descendants(SimpleModel); assert hasattr(Call, "__iter__") and not isinstance(Call, list).  
    • Consume the generator once; it yields SimpleModel.  
    • Call a second time; confirm the second generator again yields SimpleModel.
  Assert: Both generators succeed and do not interfere with each other.
Validation:
  Important for performance (laziness) and statelessness across invocations.

Scenario 7: No concrete classes anywhere in the tree
Details:
  TestName: test_all_abstract_returns_empty
  Description: If every class in the hierarchy is abstract, the result should be empty regardless of inclusive.
Execution:
  Arrange: Create AbstractA (abstract) → AbstractB(AbstractA) (abstract).
  Act: Obtain lists for inclusive=True and inclusive=False.
  Assert: Both lists are empty.
Validation:
  Guards against false positives where abstract classes might accidentally leak into the output.

Scenario 8: Inclusive=False with deep concrete descendants
Details:
  TestName: test_inclusive_false_still_recurses_and_returns_descendants
  Description: Checks that setting inclusive=False does not stop the traversal; only the root is excluded.
Execution:
  Arrange: Use the three-level chain AbstractBase (abstract) → MidConcrete (concrete) → LeafConcrete (concrete).
  Act: Call list(get_concrete_descendants(AbstractBase, inclusive=False)).
  Assert: The list contains [MidConcrete, LeafConcrete] in depth-first order.
Validation:
  Ensures the inclusive flag applies solely to the supplied root without altering recursion semantics.

"""

# ********RoostGPT********
import types
import sys
import inspect
import pytest

# ---------------------------------------------------------------------------
# Mandatory imports required by the instructions
# ---------------------------------------------------------------------------
try:
    from wagtail.models import Task  # noqa: F401  # pylint: disable=unused-import
except ModuleNotFoundError:
    # Provide a lightweight stand-in so the import always succeeds.
    wagtail_models_stub = types.ModuleType("wagtail.models")
    wagtail_models_stub.Task = type("Task", (), {})
    sys.modules["wagtail.models"] = wagtail_models_stub
    from wagtail.models import Task  # noqa: F401  # pylint: disable=wrong-import-position,unused-import

# ---------------------------------------------------------------------------
# Target under test
# ---------------------------------------------------------------------------
try:
    from wagtail.workflows import get_concrete_descendants
except ModuleNotFoundError:  # pragma: no cover
    # Abort the entire test module if the implementation is unavailable.
    pytest.skip(
        "wagtail.workflows.get_concrete_descendants is not importable – "
        "skipping all workflow descendant tests.",
        allow_module_level=True,
    )


class Test_WorkflowsGetConcreteDescendants:
    """Unit-tests for wagtail.workflows.get_concrete_descendants."""

    # ---------------------------------------------------------------------
    # Helper utilities
    # ---------------------------------------------------------------------
    @staticmethod
    def _make_meta(abstract: bool):
        """Return a minimal _meta replacement mirroring Django’s API."""
        return type("Meta", (), {"abstract": abstract})

    # ---------------------------------------------------------------------
    # Scenario 1
    # ---------------------------------------------------------------------
    @pytest.mark.smoke
    @pytest.mark.valid
    def test_concrete_root_no_children_inclusive_true(self):
        """A concrete class with no subclasses is yielded when inclusive=True."""
        class Root:  # noqa: D401
            _meta = self._make_meta(abstract=False)  # type: ignore[attr-defined]  # pylint: disable=no-member

        result = list(get_concrete_descendants(Root, inclusive=True))
        assert result == [Root]

    # ---------------------------------------------------------------------
    # Scenario 2
    # ---------------------------------------------------------------------
    @pytest.mark.negative
    @pytest.mark.valid
    def test_concrete_root_no_children_inclusive_false(self):
        """The concrete class is omitted when inclusive=False."""
        class Root:  # noqa: D401
            _meta = self._make_meta(abstract=False)  # type: ignore[attr-defined]  # pylint: disable=no-member

        result = list(get_concrete_descendants(Root, inclusive=False))
        assert result == []

    # ---------------------------------------------------------------------
    # Scenario 3
    # ---------------------------------------------------------------------
    @pytest.mark.regression
    def test_abstract_root_single_concrete_child(self):
        """Abstract parents are ignored; concrete children are returned."""
        class AbstractBase:  # noqa: D401
            _meta = self._make_meta(abstract=True)

        class ConcreteLeaf(AbstractBase):  # noqa: D401
            _meta = self._make_meta(abstract=False)

        result = list(get_concrete_descendants(AbstractBase))
        assert result == [ConcreteLeaf]

    # ---------------------------------------------------------------------
    # Scenario 4
    # ---------------------------------------------------------------------
    @pytest.mark.regression
    def test_mixed_hierarchy_filters_out_abstract_classes(self):
        """Mixed hierarchy returns only concrete models in DFS order."""
        class RootConcrete:  # noqa: D401
            _meta = self._make_meta(abstract=False)

        class ChildAbstract(RootConcrete):  # noqa: D401
            _meta = self._make_meta(abstract=True)

        class GrandChildConcreteA(ChildAbstract):  # noqa: D401
            _meta = self._make_meta(abstract=False)

        class ChildConcreteB(RootConcrete):  # noqa: D401
            _meta = self._make_meta(abstract=False)

        result = list(get_concrete_descendants(RootConcrete))
        expected = [GrandChildConcreteA, ChildConcreteB, RootConcrete]
        assert result == expected

    # ---------------------------------------------------------------------
    # Scenario 5
    # ---------------------------------------------------------------------
    @pytest.mark.performance
    def test_depth_first_yields_descendants_before_parent(self):
        """Every descendant must appear before its parent."""
        class RootConcrete:  # noqa: D401
            _meta = self._make_meta(abstract=False)

        class ChildAbstract(RootConcrete):  # noqa: D401
            _meta = self._make_meta(abstract=True)

        class GrandChildConcreteA(ChildAbstract):  # noqa: D401
            _meta = self._make_meta(abstract=False)

        class ChildConcreteB(RootConcrete):  # noqa: D401
            _meta = self._make_meta(abstract=False)

        result = list(get_concrete_descendants(RootConcrete))

        assert result.index(GrandChildConcreteA) < result.index(RootConcrete)
        assert result.index(ChildConcreteB) < result.index(RootConcrete)

    # ---------------------------------------------------------------------
    # Scenario 6
    # ---------------------------------------------------------------------
    @pytest.mark.security
    def test_returns_fresh_generator_each_call(self):
        """Confirm laziness and independence of successive invocations."""
        class SimpleModel:  # noqa: D401
            _meta = self._make_meta(abstract=False)

        first_call = get_concrete_descendants(SimpleModel)
        second_call = get_concrete_descendants(SimpleModel)

        # (a) Both calls return generators (not lists)
        assert inspect.isgenerator(first_call)
        assert inspect.isgenerator(second_call)

        # (b) Each generator can be consumed independently.
        assert list(first_call) == [SimpleModel]
        assert list(second_call) == [SimpleModel]

    # ---------------------------------------------------------------------
    # Scenario 7
    # ---------------------------------------------------------------------
    @pytest.mark.negative
    def test_all_abstract_returns_empty(self):
        """Purely abstract hierarchies should yield nothing."""
        class AbstractA:  # noqa: D401
            _meta = self._make_meta(abstract=True)

        class AbstractB(AbstractA):  # noqa: D401
            _meta = self._make_meta(abstract=True)

        inclusive_true_result = list(get_concrete_descendants(AbstractA, inclusive=True))
        inclusive_false_result = list(get_concrete_descendants(AbstractA, inclusive=False))

        assert inclusive_true_result == []
        assert inclusive_false_result == []

    # ---------------------------------------------------------------------
    # Scenario 8
    # ---------------------------------------------------------------------
    @pytest.mark.positive
    def test_inclusive_false_still_recurses_and_returns_descendants(self):
        """Setting inclusive=False only affects the supplied root."""
        class AbstractBase:  # noqa: D401
            _meta = self._make_meta(abstract=True)

        class MidConcrete(AbstractBase):  # noqa: D401
            _meta = self._make_meta(abstract=False)

        class LeafConcrete(MidConcrete):  # noqa: D401
            _meta = self._make_meta(abstract=False)

        result = list(get_concrete_descendants(AbstractBase, inclusive=False))

        # Expected content
        assert result == [LeafConcrete, MidConcrete]

        # Order check: descendant (Leaf) appears before parent (Mid)
        assert result.index(LeafConcrete) < result.index(MidConcrete)

