# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=WorkflowLock.get_message_98bcfd9a25
ROOST_METHOD_SIG_HASH=WorkflowLock.get_message_38d14a7494


 
Scenario 1: Message is omitted when the lock does not apply to the requesting user
Details:
  TestName: test_get_message_returns_none_for_irrelevant_user
  Description: Verifies that get_message returns no message when self.for_user(user) evaluates to False, confirming that no information is leaked to users who should not see workflow details.
Execution:
  Arrange: 
    • Create a dummy instance of the class containing get_message.  
    • Stub self.for_user to return False for the supplied user.  
    • Provide any minimal attribute values the method may reference (model_name, object, task), though they should not be used because for_user is False.
  Act: Invoke get_message with the user object.
  Assert: Assert that the returned value is None (or other falsy value) and that no exception is raised.
Validation: 
  The test ensures compliance with the security/business rule that only users affected by the lock receive workflow status information. 

"""

# ********RoostGPT********
import types
import pytest

# Required imports as per instructions
try:
    from django.conf import settings  # noqa: F401
    from django.utils.html import format_html  # noqa: F401
    from django.utils.safestring import mark_safe  # noqa: F401
    from django.utils.text import capfirst  # noqa: F401
    from django.utils.translation import gettext_lazy as _  # noqa: F401
    from wagtail.admin.utils import get_latest_str, get_user_display_name  # noqa: F401
    from wagtail.utils.timestamps import render_timestamp  # noqa: F401
    from wagtail.models import Page  # noqa: F401
except ModuleNotFoundError:
    # Provide light-weight fall-backs so the tests can run without Django/Wagtail.
    import sys

    fallback_module = types.ModuleType("fallback")
    sys.modules["django"] = fallback_module
    sys.modules["django.conf"] = types.ModuleType("django.conf")
    sys.modules["django.conf"].settings = types.SimpleNamespace()
    sys.modules["django.utils"] = types.ModuleType("django.utils")
    sys.modules["django.utils.html"] = types.ModuleType("django.utils.html")
    sys.modules["django.utils.html"].format_html = lambda *args, **kwargs: ""
    sys.modules["django.utils.safestring"] = types.ModuleType("django.utils.safestring")
    sys.modules["django.utils.safestring"].mark_safe = lambda x: x
    sys.modules["django.utils.text"] = types.ModuleType("django.utils.text")
    sys.modules["django.utils.text"].capfirst = lambda s: s[:1].upper() + s[1:]
    sys.modules["django.utils.translation"] = types.ModuleType("django.utils.translation")
    sys.modules["django.utils.translation"].gettext_lazy = lambda s: s
    sys.modules["wagtail"] = types.ModuleType("wagtail")
    sys.modules["wagtail.admin"] = types.ModuleType("wagtail.admin")
    sys.modules["wagtail.admin.utils"] = types.ModuleType("wagtail.admin.utils")
    sys.modules["wagtail.admin.utils"].get_latest_str = lambda *args, **kwargs: ""
    sys.modules["wagtail.admin.utils"].get_user_display_name = lambda *args, **kwargs: ""
    sys.modules["wagtail.utils"] = types.ModuleType("wagtail.utils")
    sys.modules["wagtail.utils.timestamps"] = types.ModuleType("wagtail.utils.timestamps")
    sys.modules["wagtail.utils.timestamps"].render_timestamp = lambda *args, **kwargs: ""
    sys.modules["wagtail.models"] = types.ModuleType("wagtail.models")
    sys.modules["wagtail.models"].Page = object
    # Re-import the fall-backed symbols for local use
    from django.conf import settings  # noqa: F401
    from django.utils.html import format_html  # noqa: F401
    from django.utils.safestring import mark_safe  # noqa: F401
    from django.utils.text import capfirst  # noqa: F401
    from django.utils.translation import gettext_lazy as _  # noqa: F401
    from wagtail.admin.utils import get_latest_str, get_user_display_name  # noqa: F401
    from wagtail.utils.timestamps import render_timestamp  # noqa: F401
    from wagtail.models import Page  # noqa: F401

# Import class under test
from wagtail.locks import WorkflowLock


@pytest.mark.security
class Test_WorkflowLockGetMessage:
    """
    Tests for WorkflowLock.get_message method.
    """

    def test_get_message_returns_none_for_irrelevant_user(self):
        """
        Scenario 1:
        Verifies that get_message returns None when self.for_user(user) is False,
        ensuring that users who are not affected by the lock do not receive any
        workflow status information.
        """
        # Arrange
        dummy_user = object()  # Stub user object

        # Create a lock instance without calling its __init__ (if it expects args)
        lock_instance = WorkflowLock.__new__(WorkflowLock)

        # Monkey-patch the for_user method to force a False return value
        def always_false_for_user(self, user):  # noqa: D401
            return False

        lock_instance.for_user = types.MethodType(always_false_for_user, lock_instance)

        # Act
        result = lock_instance.get_message(dummy_user)

        # Assert
        assert result is None, "Expected get_message to return None for irrelevant users."
