# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=ScheduledForPublishLock.get_locked_by_d06e2d4ccf
ROOST_METHOD_SIG_HASH=ScheduledForPublishLock.get_locked_by_41b18b2414


Scenario 1: Constant message returned for a normal user and page
Details:
  TestName: test_locked_by_returns_constant_message
  Description: Verify that calling get_locked_by on a standard Page instance with a regular authenticated User returns the exact, untranslated message “Locked by schedule”.
Execution:
  Arrange: Create a Page-like dummy object (or use wagtail Page factory) and a standard django.auth User.
  Act: Invoke page.get_locked_by(user).
  Assert: The result equals "Locked by schedule" (string comparison).
Validation:
  Confirms that the business rule “always display the constant lock notification” is honored irrespective of typical caller context.

Scenario 2: Function is agnostic to the caller object
Details:
  TestName: test_locked_by_ignores_self_content
  Description: Demonstrate that the value of self has no influence on the return value by passing an arbitrary stub object instead of a real Page.
Execution:
  Arrange: Define a lightweight dummy class with get_locked_by bound as an instance method.
  Act: Call dummy_instance.get_locked_by(user) where user is any valid User.
  Assert: Result is "Locked by schedule".
Validation:
  Shows that the method’s implementation is self-independent, meeting the requirement that it always yield the constant message.

Scenario 3: Anonymous or None user produces the same output
Details:
  TestName: test_locked_by_with_anonymous_user
  Description: Ensure the lock message does not depend on user identity by passing django.contrib.auth.models.AnonymousUser or even None.
Execution:
  Arrange: Build a valid Page object (or stub) and obtain AnonymousUser() or set user = None.
  Act: Call page.get_locked_by(user).
  Assert: Result equals "Locked by schedule".
Validation:
  Strengthens confidence that the function’s logic is user-agnostic, complying with the specification that the text is unconditional.

Scenario 4: Execution inside a language override without translation file
Details:
  TestName: test_locked_by_language_override_no_translation
  Description: Within Django’s translation.override context set to a language code that lacks a message catalog (e.g., "xx"), ensure the fallback English string is delivered.
Execution:
  Arrange: Enter translation.override("xx") context; instantiate Page and User.
  Act: Call page.get_locked_by(user).
  Assert: Result is the English literal "Locked by schedule".
Validation:
  Verifies graceful degradation when no locale resource is present, guarding against missing-translation regressions.

Scenario 5: Execution with mocked translation returning a localized string
Details:
  TestName: test_locked_by_uses_gettext
  Description: Patch or monkeypatch the translation function _ to return a sentinel value (e.g., "Bloqueado por horario") and assert that get_locked_by propagates it unchanged.
Execution:
  Arrange: Monkeypatch module_scope._ to return "Bloqueado por horario"; create dummy page and user.
  Act: Invoke page.get_locked_by(user).
  Assert: Result equals the patched localized string.
Validation:
  Confirms the method delegates to Django’s i18n layer rather than hard-coding text, satisfying internationalization requirements.

Scenario 6: Return value is a plain string, not marked as safe HTML
Details:
  TestName: test_locked_by_returns_plain_string_not_safe
  Description: Make sure the result is not an instance of django.utils.safestring.SafeString, preventing accidental HTML auto-escape bypass.
Execution:
  Arrange: Instantiate Page and User.
  Act: res = page.get_locked_by(user)
  Assert: isinstance(res, str) is True AND not hasattr(res, "__html__")
Validation:
  Ensures that downstream templates remain protected from XSS because the function does not mark its output safe.

Scenario 7: Stress test with unusual self and user inputs
Details:
  TestName: test_locked_by_with_unexpected_inputs
  Description: Call get_locked_by with self=None or user objects missing typical attributes to confirm the method still returns the constant message without raising.
Execution:
  Arrange: self = None; user = object()  # generic Python object
  Act: get_locked_by(self, user)  # using the raw function rather than bound method
  Assert: Output equals "Locked by schedule".
Validation:
  Guards against accidental refactors that might start referencing self or user properties, ensuring robustness under edge conditions.

"""

# ********RoostGPT********
import importlib
from types import SimpleNamespace

import pytest
from django.utils import translation
from django.utils.safestring import SafeString
from wagtail.locks import ScheduledForPublishLock


class Test_ScheduledForPublishLockGetLockedBy:
    # ------------------------------------------------------------------ #
    # Helper(s)
    # ------------------------------------------------------------------ #
    @staticmethod
    def _build_user(username="tester"):
        """
        Attempt to return a real django User instance without touching
        the database.  Falls back to a lightweight stub when Django’s
        auth user model is unavailable (e.g. swapped or import failure).
        """
        try:
            from django.contrib.auth import get_user_model

            UserModel = get_user_model()
            return UserModel(username=username)
        except Exception:  # pragma: no cover – fallback for non-Django envs
            return SimpleNamespace(username=username)

    # ------------------------------------------------------------------ #
    # Scenario 1
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    @pytest.mark.positive
    @pytest.mark.smoke
    def test_locked_by_returns_constant_message(self):
        """Verify constant English message for a normal user and page."""
        lock = ScheduledForPublishLock()
        user = self._build_user()
        assert lock.get_locked_by(user) == "Locked by schedule"

    # ------------------------------------------------------------------ #
    # Scenario 2
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    @pytest.mark.regression
    def test_locked_by_ignores_self_content(self):
        """
        Demonstrate that the return value does not depend on *self*
        by binding the function to an unrelated dummy object.
        """

        class Dummy:
            # Bind the original implementation directly
            get_locked_by = ScheduledForPublishLock.get_locked_by

        dummy_instance = Dummy()
        user = self._build_user(username="irrelevant")
        assert dummy_instance.get_locked_by(user) == "Locked by schedule"

    # ------------------------------------------------------------------ #
    # Scenario 3
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    @pytest.mark.negative
    def test_locked_by_with_anonymous_user(self):
        """Ensure AnonymousUser or None produces identical output."""
        lock = ScheduledForPublishLock()

        # Anonymous user branch
        try:
            from django.contrib.auth.models import AnonymousUser

            anon_user = AnonymousUser()
        except Exception:  # pragma: no cover
            anon_user = None
        assert lock.get_locked_by(anon_user) == "Locked by schedule"

        # Explicit None branch
        assert lock.get_locked_by(None) == "Locked by schedule"

    # ------------------------------------------------------------------ #
    # Scenario 4
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    @pytest.mark.security
    def test_locked_by_language_override_no_translation(self):
        """
        Make sure that when the active language lacks a translation file,
        the English fallback string is returned.
        """
        lock = ScheduledForPublishLock()
        user = self._build_user()

        with translation.override("xx"):  # unlikely dummy locale
            assert lock.get_locked_by(user) == "Locked by schedule"

    # ------------------------------------------------------------------ #
    # Scenario 5
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    @pytest.mark.i18n
    def test_locked_by_uses_gettext(self, monkeypatch):
        """
        Patch the gettext wrapper (_) to return a sentinel value and
        assert that get_locked_by surfaces it unchanged.
        """
        module = importlib.import_module("wagtail.locks")
        sentinel_value = "Bloqueado por horario"

        # NOTE: raising=False so the attribute is created if missing.
        monkeypatch.setattr(module, "_", lambda msg: sentinel_value, raising=False)

        lock = ScheduledForPublishLock()
        user = self._build_user()
        assert lock.get_locked_by(user) == sentinel_value

    # ------------------------------------------------------------------ #
    # Scenario 6
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    @pytest.mark.security
    def test_locked_by_returns_plain_string_not_safe(self):
        """
        Confirm that the return value is a regular str and *not* a
        django SafeString (prevents implicit HTML safety).
        """
        lock = ScheduledForPublishLock()
        user = self._build_user()

        result = lock.get_locked_by(user)
        assert isinstance(result, str)
        assert not isinstance(result, SafeString)
        # A SafeString usually implements __html__; ensure it’s absent.
        assert not hasattr(result, "__html__")

    # ------------------------------------------------------------------ #
    # Scenario 7
    # ------------------------------------------------------------------ #
    @pytest.mark.valid
    @pytest.mark.regression
    def test_locked_by_with_unexpected_inputs(self):
        """
        Call get_locked_by with self=None and a generic object() user
        to ensure robustness under edge conditions.
        """
        result = ScheduledForPublishLock.get_locked_by(None, object())
        assert result == "Locked by schedule"
