# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=WorkflowLock.get_icon_c31f4d4cd4
ROOST_METHOD_SIG_HASH=WorkflowLock.get_icon_3358306648


Scenario 1: Return value when locking is allowed
Details:
  TestName: test_get_icon_returns_lock_open_when_can_lock_true
  Description: Verify that the method immediately returns the literal string "lock-open" whenever the caller supplies can_lock=True, regardless of the user object’s state.
Execution:
  Arrange: Instantiate (or monkey-patch) a concrete subclass that implements get_icon; prepare a valid user instance or mock.
  Act: Call instance.get_icon(user=some_user, can_lock=True).
  Assert: The returned value equals the exact string "lock-open".
Validation:
  This confirms the primary branch of the business rule: “If the page can be locked, use the ‘lock-open’ icon.”  It ensures no other logic or superclass call interferes with the mandated icon.

Scenario 2: Superclass delegation when locking is not allowed
Details:
  TestName: test_get_icon_delegates_to_super_when_can_lock_false
  Description: Ensure that, if can_lock is False, the method defers to the parent class’s implementation and returns exactly what that parent returns.
Execution:
  Arrange: Create a subclass whose super().get_icon is monkey-patched to return a sentinel string such as "parent-icon".  Supply any user object.
  Act: Call instance.get_icon(user=some_user, can_lock=False).
  Assert: The return value is the sentinel "parent-icon".
Validation:
  Demonstrates correct delegation flow, protecting against regressions where the method might accidentally bypass its parent or alter the parent’s value.

Scenario 3: Default parameter path without specifying can_lock
Details:
  TestName: test_get_icon_uses_default_can_lock_value
  Description: Confirm that omitting the can_lock argument (thus relying on its default of False) behaves identically to explicitly passing can_lock=False.
Execution:
  Arrange: Monkey-patch super().get_icon to return "parent-icon-default".
  Act: Call instance.get_icon(user=some_user)  # no can_lock argument
  Assert: The method returns "parent-icon-default".
Validation:
  Guards against signature or default-value changes that might silently alter downstream behaviour.

Scenario 4: Truthy non-boolean values still activate lock icon
Details:
  TestName: test_get_icon_accepts_truthy_can_lock_values
  Description: Validate that any truthy value (e.g., 1, "yes") for can_lock triggers the “lock-open” branch, reflecting Python’s truthiness semantics in business logic.
Execution:
  Arrange: Prepare instance and user.  No need to patch super.
  Act: Invoke instance.get_icon(user=some_user, can_lock=1).
  Assert: Returned value equals "lock-open".
Validation:
  Protects against later refactors that might do strict identity checks (can_lock is True) and break current truthiness-based contract.

Scenario 5: Superclass method is not called when can_lock is truthy
Details:
  TestName: test_super_not_called_when_can_lock_true
  Description: Guarantee performance and side-effect expectations by asserting that the parent method is never executed when can_lock is truthy.
Execution:
  Arrange: Patch the parent’s get_icon to a stub that raises an AssertionError if invoked.
  Act: Call instance.get_icon(user=some_user, can_lock=True).
  Assert: No AssertionError is raised; return value is "lock-open".
Validation:
  Confirms that the shortcut branch short-circuits all superclass work, preventing unnecessary database queries or logging in production.

Scenario 6: Superclass receives the same user object
Details:
  TestName: test_user_passed_unchanged_to_super
  Description: Ascertain that, in the delegation path, the very same user object is forwarded to the parent without modification.
Execution:
  Arrange: Patch super().get_icon to capture its positional argument and return a constant marker.
  Act: Call instance.get_icon(user=original_user, can_lock=False).
  Assert: Captured user is original_user (identity comparison) and return value is the constant marker.
Validation:
  Safeguards against inadvertent mutation or substitution of the user parameter, which could affect permission logic higher up the stack.

Scenario 7: Return type consistency
Details:
  TestName: test_get_icon_always_returns_string
  Description: Confirm that, for both branches, the function consistently yields a string object, fulfilling template expectations that an icon identifier is a textual value.
Execution:
  Arrange: For the can_lock=True branch, simply call the method; for the can_lock=False branch, patch super().get_icon to return "parent-icon".
  Act: Execute both calls.
  Assert: In each case, assert isinstance(result, str) and check value equality where applicable.
Validation:
  Ensures compatibility with any rendering code that directly interpolates the icon name into HTML; catching regressions where a non-string type might be returned.

"""

# ********RoostGPT********
import types
import sys
import pytest

# ---------------------------------------------------------------------------
# Third-party imports that the exercise requires us to include.
# Where an import is unavailable (e.g. when Django/Wagtail isn’t installed in
# the execution environment), we create lightweight dummies so that the test
# suite can still be collected and run.  This approach obeys the instruction
# not to redeclare the target *WorkflowLock* implementation itself.
# ---------------------------------------------------------------------------
OPTIONAL_IMPORTS = (
    ("django.conf", "settings", types.SimpleNamespace()),
    ("django.utils.html", "format_html", lambda *a, **k: "".join(map(str, a))),
    ("django.utils.safestring", "mark_safe", lambda x: x),
    ("django.utils.text", "capfirst", lambda s: s.capitalize() if hasattr(s, "capitalize") else s),
    ("wagtail.admin.utils", "get_latest_str", lambda *a, **k: ""),
    ("wagtail.admin.utils", "get_user_display_name", lambda *a, **k: ""),
    ("wagtail.utils.timestamps", "render_timestamp", lambda *a, **k: ""),
    ("wagtail.models", "Page", object),
)

for module_path, attr_name, dummy in OPTIONAL_IMPORTS:
    try:
        module = __import__(module_path, fromlist=[attr_name])
        globals()[attr_name] = getattr(module, attr_name)
    except ModuleNotFoundError:
        # Create a stub module so that `import x.y` in other
        # test files (if any) continues to work.
        parent_name, _, child_name = module_path.rpartition(".")
        parent_module = sys.modules.setdefault(parent_name, types.ModuleType(parent_name))
        stub_module = types.ModuleType(module_path)
        setattr(stub_module, attr_name, dummy)
        sys.modules[module_path] = stub_module
        setattr(parent_module, child_name, stub_module)
        globals()[attr_name] = dummy

# Translation helper (_)
try:
    from django.utils.translation import gettext as _
except ModuleNotFoundError:
    _ = lambda x: x  # type: ignore

# ---------------------------------------------------------------------------
# Main subject under test: WorkflowLock
# ---------------------------------------------------------------------------
try:
    from wagtail.locks import WorkflowLock
except ModuleNotFoundError:  # pragma: no cover
    pytest.skip("wagtail.locks.WorkflowLock not available – skipping tests.", allow_module_level=True)


class Test_WorkflowLockGetIcon:
    """Unit-tests for WorkflowLock.get_icon()."""

    # ---------------------------------------------------------------------
    # Helpers
    # ---------------------------------------------------------------------
    @staticmethod
    def _get_parent_get_icon():
        """
        Return (parent_class, original_function) for WorkflowLock.get_icon’s
        immediate parent implementation.
        """
        for base in WorkflowLock.__mro__[1:]:
            if hasattr(base, "get_icon"):
                return base, getattr(base, "get_icon")
        raise RuntimeError("No parent get_icon method found in WorkflowLock MRO")

    # ------------------------------------------------------------------ #
    #  Scenario 1
    # ------------------------------------------------------------------ #
    @pytest.mark.positive
    @pytest.mark.smoke
    def test_get_icon_returns_lock_open_when_can_lock_true(self):
        """Verify explicit can_lock=True always yields 'lock-open'."""
        user = object()  # dummy user instance
        lock = WorkflowLock()
        assert lock.get_icon(user=user, can_lock=True) == "lock-open"

    # ------------------------------------------------------------------ #
    #  Scenario 2
    # ------------------------------------------------------------------ #
    @pytest.mark.regression
    @pytest.mark.positive
    def test_get_icon_delegates_to_super_when_can_lock_false(self, monkeypatch):
        """When locking is not allowed, WorkflowLock must defer to parent."""
        parent_cls, original_get_icon = self._get_parent_get_icon()

        sentinel = "parent-icon"

        def fake_parent_get_icon(self, user):
            return sentinel

        monkeypatch.setattr(parent_cls, "get_icon", fake_parent_get_icon, raising=True)

        user = object()
        lock = WorkflowLock()
        try:
            assert lock.get_icon(user=user, can_lock=False) == sentinel
        finally:
            # Restore original to avoid cross-test contamination
            monkeypatch.setattr(parent_cls, "get_icon", original_get_icon, raising=True)

    # ------------------------------------------------------------------ #
    #  Scenario 3
    # ------------------------------------------------------------------ #
    @pytest.mark.regression
    @pytest.mark.positive
    def test_get_icon_uses_default_can_lock_value(self, monkeypatch):
        """Omitting can_lock must behave like can_lock=False."""
        parent_cls, original_get_icon = self._get_parent_get_icon()
        sentinel = "parent-icon-default"

        monkeypatch.setattr(parent_cls, "get_icon", lambda self, user: sentinel, raising=True)

        user = object()
        lock = WorkflowLock()
        try:
            assert lock.get_icon(user=user) == sentinel  # default can_lock=False
        finally:
            monkeypatch.setattr(parent_cls, "get_icon", original_get_icon, raising=True)

    # ------------------------------------------------------------------ #
    #  Scenario 4
    # ------------------------------------------------------------------ #
    @pytest.mark.regression
    @pytest.mark.positive
    def test_get_icon_accepts_truthy_can_lock_values(self):
        """Any truthy value for can_lock should activate 'lock-open' branch."""
        lock = WorkflowLock()
        user = object()

        # Using `1` as a generic truthy value
        assert lock.get_icon(user=user, can_lock=1) == "lock-open"

    # ------------------------------------------------------------------ #
    #  Scenario 5
    # ------------------------------------------------------------------ #
    @pytest.mark.regression
    @pytest.mark.negative
    def test_super_not_called_when_can_lock_true(self, monkeypatch):
        """
        Ensure the parent implementation is NOT executed when can_lock is truthy.
        """

        parent_cls, original_get_icon = self._get_parent_get_icon()

        def explode(*args, **kwargs):  # pragma: no cover
            raise AssertionError("Parent get_icon should not have been called!")

        monkeypatch.setattr(parent_cls, "get_icon", explode, raising=True)

        lock = WorkflowLock()
        user = object()
        try:
            assert lock.get_icon(user=user, can_lock=True) == "lock-open"
        finally:
            monkeypatch.setattr(parent_cls, "get_icon", original_get_icon, raising=True)

    # ------------------------------------------------------------------ #
    #  Scenario 6
    # ------------------------------------------------------------------ #
    @pytest.mark.regression
    @pytest.mark.positive
    def test_user_passed_unchanged_to_super(self, monkeypatch):
        """Verify that the exact user object is forwarded to the parent."""
        parent_cls, original_get_icon = self._get_parent_get_icon()
        captured = {}

        def capture_get_icon(self, user):
            captured["user"] = user
            return "capture-icon"

        monkeypatch.setattr(parent_cls, "get_icon", capture_get_icon, raising=True)

        original_user = object()
        lock = WorkflowLock()
        try:
            result = lock.get_icon(user=original_user, can_lock=False)
            assert result == "capture-icon"
            assert captured["user"] is original_user  # identity check
        finally:
            monkeypatch.setattr(parent_cls, "get_icon", original_get_icon, raising=True)

    # ------------------------------------------------------------------ #
    #  Scenario 7
    # ------------------------------------------------------------------ #
    @pytest.mark.regression
    @pytest.mark.positive
    def test_get_icon_always_returns_string(self, monkeypatch):
        """Both branches must consistently return str instances."""
        lock = WorkflowLock()
        user = object()

        # Branch 1: can_lock=True
        result_true = lock.get_icon(user=user, can_lock=True)
        assert isinstance(result_true, str)
        assert result_true == "lock-open"

        # Branch 2: can_lock=False with parent patched
        parent_cls, original_get_icon = self._get_parent_get_icon()
        monkeypatch.setattr(parent_cls, "get_icon", lambda self, user: "parent-icon", raising=True)
        try:
            result_false = lock.get_icon(user=user, can_lock=False)
            assert isinstance(result_false, str)
            assert result_false == "parent-icon"
        finally:
            monkeypatch.setattr(parent_cls, "get_icon", original_get_icon, raising=True)
