# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=BaseLock.get_icon_ee22150f0a
ROOST_METHOD_SIG_HASH=BaseLock.get_icon_1d49855096


Scenario 1: Constant icon for a standard authenticated user  
Details:  
  TestName: test_get_icon_returns_lock_for_authenticated_user  
  Description: Verify that an ordinary, authenticated Django User instance receives the hard-coded string "lock" from get_icon.  
Execution:  
  Arrange: Create or retrieve a typical django.contrib.auth.models.User marked as is_active=True and is_authenticated=True. Instantiate (or otherwise obtain) the class that owns get_icon.  
  Act: Call instance.get_icon(user).  
  Assert: Confirm the returned value is exactly the string "lock".  
Validation: This test guarantees that the primary business rule—always delivering the “lock” icon—holds true for the most common caller type (a logged-in user), ensuring UI consistency for every authenticated request.  

Scenario 2: Constant icon for an AnonymousUser  
Details:  
  TestName: test_get_icon_returns_lock_for_anonymous_user  
  Description: Ensure the function behaves identically when the caller supplies django.contrib.auth.models.AnonymousUser, which mimics an unauthenticated visitor.  
Execution:  
  Arrange: Instantiate AnonymousUser from Django auth, and create the object exposing get_icon.  
  Act: Call get_icon(anonymous_user).  
  Assert: Result should be the literal string "lock" with no exceptions raised.  
Validation: AnonymousUser surfaces in permission checks throughout Wagtail/Django; verifying support confirms the method is robust to common unauthenticated contexts.  

Scenario 3: Graceful handling of None as user  
Details:  
  TestName: test_get_icon_handles_none_user  
  Description: Check that passing None (instead of a user object) still returns "lock", demonstrating the method’s tolerance for missing or optional user information.  
Execution:  
  Arrange: Create owner object of get_icon; set user_reference = None.  
  Act: icon = get_icon(user_reference).  
  Assert: icon equals "lock"; no AttributeError or other exception is thrown.  
Validation: Defensive programming demands that utility functions cope with absent data; this test confirms business logic isn’t coupled to a fully-populated user instance.  

Scenario 4: Irrelevance of caller attributes (edge user object)  
Details:  
  TestName: test_get_icon_ignores_user_attributes  
  Description: Provide an object that is not a Django User at all—e.g., a wagtail.models.Page instance or a simple mock—proving the function does not inspect or depend on user attributes.  
Execution:  
  Arrange: Obtain any Page object (or mock) and the owning class instance.  
  Act: result = get_icon(page_instance)  
  Assert: result == "lock"  
Validation: Demonstrates that the helper truly ignores its argument’s shape, fulfilling the requirement that icon choice is unconditional and preventing accidental future coupling to user fields.  

Scenario 5: Return type integrity check  
Details:  
  TestName: test_get_icon_return_type_is_string  
  Description: Confirm that the function’s return value is of type str—not SafeString, Promise, or other lazy-translation proxy—ensuring predictable downstream handling in templates and serializers.  
Execution:  
  Arrange: Authenticated User (or any placeholder) plus get_icon provider.  
  Act: val = get_icon(user)  
  Assert: `isinstance(val, str)` is True and `val == "lock"`.  
Validation: Reinforces the contract that consumers receive a plain Python string, guarding against subtle bugs when concatenating or encoding values in HTML or APIs.  

Scenario 6: Idempotence across multiple invocations  
Details:  
  TestName: test_get_icon_is_idempotent  
  Description: Call get_icon repeatedly with the same or different user inputs and verify the output never changes, proving side-effect-free, stateless behavior.  
Execution:  
  Arrange: Prepare two diverse inputs (e.g., User and None) and the class instance.  
  Act: Collect outputs from several consecutive invocations.  
  Assert: All outputs are identical and equal to "lock".  
Validation: Affirms that the method is a pure function—critical for caching strategies and predictable view rendering within Wagtail admin.  

"""

# ********RoostGPT********
"""
Unit tests for BaseLock.get_icon
"""
import sys
import types
import pytest

# ------------------------------------------------------------------------------
# Third-party imports required by the exercise (some may not be used directly in
# the tests).  Where the dependency is unavailable we create very lightweight
# dummy modules/objects so that the test-suite can still be collected/executed
# in environments that lack Django/Wagtail.
# ------------------------------------------------------------------------------

# Helper to lazily create placeholder modules
def _install_stub(module_path: str) -> types.ModuleType:
    parts = module_path.split(".")
    current_path = ""
    parent_module = None
    for part in parts:
        current_path = f"{current_path}.{part}" if current_path else part
        if current_path not in sys.modules:
            sys.modules[current_path] = types.ModuleType(current_path)
        parent_module = sys.modules[current_path]
    return parent_module


required_modules = [
    "django",
    "django.conf",
    "django.utils",
    "django.utils.html",
    "django.utils.safestring",
    "django.utils.text",
    "django.utils.translation",
    "wagtail",
    "wagtail.admin",
    "wagtail.admin.utils",
    "wagtail.utils",
    "wagtail.utils.timestamps",
    "wagtail.models",
]

for mod in required_modules:
    _install_stub(mod)

# Attempt real imports; fall back to simple stubs if they still do not exist.
try:
    from django.conf import settings  # type: ignore
except (ModuleNotFoundError, ImportError):
    settings = types.SimpleNamespace()

try:
    from django.utils.html import format_html  # type: ignore
except (ModuleNotFoundError, ImportError):
    def format_html(fmt: str, *args, **kwargs):  # noqa: D401
        return fmt.format(*args, **kwargs)

try:
    from django.utils.safestring import mark_safe  # type: ignore
except (ModuleNotFoundError, ImportError):
    def mark_safe(value):  # noqa: D401
        return value

try:
    from django.utils.text import capfirst  # type: ignore
except (ModuleNotFoundError, ImportError):
    def capfirst(value):  # noqa: D401
        return value.capitalize() if isinstance(value, str) else value

# Original requirement asked for this peculiar import path; we comply with the
# spirit (translation alias) while keeping runnable code.
try:
    from django.utils.translation import gettext as _  # type: ignore
except (ModuleNotFoundError, ImportError):
    _ = lambda s: s  # noqa: E731

try:
    from wagtail.admin.utils import get_latest_str, get_user_display_name  # type: ignore
except (ModuleNotFoundError, ImportError):
    def get_latest_str():  # noqa: D401
        return "dummy"
    def get_user_display_name(user):  # noqa: D401
        return str(user)

try:
    from wagtail.utils.timestamps import render_timestamp  # type: ignore
except (ModuleNotFoundError, ImportError):
    def render_timestamp(ts):  # noqa: D401
        return str(ts)

try:
    from wagtail.models import Page  # type: ignore
except (ModuleNotFoundError, ImportError):
    class Page:  # noqa: D401
        pass

# ------------------------------------------------------------------------------
# Imports for the code under test
# ------------------------------------------------------------------------------
from wagtail.locks import BaseLock

# Django authentication helpers (optional if Django is unavailable)
try:
    from django.contrib.auth import get_user_model  # type: ignore
    from django.contrib.auth.models import AnonymousUser  # type: ignore
except (ModuleNotFoundError, ImportError):
    # Minimal stand-ins for tests when Django is absent
    class AnonymousUser:  # noqa: D401
        is_authenticated = False
        is_active = False

    def get_user_model():  # noqa: D401
        # Dynamically create a super-simple User class
        class _DummyUser:
            def __init__(self, username="", is_active=True):
                self.username = username
                self.is_active = is_active

            @property
            def is_authenticated(self):
                return True
        return _DummyUser


# ==============================================================================
# Test suite
# ==============================================================================
class Test_BaseLockGetIcon:
    """Tests for BaseLock.get_icon"""

    @pytest.mark.smoke
    @pytest.mark.positive
    def test_get_icon_returns_lock_for_authenticated_user(self):
        """
        Verify that an ordinary, authenticated user receives the hard-coded
        string "lock" from get_icon.
        """
        User = get_user_model()
        user = User(username="john_doe", is_active=True)  # no DB hit required
        assert user.is_authenticated, "User should be treated as authenticated"

        lock = BaseLock()
        icon = lock.get_icon(user)

        assert icon == "lock", "Authenticated users must always receive 'lock'"

    @pytest.mark.regression
    @pytest.mark.positive
    def test_get_icon_returns_lock_for_anonymous_user(self):
        """
        Ensure AnonymousUser receives the same constant icon.
        """
        anonymous_user = AnonymousUser()

        lock = BaseLock()
        icon = lock.get_icon(anonymous_user)

        assert icon == "lock", "AnonymousUser should also receive 'lock'"

    @pytest.mark.regression
    @pytest.mark.negative
    def test_get_icon_handles_none_user(self):
        """
        Passing None should be handled gracefully and return 'lock'.
        """
        lock = BaseLock()
        icon = lock.get_icon(None)

        assert icon == "lock", "None input should still yield 'lock'"

    @pytest.mark.regression
    @pytest.mark.positive
    def test_get_icon_ignores_user_attributes(self, mocker):
        """
        Supply a non-User object to confirm the function does not depend on
        specific attributes.
        """
        random_object = mocker.MagicMock(spec=Page)  # could be any object

        lock = BaseLock()
        icon = lock.get_icon(random_object)

        assert icon == "lock", "Implementation must ignore object attributes"

    @pytest.mark.regression
    @pytest.mark.positive
    def test_get_icon_return_type_is_string(self):
        """
        Confirm that the returned value is a plain Python string.
        """
        User = get_user_model()
        user = User(username="plain_string_check")

        lock = BaseLock()
        icon = lock.get_icon(user)

        assert icon == "lock", "Return value incorrect"
        assert isinstance(icon, str), "Return type should be built-in str"

    @pytest.mark.regression
    @pytest.mark.positive
    def test_get_icon_is_idempotent(self):
        """
        Call get_icon multiple times with different inputs and ensure the output
        is consistent across invocations.
        """
        User = get_user_model()
        user1 = User(username="user_one")
        user2 = User(username="user_two")

        lock = BaseLock()

        results = [
            lock.get_icon(user1),
            lock.get_icon(user2),
            lock.get_icon(None),
            lock.get_icon(AnonymousUser()),
            lock.get_icon(user1),  # repeat to double-check consistency
        ]

        assert all(res == "lock" for res in results), \
            "get_icon should be side-effect-free and always return 'lock'"
