# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=BasicLock.get_locked_by_b74b5fb9df
ROOST_METHOD_SIG_HASH=BasicLock.get_locked_by_41b18b2414


Scenario 1: Current user is the locker
Details:
  TestName: test_returns_locked_by_you_for_current_user
  Description: Verifies that the function recognises when the calling user is the one who locked the object and returns the “Locked by you” message.
Execution:
  Arrange: 
    • Create a stub admin-like instance whose .object attribute has locked_by_id set to the same primary key as the supplied user (e.g., user.pk == 42, locked_by_id == 42).  
    • Ensure the translation helper _() yields the plain string “Locked by you”.
  Act:
    • Invoke get_locked_by with the prepared admin instance and user.
  Assert:
    • Confirm the returned value is exactly “Locked by you”.
Validation:
  This test guarantees that branch #1 of the business logic is honoured whenever the lock is owned by the current user.

Scenario 2: Object is locked by someone else
Details:
  TestName: test_returns_locked_by_another_user
  Description: Confirms that the message “Locked by another user” is produced when the object is locked but not by the current user.
Execution:
  Arrange:
    • Stub admin instance: .object.locked_by_id = 13.  
    • user.pk = 42 (different from 13).  
  Act:
    • Call get_locked_by(admin, user).
  Assert:
    • The function returns “Locked by another user”.
Validation:
  Validates branch #2 of the logic, proving that any non-matching, truthy locked_by_id is reported as being held by “another user”.

Scenario 3: Object is not locked at all
Details:
  TestName: test_delegates_to_super_when_unlocked
  Description: Ensures that when locked_by_id is falsy/None, control is passed to the superclass implementation.
Execution:
  Arrange:
    • Build a minimal subclass in the test that overrides get_locked_by in its parent to return a sentinel string such as “No lock”.  
    • Set .object.locked_by_id = None.  
  Act:
    • Invoke the child’s get_locked_by(user).  
  Assert:
    • The return value matches the sentinel string, confirming delegation.
Validation:
  Demonstrates correct fallback behaviour (branch #3) whenever the object is unlocked.

Scenario 4: Anonymous or system user (pk is None) while another user holds the lock
Details:
  TestName: test_anonymous_user_receives_locked_by_another_user
  Description: Assures that even if the caller lacks a primary key, the function still indicates the lock belongs to someone else.
Execution:
  Arrange:
    • user.pk = None (simulates AnonymousUser or an improperly initialised user).  
    • .object.locked_by_id = 777 (truthy).  
  Act:
    • Call get_locked_by(admin, user).
  Assert:
    • Response is “Locked by another user”.
Validation:
  Protects against unexpected behaviour when user.pk is None; confirms the second branch does not erroneously match when equality cannot be established.

Scenario 5: Edge case with zero primary key that still matches
Details:
  TestName: test_zero_pk_still_matches_current_user
  Description: Checks that a primary key value of 0—although falsy—works correctly when equality is evaluated.
Execution:
  Arrange:
    • user.pk = 0  
    • .object.locked_by_id = 0  
  Act:
    • Run get_locked_by(admin, user).
  Assert:
    • Result is “Locked by you”.
Validation:
  Ensures that equality is tested before truthiness, preventing a logic error where 0 might have been discarded as falsy.

Scenario 6: Edge case with zero locked_by_id that does not match
Details:
  TestName: test_zero_locked_by_id_without_match_delegates_to_super
  Description: Proves that a falsy locked_by_id (0) that differs from user.pk bypasses the first two branches and falls through to the superclass.
Execution:
  Arrange:
    • user.pk = 5  
    • .object.locked_by_id = 0  
    • Superclass get_locked_by is patched to return “No lock”.  
  Act:
    • Invoke get_locked_by(admin, user).
  Assert:
    • Function returns “No lock”.
Validation:
  Verifies the precise order of conditions: equality check → truthiness check → superclass fallback.  This edge case would expose a flaw if the truthiness check mistakenly ran before equality.

"""

# ********RoostGPT********
import sys
import types
from types import SimpleNamespace

import pytest

# Mandatory imports requested by the instructions. They might not exist in the
# execution environment, therefore we provide light-weight stubs to keep the
# import machinery satisfied without affecting the actual test logic.
# --------------------------------------------------------------------------- #
# TODO: Replace these stubs with real libraries in an environment where Django
#       & Wagtail are installed.
for _missing_mod in [
    "django",
    "django.conf",
    "django.utils",
    "django.utils.html",
    "django.utils.safestring",
    "django.utils.text",
    "django.utils.translation",
    "wagtail",
    "wagtail.admin",
    "wagtail.admin.utils",
    "wagtail.utils",
    "wagtail.utils.timestamps",
    "wagtail.models",
]:
    if _missing_mod not in sys.modules:
        sys.modules[_missing_mod] = types.ModuleType(_missing_mod)

from django.conf import settings                          # noqa: F401  (stubbed)
from django.utils.html import format_html                 # noqa: F401
from django.utils.safestring import mark_safe             # noqa: F401
from django.utils.text import capfirst                    # noqa: F401
from django.utils.translation import gettext as _         # noqa: F401
from wagtail.admin.utils import (                          # noqa: F401
    get_latest_str,
    get_user_display_name,
)
from wagtail.utils.timestamps import render_timestamp     # noqa: F401
from wagtail.models import Page                           # noqa: F401

# The class under test
from wagtail.locks import BasicLock


class Test_BasicLockGetLockedBy:
    """Unit-tests for BasicLock.get_locked_by covering multiple scenarios."""

    # --------------------------------------------------------------------- #
    # Scenario 1: current user is the locker
    # --------------------------------------------------------------------- #
    @pytest.mark.smoke
    @pytest.mark.positive
    def test_returns_locked_by_you_for_current_user(self):
        user_pk = 42
        user = SimpleNamespace(pk=user_pk)

        # Create a bare BasicLock instance without invoking its constructor.
        lock = BasicLock.__new__(BasicLock)
        lock.object = SimpleNamespace(locked_by_id=user_pk)

        result = lock.get_locked_by(user)
        assert str(result) == "Locked by you"

    # --------------------------------------------------------------------- #
    # Scenario 2: object is locked by *another* user
    # --------------------------------------------------------------------- #
    @pytest.mark.regression
    @pytest.mark.negative
    def test_returns_locked_by_another_user(self):
        user = SimpleNamespace(pk=42)
        lock = BasicLock.__new__(BasicLock)
        lock.object = SimpleNamespace(locked_by_id=13)

        result = lock.get_locked_by(user)
        assert str(result) == "Locked by another user"

    # --------------------------------------------------------------------- #
    # Helper mixin supplying the sentinel implementation used by scenarios
    # that must verify delegation to super().
    # --------------------------------------------------------------------- #
    class _SentinelMixin:
        sentinel_text = "No lock"

        def get_locked_by(self, user):  # noqa: D401
            """Return a constant string so tests can detect delegation."""
            return self.sentinel_text

    # --------------------------------------------------------------------- #
    # Scenario 3: unlocked object should delegate to super()
    # --------------------------------------------------------------------- #
    @pytest.mark.valid
    def test_delegates_to_super_when_unlocked(self):
        class ChildLock(BasicLock, self._SentinelMixin):
            pass

        user = SimpleNamespace(pk=1)
        lock = ChildLock.__new__(ChildLock)
        lock.object = SimpleNamespace(locked_by_id=None)

        result = lock.get_locked_by(user)
        assert result == ChildLock.sentinel_text

    # --------------------------------------------------------------------- #
    # Scenario 4: anonymous/system user (pk=None) while another user holds the
    # lock.
    # --------------------------------------------------------------------- #
    @pytest.mark.security
    def test_anonymous_user_receives_locked_by_another_user(self):
        user = SimpleNamespace(pk=None)
        lock = BasicLock.__new__(BasicLock)
        lock.object = SimpleNamespace(locked_by_id=777)

        result = lock.get_locked_by(user)
        assert str(result) == "Locked by another user"

    # --------------------------------------------------------------------- #
    # Scenario 5: edge-case where pk == 0 (falsy) but still matches
    # --------------------------------------------------------------------- #
    @pytest.mark.edge
    def test_zero_pk_still_matches_current_user(self):
        user = SimpleNamespace(pk=0)
        lock = BasicLock.__new__(BasicLock)
        lock.object = SimpleNamespace(locked_by_id=0)

        result = lock.get_locked_by(user)
        assert str(result) == "Locked by you"

    # --------------------------------------------------------------------- #
    # Scenario 6: locked_by_id == 0 (falsy) AND does *not* match -> delegate
    # --------------------------------------------------------------------- #
    @pytest.mark.edge
    def test_zero_locked_by_id_without_match_delegates_to_super(self):
        class ChildLock(BasicLock, self._SentinelMixin):
            pass

        user = SimpleNamespace(pk=5)
        lock = ChildLock.__new__(ChildLock)
        lock.object = SimpleNamespace(locked_by_id=0)

        result = lock.get_locked_by(user)
        assert result == ChildLock.sentinel_text
