# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=BaseLock.get_context_for_user_661bbd054b
ROOST_METHOD_SIG_HASH=BaseLock.get_context_for_user_d74a922eb7


 
Scenario 1: Returns a fully populated context when lock applies to the user
Details:
  TestName: test_returns_expected_context_when_locked
  Description: Verifies that the function assembles the correct dictionary when the underlying for_user method reports that the current user is affected by the lock.
Execution:
  Arrange: Create a subclass or monkeypatch the instance so that for_user returns True, get_message returns "Editing is locked", get_icon returns "lock", get_locked_by returns "Admin", and get_description returns "No one can edit while locked".
  Act: Call get_context_for_user(user, parent_context=None).
  Assert: The returned value equals 
          {
              "locked": True,
              "message": "Editing is locked",
              "icon": "lock",
              "locked_by": "Admin",
              "description": "No one can edit while locked",
          } and contains exactly five keys.
Validation:
  Rationalize that, per business rules, when a lock is active for the user, locked must be True and every other delegated field must propagate unchanged to the resulting context. 

"""

# ********RoostGPT********
import sys
import types

# ---------------------------------------------------------------------------
# Optional dependency stubs to allow the tests to run without Django/Wagtail
# ---------------------------------------------------------------------------
try:
    from django.conf import settings  # noqa: F401
    from django.utils.html import format_html  # noqa: F401
    from django.utils.safestring import mark_safe  # noqa: F401
    from django.utils.text import capfirst  # noqa: F401
    from django.utils.translation import gettext as _  # noqa: F401
    from wagtail.admin.utils import get_latest_str, get_user_display_name  # noqa: F401
    from wagtail.utils.timestamps import render_timestamp  # noqa: F401
    from wagtail.models import Page  # noqa: F401
except ModuleNotFoundError:
    # Create minimal stub modules/functions so imports succeed
    django_stub = types.ModuleType("django")
    sys.modules["django"] = django_stub

    django_conf_stub = types.ModuleType("django.conf")
    django_conf_stub.settings = types.SimpleNamespace()
    sys.modules["django.conf"] = django_conf_stub
    django_stub.conf = django_conf_stub

    django_utils_stub = types.ModuleType("django.utils")
    sys.modules["django.utils"] = django_utils_stub

    django_utils_html_stub = types.ModuleType("django.utils.html")
    django_utils_html_stub.format_html = lambda *args, **kwargs: "".join(map(str, args))
    sys.modules["django.utils.html"] = django_utils_html_stub
    django_utils_stub.html = django_utils_html_stub

    django_utils_safestring_stub = types.ModuleType("django.utils.safestring")
    django_utils_safestring_stub.mark_safe = lambda x: x
    sys.modules["django.utils.safestring"] = django_utils_safestring_stub
    django_utils_stub.safestring = django_utils_safestring_stub

    django_utils_text_stub = types.ModuleType("django.utils.text")
    django_utils_text_stub.capfirst = lambda x: x.capitalize() if x else x
    sys.modules["django.utils.text"] = django_utils_text_stub
    django_utils_stub.text = django_utils_text_stub

    django_utils_translation_stub = types.ModuleType("django.utils.translation")
    django_utils_translation_stub.gettext = lambda x: x
    sys.modules["django.utils.translation"] = django_utils_translation_stub
    django_utils_stub.translation = django_utils_translation_stub

    wagtail_stub = types.ModuleType("wagtail")
    sys.modules["wagtail"] = wagtail_stub

    wagtail_admin_stub = types.ModuleType("wagtail.admin")
    wagtail_admin_utils_stub = types.ModuleType("wagtail.admin.utils")
    wagtail_admin_utils_stub.get_latest_str = lambda *args, **kwargs: "latest"
    wagtail_admin_utils_stub.get_user_display_name = lambda user: getattr(user, "username", str(user))
    sys.modules["wagtail.admin"] = wagtail_admin_stub
    sys.modules["wagtail.admin.utils"] = wagtail_admin_utils_stub
    wagtail_admin_stub.utils = wagtail_admin_utils_stub

    wagtail_utils_stub = types.ModuleType("wagtail.utils")
    wagtail_utils_timestamps_stub = types.ModuleType("wagtail.utils.timestamps")
    wagtail_utils_timestamps_stub.render_timestamp = lambda *args, **kwargs: "timestamp"
    sys.modules["wagtail.utils"] = wagtail_utils_stub
    sys.modules["wagtail.utils.timestamps"] = wagtail_utils_timestamps_stub
    wagtail_utils_stub.timestamps = wagtail_utils_timestamps_stub

    wagtail_models_stub = types.ModuleType("wagtail.models")
    wagtail_models_stub.Page = object
    sys.modules["wagtail.models"] = wagtail_models_stub

    # Re-attempt imports now that stubs exist
    from django.conf import settings  # noqa: F401
    from django.utils.html import format_html  # noqa: F401
    from django.utils.safestring import mark_safe  # noqa: F401
    from django.utils.text import capfirst  # noqa: F401
    from django.utils.translation import gettext as _  # noqa: F401
    from wagtail.admin.utils import get_latest_str, get_user_display_name  # noqa: F401
    from wagtail.utils.timestamps import render_timestamp  # noqa: F401
    from wagtail.models import Page  # noqa: F401

# ---------------------------------------------------------------------------
# Standard library / third-party imports for testing
# ---------------------------------------------------------------------------
import pytest

# ---------------------------------------------------------------------------
# System under test
# ---------------------------------------------------------------------------
from wagtail.locks import BaseLock


class Test_BaseLockGetContextForUser:
    """Unit tests for BaseLock.get_context_for_user."""

    @pytest.mark.smoke
    @pytest.mark.positive
    def test_returns_expected_context_when_locked(self):
        """
        Verifies that the function assembles the correct dictionary when the
        underlying for_user method reports that the current user is affected
        by the lock.
        """

        # ------------------------------------------------------------------
        # Arrange
        # ------------------------------------------------------------------
        class DummyLock(BaseLock):
            """A concrete implementation of BaseLock for testing purposes."""

            def for_user(self, user):
                return True

            def get_message(self, user):
                return "Editing is locked"

            def get_icon(self, user):
                return "lock"

            def get_locked_by(self, user):
                return "Admin"

            def get_description(self, user):
                return "No one can edit while locked"

        dummy_lock = DummyLock()
        user = object()  # Using a generic object as the user placeholder

        expected_context = {
            "locked": True,
            "message": "Editing is locked",
            "icon": "lock",
            "locked_by": "Admin",
            "description": "No one can edit while locked",
        }

        # ------------------------------------------------------------------
        # Act
        # ------------------------------------------------------------------
        actual_context = dummy_lock.get_context_for_user(user, parent_context=None)  # noqa: E501  # TODO: pass a real parent_context if needed

        # ------------------------------------------------------------------
        # Assert
        # ------------------------------------------------------------------
        assert actual_context == expected_context, "Context dictionary does not match expected output."  # noqa: E501
        assert len(actual_context) == 5, "Context dictionary should contain exactly five keys."
