# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=camelcase_to_underscore_3e830515d5
ROOST_METHOD_SIG_HASH=camelcase_to_underscore_22767c56ff


Scenario 1: Standard two-word CamelCase conversion
Details:
  TestName: test_standard_camelcase
  Description: Verify that a simple two-word CamelCase string is correctly converted to snake_case.
Execution:
  Arrange: Define input_string = "CamelCase".
  Act: result = camelcase_to_underscore(input_string)
  Assert: result == "camel_case".
Validation:
  This confirms that the primary, everyday use-case works as intended.

Scenario 2: Input already in lowercase should remain unchanged
Details:
  TestName: test_already_lowercase
  Description: Ensure that a string containing no uppercase letters is returned untouched (other than .lower()).
Execution:
  Arrange: input_string = "lowercase".
  Act: result = camelcase_to_underscore(input_string)
  Assert: result == "lowercase".
Validation:
  Guards against unwanted insertion of underscores when no pattern match exists.

Scenario 3: Single uppercase character
Details:
  TestName: test_single_uppercase_char
  Description: Confirm that a lone capital letter is lower-cased without producing leading or trailing underscores.
Execution:
  Arrange: input_string = "X".
  Act: result = camelcase_to_underscore(input_string)
  Assert: result == "x".
Validation:
  Exercises the `_strip` logic, proving that generated boundary underscores are removed.

Scenario 4: Acronym at the start of the string
Details:
  TestName: test_leading_acronym
  Description: Check behaviour when the identifier begins with a run of consecutive capitals.
Execution:
  Arrange: input_string = "XMLHttpRequest".
  Act: result = camelcase_to_underscore(input_string)
  Assert: result == "xml_http_request".
Validation:
  Shows that the regex does not split the acronym itself but places an underscore before the first mixed-case boundary.

Scenario 5: Acronym in the middle of the string
Details:
  TestName: test_internal_acronym
  Description: Ensure that acronyms embedded mid-string are handled gracefully.
Execution:
  Arrange: input_string = "UserIDNumber".
  Act: result = camelcase_to_underscore(input_string)
  Assert: result == "user_id_number".
Validation:
  Verifies that the final capital of the acronym, followed by a non-capital, produces the expected single underscore.

Scenario 6: Acronym at the end of the string
Details:
  TestName: test_trailing_acronym
  Description: Validate handling when the word ends in an all-cap acronym.
Execution:
  Arrange: input_string = "GetHTTP".
  Act: result = camelcase_to_underscore(input_string)
  Assert: result == "get_http".
Validation:
  Confirms the second branch of the regex where an uppercase letter precedes end-of-string.

Scenario 7: Mixed digits and capitals
Details:
  TestName: test_digits_and_capitals
  Description: Check that digits do not interfere with underscore insertion before an uppercase letter.
Execution:
  Arrange: input_string = "Version2Update".
  Act: result = camelcase_to_underscore(input_string)
  Assert: result == "version2_update".
Validation:
  Ensures digits are treated as neutral characters with respect to matching rules.

Scenario 8: Input already in snake_case should be idempotent
Details:
  TestName: test_idempotence_on_snake_case
  Description: The function should not alter an already correctly formatted identifier.
Execution:
  Arrange: input_string = "already_snake_case".
  Act: first = camelcase_to_underscore(input_string); second = camelcase_to_underscore(first)
  Assert: first == "already_snake_case" and second == first
Validation:
  Protects against accidental degradation when reusing the transformer on its own output.

Scenario 9: Leading and trailing underscores in the source
Details:
  TestName: test_strip_generated_not_original
  Description: Validate that original boundary underscores are preserved while generated ones are stripped.
Execution:
  Arrange: input_string = "__CamelCase__".
  Act: result = camelcase_to_underscore(input_string)
  Assert: result == "__camel_case__".
Validation:
  Proves that `strip("_")` only affects underscores added by the regex replacement, not user-supplied ones.

Scenario 10: Non-ASCII uppercase letter followed by ASCII uppercase
Details:
  TestName: test_unicode_capital
  Description: Ensure correct behaviour with a Unicode capital outside A-Z, which the regex will ignore.
Execution:
  Arrange: input_string = "ÜberWord".
  Act: result = camelcase_to_underscore(input_string)
  Assert: result == "über_word".
Validation:
  Confirms .lower() handles Unicode while the regex still splits before ASCII caps.

Scenario 11: Empty string input
Details:
  TestName: test_empty_string
  Description: Verify that supplying an empty string returns an empty string without error.
Execution:
  Arrange: input_string = "".
  Act: result = camelcase_to_underscore(input_string)
  Assert: result == "".
Validation:
  Establishes robustness against degenerate but possible input.

Scenario 12: Multiple successive capitals split only once
Details:
  TestName: test_multiple_successive_capitals
  Description: Confirm that a run of capitals generates a single underscore before the run, not between each pair.
Execution:
  Arrange: input_string = "HTTPRequest".
  Act: result = camelcase_to_underscore(input_string)
  Assert: result == "http_request".
Validation:
  Demonstrates that the first alternative in the regex is suppressed for a capital preceded by another capital, preventing over-splitting.

"""

# ********RoostGPT********
import functools
import inspect
import logging
import re
import unicodedata
from collections.abc import Iterable
from hashlib import md5
from typing import TYPE_CHECKING, Any

import pytest

# ------------------------------------------------------------------------------
# Third-party, optional dependencies
# ------------------------------------------------------------------------------

# The following imports are declared inside try / except blocks so that the test
# suite remains runnable even when the host environment does not provide Django
# or Wagtail.  When the libraries are present, they will be used normally;
# otherwise, tests will be skipped automatically via pytest.importorskip.
try:
    from anyascii import anyascii  # noqa: F401
except ModuleNotFoundError:  # pragma: no cover
    anyascii = None  # type: ignore

# Optional Django & Wagtail stack ------------------------------------------------
try:
    from django.apps import apps  # noqa: F401
    from django.conf import settings  # noqa: F401
    from django.conf.locale import LANG_INFO  # noqa: F401
    from django.core.cache import cache  # noqa: F401
    from django.core.cache.utils import make_template_fragment_key  # noqa: F401
    from django.core.exceptions import ImproperlyConfigured, SuspiciousOperation  # noqa: F401
    from django.core.signals import setting_changed  # noqa: F401
    from django.db.models import Model  # noqa: F401
    from django.db.models.base import ModelBase  # noqa: F401
    from django.dispatch import receiver  # noqa: F401
    from django.http import HttpRequest  # noqa: F401
    from django.test import RequestFactory  # noqa: F401
    from django.utils.encoding import force_str  # noqa: F401
    from django.utils.text import capfirst, slugify  # noqa: F401
    from django.utils.translation import (  # noqa: F401
        check_for_language,
        get_supported_language_variant,
    )
    from django.utils.translation import gettext as _  # noqa: F401
    from wagtail.models import Locale, Site  # noqa: F401
except ModuleNotFoundError:  # pragma: no cover
    # If Django or Wagtail are not installed, we simply create dummies so that
    # the names exist. This keeps static analysis tools quiet and avoids
    # NameError inside the tests when these symbols are referenced only via noqa.
    import types
    apps = types.SimpleNamespace()  # type: ignore
    settings = types.SimpleNamespace()  # type: ignore
    LANG_INFO = {}
    cache = types.SimpleNamespace()
    make_template_fragment_key = lambda *_, **__: ""  # type: ignore
    ImproperlyConfigured = SuspiciousOperation = RuntimeError  # type: ignore
    setting_changed = receiver = lambda *_, **__: None  # type: ignore
    Model = ModelBase = HttpRequest = RequestFactory = object  # type: ignore
    force_str = lambda s: str(s)  # type: ignore
    capfirst = slugify = lambda s: str(s)  # type: ignore
    check_for_language = get_supported_language_variant = lambda *_, **__: ""  # type: ignore
    _ = lambda s: s  # type: ignore
    Locale = Site = object  # type: ignore

# ------------------------------------------------------------------------------
# Target under test
# ------------------------------------------------------------------------------
# If Wagtail is not installed, all tests in this module will be skipped.
pytest.importorskip("wagtail.coreutils")
from wagtail.coreutils import camelcase_to_underscore  # noqa: E402


logger = logging.getLogger(__name__)


@pytest.mark.usefixtures()
class Test_CoreutilsCamelcaseToUnderscore:
    """Unit-tests for wagtail.coreutils.camelcase_to_underscore"""

    # ----------------------------------------------------------------------
    # Scenario 1
    # ----------------------------------------------------------------------
    @pytest.mark.smoke
    @pytest.mark.positive
    def test_standard_camelcase(self) -> None:
        """
        Verify that a simple two-word CamelCase string is correctly converted
        to snake_case.
        """
        input_string = "CamelCase"
        result = camelcase_to_underscore(input_string)
        assert result == "camel_case"

    # ----------------------------------------------------------------------
    # Scenario 2
    # ----------------------------------------------------------------------
    @pytest.mark.regression
    @pytest.mark.positive
    def test_already_lowercase(self) -> None:
        """
        Ensure that a string containing no uppercase letters is returned
        untouched.
        """
        input_string = "lowercase"
        result = camelcase_to_underscore(input_string)
        assert result == "lowercase"

    # ----------------------------------------------------------------------
    # Scenario 3
    # ----------------------------------------------------------------------
    @pytest.mark.edge
    @pytest.mark.positive
    def test_single_uppercase_char(self) -> None:
        """
        Confirm that a lone capital letter is lower-cased without producing
        leading or trailing underscores.
        """
        input_string = "X"
        result = camelcase_to_underscore(input_string)
        assert result == "x"

    # ----------------------------------------------------------------------
    # Scenario 4
    # ----------------------------------------------------------------------
    @pytest.mark.regression
    @pytest.mark.positive
    def test_leading_acronym(self) -> None:
        """
        Check behaviour when the identifier begins with a run of consecutive
        capitals.
        """
        input_string = "XMLHttpRequest"
        result = camelcase_to_underscore(input_string)
        assert result == "xml_http_request"

    # ----------------------------------------------------------------------
    # Scenario 5
    # ----------------------------------------------------------------------
    @pytest.mark.regression
    @pytest.mark.positive
    def test_internal_acronym(self) -> None:
        """
        Ensure that acronyms embedded mid-string are handled gracefully.
        """
        input_string = "UserIDNumber"
        result = camelcase_to_underscore(input_string)
        assert result == "user_id_number"

    # ----------------------------------------------------------------------
    # Scenario 6
    # ----------------------------------------------------------------------
    @pytest.mark.regression
    @pytest.mark.positive
    def test_trailing_acronym(self) -> None:
        """
        Validate handling when the word ends in an all-cap acronym.
        """
        input_string = "GetHTTP"
        result = camelcase_to_underscore(input_string)
        assert result == "get_http"

    # ----------------------------------------------------------------------
    # Scenario 7
    # ----------------------------------------------------------------------
    @pytest.mark.regression
    @pytest.mark.positive
    def test_digits_and_capitals(self) -> None:
        """
        Check that digits do not interfere with underscore insertion before an
        uppercase letter.
        """
        input_string = "Version2Update"
        result = camelcase_to_underscore(input_string)
        assert result == "version2_update"

    # ----------------------------------------------------------------------
    # Scenario 8
    # ----------------------------------------------------------------------
    @pytest.mark.regression
    @pytest.mark.positive
    def test_idempotence_on_snake_case(self) -> None:
        """
        The function should not alter an already correctly formatted identifier.
        """
        input_string = "already_snake_case"
        first = camelcase_to_underscore(input_string)
        second = camelcase_to_underscore(first)
        assert first == "already_snake_case"
        assert second == first

    # ----------------------------------------------------------------------
    # Scenario 9
    # ----------------------------------------------------------------------
    @pytest.mark.regression
    @pytest.mark.negative
    def test_strip_generated_not_original(self) -> None:
        """
        Validate that original boundary underscores get removed along with
        automatically generated ones.  This reflects the actual behaviour of
        Wagtail’s implementation which performs a blanket strip('_').
        """
        input_string = "__CamelCase__"
        result = camelcase_to_underscore(input_string)
        # NOTE: Due to .strip("_"), leading / trailing underscores are removed
        # entirely.  The expected string therefore contains none of the outer
        # underscores.
        expected_output = "camel_case"
        assert result == expected_output

    # ----------------------------------------------------------------------
    # Scenario 10
    # ----------------------------------------------------------------------
    @pytest.mark.regression
    @pytest.mark.positive
    def test_unicode_capital(self) -> None:
        """
        Ensure correct behaviour with a Unicode capital outside A-Z, which the
        regex will ignore.
        """
        input_string = "ÜberWord"
        result = camelcase_to_underscore(input_string)
        assert result == "über_word"

    # ----------------------------------------------------------------------
    # Scenario 11
    # ----------------------------------------------------------------------
    @pytest.mark.edge
    @pytest.mark.positive
    def test_empty_string(self) -> None:
        """
        Verify that supplying an empty string returns an empty string without
        error.
        """
        input_string = ""
        result = camelcase_to_underscore(input_string)
        assert result == ""

    # ----------------------------------------------------------------------
    # Scenario 12
    # ----------------------------------------------------------------------
    @pytest.mark.regression
    @pytest.mark.positive
    def test_multiple_successive_capitals(self) -> None:
        """
        Confirm that a run of capitals generates a single underscore before the
        run, not between each pair.
        """
        input_string = "HTTPRequest"
        result = camelcase_to_underscore(input_string)
        assert result == "http_request"
