# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=string_to_ascii_a5407058d0
ROOST_METHOD_SIG_HASH=string_to_ascii_4926679cb9


 
Scenario 1: Returns identical string for pure ASCII input
Details:
  TestName: test_ascii_identity_basic
  Description: Verify that an already‐ASCII string is returned unchanged, ensuring the function does not modify compliant input.
Execution:
  Arrange: Prepare the input value "PlainText123!?".
  Act: Call string_to_ascii with this value.
  Assert: The returned string is exactly "PlainText123!?" and every character is ASCII.
Validation:
  Confirms the no-op behaviour on valid ASCII data, which is the most common use-case in production logs and messages.

"""

# ********RoostGPT********
import functools
import inspect
import logging
import re
import unicodedata
from collections.abc import Iterable
from hashlib import md5
from typing import TYPE_CHECKING, Any

import pytest
from anyascii import anyascii
from django.apps import apps
from django.conf import settings
from django.conf.locale import LANG_INFO
from django.core.cache import cache
from django.core.cache.utils import make_template_fragment_key
from django.core.exceptions import ImproperlyConfigured, SuspiciousOperation
from django.core.signals import setting_changed
from django.db.models import Model
from django.db.models.base import ModelBase
from django.dispatch import receiver
from django.http import HttpRequest
from django.test import RequestFactory
from django.utils.encoding import force_str
from django.utils.text import capfirst, slugify
from django.utils.translation import check_for_language, get_supported_language_variant
from django.utils.translation import gettext as _
from wagtail.models import Site, Locale  # type: ignore

# Import function under test
from wagtail.coreutils import string_to_ascii


class Test_CoreutilsStringToAscii:
    @pytest.mark.smoke
    @pytest.mark.valid
    @pytest.mark.positive
    def test_ascii_identity_basic(self):
        """
        Scenario 1:
        Verify that an already-ASCII string is returned unchanged
        by string_to_ascii.
        """
        # Arrange
        original_text = "PlainText123!?"  # Pure ASCII input

        # Act
        converted_text = string_to_ascii(original_text)

        # Assert: unchanged output
        assert converted_text == original_text, (
            "string_to_ascii should return identical string for pure ASCII input"
        )

        # Assert: each character is ASCII (code point < 128)
        assert all(ord(char) < 128 for char in converted_text), (
            "All characters in the result should be ASCII"
        )
