# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=WorkflowLock.get_icon_c31f4d4cd4
ROOST_METHOD_SIG_HASH=WorkflowLock.get_icon_3358306648


Scenario 1: Return value when locking is allowed
Details:
  TestName: test_get_icon_returns_lock_open_when_can_lock_true
  Description: Verify that the method immediately returns the literal string "lock-open" whenever the caller supplies can_lock=True, regardless of the user object’s state.
Execution:
  Arrange: Instantiate (or monkey-patch) a concrete subclass that implements get_icon; prepare a valid user instance or mock.
  Act: Call instance.get_icon(user=some_user, can_lock=True).
  Assert: The returned value equals the exact string "lock-open".
Validation:
  This confirms the primary branch of the business rule: “If the page can be locked, use the ‘lock-open’ icon.”  It ensures no other logic or superclass call interferes with the mandated icon.

Scenario 2: Superclass delegation when locking is not allowed
Details:
  TestName: test_get_icon_delegates_to_super_when_can_lock_false
  Description: Ensure that, if can_lock is False, the method defers to the parent class’s implementation and returns exactly what that parent returns.
Execution:
  Arrange: Create a subclass whose super().get_icon is monkey-patched to return a sentinel string such as "parent-icon".  Supply any user object.
  Act: Call instance.get_icon(user=some_user, can_lock=False).
  Assert: The return value is the sentinel "parent-icon".
Validation:
  Demonstrates correct delegation flow, protecting against regressions where the method might accidentally bypass its parent or alter the parent’s value.

Scenario 3: Default parameter path without specifying can_lock
Details:
  TestName: test_get_icon_uses_default_can_lock_value
  Description: Confirm that omitting the can_lock argument (thus relying on its default of False) behaves identically to explicitly passing can_lock=False.
Execution:
  Arrange: Monkey-patch super().get_icon to return "parent-icon-default".
  Act: Call instance.get_icon(user=some_user)  # no can_lock argument
  Assert: The method returns "parent-icon-default".
Validation:
  Guards against signature or default-value changes that might silently alter downstream behaviour.

Scenario 4: Truthy non-boolean values still activate lock icon
Details:
  TestName: test_get_icon_accepts_truthy_can_lock_values
  Description: Validate that any truthy value (e.g., 1, "yes") for can_lock triggers the “lock-open” branch, reflecting Python’s truthiness semantics in business logic.
Execution:
  Arrange: Prepare instance and user.  No need to patch super.
  Act: Invoke instance.get_icon(user=some_user, can_lock=1).
  Assert: Returned value equals "lock-open".
Validation:
  Protects against later refactors that might do strict identity checks (can_lock is True) and break current truthiness-based contract.

Scenario 5: Superclass method is not called when can_lock is truthy
Details:
  TestName: test_super_not_called_when_can_lock_true
  Description: Guarantee performance and side-effect expectations by asserting that the parent method is never executed when can_lock is truthy.
Execution:
  Arrange: Patch the parent’s get_icon to a stub that raises an AssertionError if invoked.
  Act: Call instance.get_icon(user=some_user, can_lock=True).
  Assert: No AssertionError is raised; return value is "lock-open".
Validation:
  Confirms that the shortcut branch short-circuits all superclass work, preventing unnecessary database queries or logging in production.

Scenario 6: Superclass receives the same user object
Details:
  TestName: test_user_passed_unchanged_to_super
  Description: Ascertain that, in the delegation path, the very same user object is forwarded to the parent without modification.
Execution:
  Arrange: Patch super().get_icon to capture its positional argument and return a constant marker.
  Act: Call instance.get_icon(user=original_user, can_lock=False).
  Assert: Captured user is original_user (identity comparison) and return value is the constant marker.
Validation:
  Safeguards against inadvertent mutation or substitution of the user parameter, which could affect permission logic higher up the stack.

Scenario 7: Return type consistency
Details:
  TestName: test_get_icon_always_returns_string
  Description: Confirm that, for both branches, the function consistently yields a string object, fulfilling template expectations that an icon identifier is a textual value.
Execution:
  Arrange: For the can_lock=True branch, simply call the method; for the can_lock=False branch, patch super().get_icon to return "parent-icon".
  Act: Execute both calls.
  Assert: In each case, assert isinstance(result, str) and check value equality where applicable.
Validation:
  Ensures compatibility with any rendering code that directly interpolates the icon name into HTML; catching regressions where a non-string type might be returned.

"""

# ********RoostGPT********
import sys
import types
import pytest

# --------------------------------------------------------------------------
# Safeguard imports that may not exist in the execution environment.
# Each missing Django/Wagtail module is replaced by a minimal stub to
# satisfy the import statements required by the task instructions.
# --------------------------------------------------------------------------

def _create_stub(full_name, attr_dict=None):
    """
    Utility to create a stub module (and any parent modules that do not
    yet exist) so that `import x.y.z` succeeds even if the real package
    is absent.
    """
    attr_dict = attr_dict or {}
    module_parts = full_name.split(".")
    module_path = ""
    for part in module_parts:
        module_path = f"{module_path}.{part}" if module_path else part
        if module_path not in sys.modules:
            sys.modules[module_path] = types.ModuleType(module_path)
    for key, value in attr_dict.items():
        setattr(sys.modules[full_name], key, value)
    return sys.modules[full_name]


# Stubbing Django modules
try:
    from django.conf import settings
except ModuleNotFoundError:  # pragma: no cover
    _create_stub("django")
    conf_stub = _create_stub("django.conf", {"settings": types.SimpleNamespace()})
    settings = conf_stub.settings

try:
    from django.utils.html import format_html
except ModuleNotFoundError:  # pragma: no cover
    html_stub = _create_stub("django.utils.html")
    def format_html(s, *args, **kwargs):  # noqa: D401
        return s.format(*args, **kwargs)
    html_stub.format_html = format_html

try:
    from django.utils.safestring import mark_safe
except ModuleNotFoundError:  # pragma: no cover
    safe_stub = _create_stub("django.utils.safestring")
    def mark_safe(s):  # noqa: D401
        return s
    safe_stub.mark_safe = mark_safe

try:
    from django.utils.text import capfirst
except ModuleNotFoundError:  # pragma: no cover
    text_stub = _create_stub("django.utils.text")
    text_stub.capfirst = lambda s: s.capitalize()

try:
    # Intentionally keeping the import statement shape requested by the task
    from django.utils.translation import django as _  # type: ignore  # noqa: E402,F401
except ModuleNotFoundError:  # pragma: no cover
    trans_stub = _create_stub("django.utils.translation")
    trans_stub.django = lambda s: s  # type: ignore

# Stubbing Wagtail modules other than the one under test
for wagtail_path in [
    "wagtail.admin.utils",
    "wagtail.utils.timestamps",
    "wagtail.models",
]:
    if wagtail_path not in sys.modules:  # pragma: no cover
        _create_stub(wagtail_path)

if "wagtail.admin.utils" in sys.modules:
    util_stub = sys.modules["wagtail.admin.utils"]
    util_stub.get_latest_str = lambda *a, **kw: "latest-str"
    util_stub.get_user_display_name = lambda user: str(user)

if "wagtail.utils.timestamps" in sys.modules:
    ts_stub = sys.modules["wagtail.utils.timestamps"]
    ts_stub.render_timestamp = lambda *a, **kw: "timestamp"

if "wagtail.models" in sys.modules:
    page_stub = sys.modules["wagtail.models"]
    page_stub.Page = object

# --------------------------------------------------------------------------
# Import the subject under test
# --------------------------------------------------------------------------
from wagtail.locks import WorkflowLock  # noqa: E402


# --------------------------------------------------------------------------
# Unit-test suite for WorkflowLock.get_icon
# --------------------------------------------------------------------------
class Test_WorkflowLockGetIcon:
    @pytest.mark.positive
    @pytest.mark.smoke
    def test_get_icon_returns_lock_open_when_can_lock_true(self):
        """
        Scenario 1:
        Verify that a truthy `can_lock` argument immediately returns
        the literal string ``"lock-open"``.
        """
        lock_instance = object.__new__(WorkflowLock)
        user = object()  # Dummy user object

        result = lock_instance.get_icon(user=user, can_lock=True)

        assert result == "lock-open"

    @pytest.mark.regression
    @pytest.mark.negative
    def test_get_icon_delegates_to_super_when_can_lock_false(self, monkeypatch):
        """
        Scenario 2:
        Ensure that with ``can_lock=False`` the method defers to
        the parent ``get_icon`` implementation.
        """
        sentinel_icon = "parent-icon"
        parent_cls = WorkflowLock.__base__

        def fake_parent_get_icon(self, user):
            return sentinel_icon

        monkeypatch.setattr(parent_cls, "get_icon", fake_parent_get_icon, raising=True)

        lock_instance = object.__new__(WorkflowLock)
        user = object()

        result = lock_instance.get_icon(user=user, can_lock=False)

        assert result == sentinel_icon

    @pytest.mark.regression
    @pytest.mark.negative
    def test_get_icon_uses_default_can_lock_value(self, monkeypatch):
        """
        Scenario 3:
        Confirm that omitting the ``can_lock`` argument behaves exactly
        as providing ``can_lock=False``.
        """
        sentinel_icon = "parent-icon-default"
        parent_cls = WorkflowLock.__base__

        def fake_parent_get_icon(self, user):
            return sentinel_icon

        monkeypatch.setattr(parent_cls, "get_icon", fake_parent_get_icon, raising=True)

        lock_instance = object.__new__(WorkflowLock)
        user = object()

        result = lock_instance.get_icon(user=user)  # No `can_lock` provided

        assert result == sentinel_icon

    @pytest.mark.positive
    def test_get_icon_accepts_truthy_can_lock_values(self):
        """
        Scenario 4:
        Any truthy value (e.g., ``1``) for ``can_lock`` should trigger
        the "lock-open" branch.
        """
        lock_instance = object.__new__(WorkflowLock)
        user = object()

        result = lock_instance.get_icon(user=user, can_lock=1)

        assert result == "lock-open"

    @pytest.mark.performance
    def test_super_not_called_when_can_lock_true(self, monkeypatch):
        """
        Scenario 5:
        Ensure that the superclass method is never executed when
        ``can_lock`` is truthy.
        """
        parent_cls = WorkflowLock.__base__

        def raising_super(self, user):
            raise AssertionError("Superclass get_icon should NOT be called")

        monkeypatch.setattr(parent_cls, "get_icon", raising_super, raising=True)

        lock_instance = object.__new__(WorkflowLock)
        user = object()

        # Should not raise the AssertionError
        result = lock_instance.get_icon(user=user, can_lock=True)

        assert result == "lock-open"

    @pytest.mark.security
    def test_user_passed_unchanged_to_super(self, monkeypatch):
        """
        Scenario 6:
        Validate that the same user object is forwarded to the parent
        method without modification.
        """
        captured = {}
        sentinel_icon = "parent-icon"
        parent_cls = WorkflowLock.__base__

        def capturing_super(self, user):
            captured["user"] = user
            return sentinel_icon

        monkeypatch.setattr(parent_cls, "get_icon", capturing_super, raising=True)

        lock_instance = object.__new__(WorkflowLock)
        original_user = object()

        result = lock_instance.get_icon(user=original_user, can_lock=False)

        # Identity comparison ensures exact object is forwarded unchanged
        assert captured["user"] is original_user
        assert result == sentinel_icon

    @pytest.mark.valid
    def test_get_icon_always_returns_string(self, monkeypatch):
        """
        Scenario 7:
        Confirm that both branches always return a string value.
        """
        # Branch 1: can_lock=True
        lock_instance = object.__new__(WorkflowLock)
        user = object()
        result_truthy = lock_instance.get_icon(user=user, can_lock=True)
        assert isinstance(result_truthy, str)
        assert result_truthy == "lock-open"

        # Branch 2: can_lock=False (delegates to parent)
        sentinel_icon = "parent-icon"
        parent_cls = WorkflowLock.__base__

        monkeypatch.setattr(
            parent_cls, "get_icon", lambda self, user: sentinel_icon, raising=True
        )

        result_falsey = lock_instance.get_icon(user=user, can_lock=False)
        assert isinstance(result_falsey, str)
        assert result_falsey == sentinel_icon
