# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=InvokeViaAttributeShortcut.__setstate___375403b201
ROOST_METHOD_SIG_HASH=InvokeViaAttributeShortcut.__setstate___69f80bf131


Scenario 1: Successful restoration of a simple state dictionary
Details:
  TestName: test_setstate_restores_attributes
  Description: Verifies that when a valid state dictionary containing "obj" and "method_name" is supplied, the instance receives those exact values.
Execution:
  Arrange: Instantiate the target class with dummy constructor arguments (they will be overwritten). Create a state dict such as {"obj": 123, "method_name": "save"}.
  Act: Call instance.__setstate__(state).
  Assert: instance.obj == 123 and instance.method_name == "save".
Validation:
  Confirms the core business requirement that __setstate__ faithfully transfers the supplied state back into the object.

Scenario 2: Restoration when "obj" is a Django-like model instance
Details:
  TestName: test_setstate_accepts_model_instance
  Description: Ensures that complex objects (e.g., a stub subclass of django.db.models.Model) survive the round-trip intact.
Execution:
  Arrange: Create a lightweight fake model class (subclassing Model or a stub) and instantiate it; build state = {"obj": fake_model, "method_name": "full_clean"}.
  Act: Invoke __setstate__ with that state.
  Assert: The stored obj attribute is the *same object* (identity comparison) and retains its type.
Validation:
  Demonstrates that __setstate__ imposes no transformation on rich Django objects—critical for pickling support in Wagtail/Django environments.

Scenario 3: Overwriting pre-existing attributes
Details:
  TestName: test_setstate_overwrites_previous_values
  Description: Confirms that values originally present on the instance are replaced by those coming from state.
Execution:
  Arrange: Set instance.obj = "old", instance.method_name = "old_method" first. Supply new_state = {"obj": "new", "method_name": "new_method"}.
  Act: Call __setstate__(new_state).
  Assert: instance.obj == "new" and instance.method_name == "new_method".
Validation:
  Guarantees that deserialization fully overwrites stale data, preventing inconsistent object state.

Scenario 4: Missing "obj" key raises KeyError
Details:
  TestName: test_setstate_missing_obj_raises
  Description: Verifies defensive behavior when "obj" is absent from the state mapping.
Execution:
  Arrange: Build state_without_obj = {"method_name": "do"}.
  Act: Invoke __setstate__ inside pytest.raises(KeyError).
  Assert: The KeyError is raised and mentions "obj".
Validation:
  Matches Python’s normal dict lookup semantics and guards against corrupt pickle data.

Scenario 5: Missing "method_name" key raises KeyError
Details:
  TestName: test_setstate_missing_method_name_raises
  Description: Mirrors Scenario 4 for the complementary required key.
Execution:
  Arrange: state_without_method = {"obj": 1}.
  Act: Call __setstate__ expecting KeyError.
  Assert: Error message references "method_name".
Validation:
  Reinforces symmetry in error handling, ensuring both keys are mandatory.

Scenario 6: Extra keys in state are safely ignored
Details:
  TestName: test_setstate_ignores_extra_keys
  Description: Confirms that superfluous data in the state dictionary does not interfere with attribute restoration.
Execution:
  Arrange: state = {"obj": 1, "method_name": "go", "irrelevant": "data"}.
  Act: Call __setstate__(state).
  Assert: instance.obj == 1, instance.method_name == "go", and hasattr(instance, "irrelevant") is False (or unchanged if pre-existing).
Validation:
  Demonstrates tolerance for forward-compatibility or accidental additions in pickled data.

Scenario 7: State provided as a mapping subclass (e.g., collections.UserDict)
Details:
  TestName: test_setstate_works_with_mapping_subclass
  Description: Ensures that any Mapping-compatible object with the required keys is accepted.
Execution:
  Arrange: Create a UserDict containing {"obj": "x", "method_name": "m"}.
  Act: Pass it to __setstate__.
  Assert: Attributes correctly set without TypeError.
Validation:
  Confirms that the implementation only relies on the mapping interface—important for interoperability.

Scenario 8: Accepting a django.utils.functional.Promise without evaluation
Details:
  TestName: test_setstate_accepts_lazy_promise
  Description: Uses a lazy translation object (Promise) as "obj" or "method_name" to prove the function stores it verbatim, without forcing evaluation.
Execution:
  Arrange: Obtain a Promise via _("lazy text") and build state = {"obj": promise_obj, "method_name": "render"}.
  Act: Call __setstate__.
  Assert: isinstance(instance.obj, Promise) and str(instance.obj) is not accessed implicitly (no side effects).
Validation:
  Vital for i18n contexts where lazily-evaluated strings must remain lazy after unpickling.

Scenario 9: Explicitly storing None as method_name
Details:
  TestName: test_setstate_allows_none_method_name
  Description: Verifies that the method tolerates a None entry for "method_name" when that is a legitimate sentinel.
Execution:
  Arrange: state = {"obj": "whatever", "method_name": None}.
  Act: Call __setstate__.
  Assert: instance.method_name is None.
Validation:
  Confirms that __setstate__ does not impose restrictive type checks on the stored values, aligning with Python’s flexible serialization norms.

"""

# ********RoostGPT********
import functools
import inspect
import logging
import re
import unicodedata
from collections import UserDict
from collections.abc import Iterable
from hashlib import md5
from typing import TYPE_CHECKING, Any
import importlib

import pytest
from anyascii import anyascii
from django.apps import apps
from django.conf import settings
from django.conf.locale import LANG_INFO
from django.core.cache import cache
from django.core.cache.utils import make_template_fragment_key
from django.core.exceptions import ImproperlyConfigured, SuspiciousOperation
from django.core.signals import setting_changed
from django.db.models import Model
from django.db.models.base import ModelBase
from django.dispatch import receiver
from django.http import HttpRequest
from django.test import RequestFactory
from django.utils.encoding import force_str
from django.utils.text import capfirst, slugify
from django.utils.translation import (
    check_for_language,
    get_supported_language_variant,
    gettext_lazy as _,
)
from wagtail.models import Locale, Site

# ------------------------------------------------------------------------------
# Attempt to import the class under test from the preferred location first,
# falling back to a flat `coreutils` module if that exists in the environment.
# ------------------------------------------------------------------------------
try:
    from wagtail.coreutils import InvokeViaAttributeShortcut
except ModuleNotFoundError:  # pragma: no cover
    InvokeViaAttributeShortcut = importlib.import_module(
        "coreutils"
    ).InvokeViaAttributeShortcut  # type: ignore


class Test_InvokeViaAttributeShortcutSetstate:
    """
    Test-suite dedicated to the behaviour of `InvokeViaAttributeShortcut.__setstate__`.
    Each test corresponds to one of the formally documented scenarios.
    """

    # --------------------------------------------------------------------- #
    # Scenario 1 – simple happy-path restoration.
    # --------------------------------------------------------------------- #
    @pytest.mark.smoke
    @pytest.mark.positive
    def test_setstate_restores_attributes(self):
        instance = object.__new__(InvokeViaAttributeShortcut)  # bypass __init__
        state = {"obj": 123, "method_name": "save"}

        instance.__setstate__(state)

        assert instance.obj == 123
        assert instance.method_name == "save"

    # --------------------------------------------------------------------- #
    # Scenario 2 – accepting a Django-style model instance.
    # --------------------------------------------------------------------- #
    @pytest.mark.regression
    def test_setstate_accepts_model_instance(self):
        # Create a lightweight fake model. No DB interaction is required.
        class FakeModel(Model):
            class Meta:
                app_label = "tests"  # noqa: D401  # just a stub to satisfy Django

        fake_model = FakeModel()
        state = {"obj": fake_model, "method_name": "full_clean"}

        instance = object.__new__(InvokeViaAttributeShortcut)
        instance.__setstate__(state)

        # Identity and type must be preserved.
        assert instance.obj is fake_model
        assert isinstance(instance.obj, FakeModel)
        assert instance.method_name == "full_clean"

    # --------------------------------------------------------------------- #
    # Scenario 3 – previous attributes are overwritten.
    # --------------------------------------------------------------------- #
    @pytest.mark.negative
    def test_setstate_overwrites_previous_values(self):
        instance = object.__new__(InvokeViaAttributeShortcut)
        # Pre-populate with stale values.
        instance.obj = "old"
        instance.method_name = "old_method"

        new_state = {"obj": "new", "method_name": "new_method"}
        instance.__setstate__(new_state)

        assert instance.obj == "new"
        assert instance.method_name == "new_method"

    # --------------------------------------------------------------------- #
    # Scenario 4 – missing "obj" triggers KeyError.
    # --------------------------------------------------------------------- #
    @pytest.mark.invalid
    def test_setstate_missing_obj_raises(self):
        instance = object.__new__(InvokeViaAttributeShortcut)
        state_without_obj = {"method_name": "do"}

        with pytest.raises(KeyError) as exc_info:
            instance.__setstate__(state_without_obj)

        assert "obj" in str(exc_info.value)

    # --------------------------------------------------------------------- #
    # Scenario 5 – missing "method_name" triggers KeyError.
    # --------------------------------------------------------------------- #
    @pytest.mark.invalid
    def test_setstate_missing_method_name_raises(self):
        instance = object.__new__(InvokeViaAttributeShortcut)
        state_without_method = {"obj": 1}

        with pytest.raises(KeyError) as exc_info:
            instance.__setstate__(state_without_method)

        assert "method_name" in str(exc_info.value)

    # --------------------------------------------------------------------- #
    # Scenario 6 – extra keys are ignored.
    # --------------------------------------------------------------------- #
    @pytest.mark.regression
    def test_setstate_ignores_extra_keys(self):
        instance = object.__new__(InvokeViaAttributeShortcut)
        state = {"obj": 1, "method_name": "go", "irrelevant": "data"}

        instance.__setstate__(state)

        assert instance.obj == 1
        assert instance.method_name == "go"
        assert not hasattr(instance, "irrelevant")

    # --------------------------------------------------------------------- #
    # Scenario 7 – state as a Mapping subclass (UserDict).
    # --------------------------------------------------------------------- #
    @pytest.mark.regression
    def test_setstate_works_with_mapping_subclass(self):
        user_dict_state = UserDict({"obj": "x", "method_name": "m"})
        instance = object.__new__(InvokeViaAttributeShortcut)

        # Should not raise.
        instance.__setstate__(user_dict_state)

        assert instance.obj == "x"
        assert instance.method_name == "m"

    # --------------------------------------------------------------------- #
    # Scenario 8 – accepting django.utils.functional.Promise.
    # --------------------------------------------------------------------- #
    @pytest.mark.performance
    def test_setstate_accepts_lazy_promise(self):
        promise_obj = _("lazy text")  # returns a Promise object
        state = {"obj": promise_obj, "method_name": "render"}

        instance = object.__new__(InvokeViaAttributeShortcut)
        instance.__setstate__(state)

        # The stored object must still be a Promise (un-evaluated).
        from django.utils.functional import Promise

        assert isinstance(instance.obj, Promise)
        assert instance.obj is promise_obj
        assert instance.method_name == "render"

    # --------------------------------------------------------------------- #
    # Scenario 9 – allowing None for method_name.
    # --------------------------------------------------------------------- #
    @pytest.mark.edgecase
    def test_setstate_allows_none_method_name(self):
        instance = object.__new__(InvokeViaAttributeShortcut)
        state = {"obj": "whatever", "method_name": None}

        instance.__setstate__(state)

        assert instance.obj == "whatever"
        assert instance.method_name is None
