# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=ScheduledForPublishLock.get_message_08e00b3b31
ROOST_METHOD_SIG_HASH=ScheduledForPublishLock.get_message_38d14a7494


Scenario 1: Happy path – correctly composed message
Details:
  TestName: test_get_message_returns_expected_string
  Description: Confirms that a standard call returns the properly formatted, capitalised and safe HTML message.
Execution:
  Arrange: 
    • Stub render_timestamp to return "01 January 2025 10:00".  
    • Build scheduled_revision with object_str="Home page" and approved_go_live_at set to any datetime.  
    • Instantiate a dummy host object with model_name="page" and attach the scheduled_revision.  
  Act: Call get_message with a dummy user object (content is irrelevant).  
  Assert: 
    • Returned value equals "Page 'Home page' is locked and has been scheduled to go live at 01 January 2025 10:00".  
    • Type of the return value is SafeString.  
Validation:
  Ensures the core business requirement—displaying an accurate, user-facing scheduling notice—is met.

Scenario 2: Lower-case model name should be capitalised
Details:
  TestName: test_get_message_capitalises_model_name
  Description: Verifies that capfirst capitalises only the first character of the message, even when the model name starts with a lowercase letter.
Execution:
  Arrange: model_name="blog post", title="My Post", timestamp stubbed to "15 Mar 2025 09:30".
  Act: Invoke get_message.
  Assert: Message begins with "Blog post" (capital B) and the remainder of the template is unchanged.
Validation:
  Demonstrates correct application of capfirst, matching editorial style guidelines.

Scenario 3: Model name already capitalised should not be changed twice
Details:
  TestName: test_get_message_preserves_existing_capitalisation
  Description: Ensures that capfirst does not introduce unintended additional capitalisation when model_name is already capitalised.
Execution:
  Arrange: model_name="Article", title="Economy", timestamp="01 Jan 2026 00:00".
  Act: Call get_message.
  Assert: Output starts with "Article" (not "Article").
Validation:
  Guards against regressions where capfirst might modify a string that is already correctly capitalised.

Scenario 4: Title containing HTML-significant characters must be escaped
Details:
  TestName: test_get_message_escapes_title_html
  Description: Confirms that special characters in the title are HTML-escaped, protecting the admin UI from XSS.
Execution:
  Arrange: title="5 < 6 & 7 > 3", model_name="snippet", timestamp="10 Oct 2024 11:11".
  Act: Call get_message.
  Assert: Returned string contains "5 &lt; 6 &amp; 7 &gt; 3", not the raw "<" or ">" characters.
Validation:
  Validates security expectations and correct use of format_html.

Scenario 5: Naive datetime is formatted correctly
Details:
  TestName: test_get_message_formats_naive_datetime
  Description: Checks that a timezone-naive datetime is passed unmodified to render_timestamp and rendered in the message.
Execution:
  Arrange: approved_go_live_at set to datetime(2027, 5, 4, 12, 0, 0) with no tzinfo. Stub render_timestamp to return "04 May 2027 12:00".
  Act: get_message().
  Assert: Timestamp string "04 May 2027 12:00" appears verbatim in output.
Validation:
  Confirms compatibility with naive datetimes, a common case on projects not using timezone support.

Scenario 6: Time-zone aware datetime is localised then formatted
Details:
  TestName: test_get_message_formats_aware_datetime
  Description: Ensures that aware datetimes are converted to local time via timezone.localtime before formatting.
Execution:
  Arrange: approved_go_live_at = datetime(2028, 8, 8, 18, 0, 0, tzinfo=pytz.UTC).  
          Monkeypatch timezone.localtime to return datetime(2028, 8, 8, 20, 0) local time.  
          Stub render_timestamp to echo its input as "08 Aug 2028 20:00".
  Act: Call get_message.
  Assert: Output contains "08 Aug 2028 20:00".
Validation:
  Verifies that the user sees localised times, meeting internationalisation requirements.

Scenario 7: Returned value must be marked safe
Details:
  TestName: test_get_message_returns_safe_string
  Description: Asserts that mark_safe has wrapped the string, making it suitable for direct inclusion in Django templates without further escaping.
Execution:
  Arrange: Standard fixture with any title and timestamp.
  Act: result = get_message(user)
  Assert: isinstance(result, SafeString) is True.
Validation:
  Protects against accidental removal of mark_safe, which would double-escape the already-escaped HTML.

Scenario 8: Missing scheduled_revision should raise AttributeError
Details:
  TestName: test_get_message_without_scheduled_revision_raises
  Description: Confirms that the method fails fast when self.object lacks a scheduled_revision, highlighting a mis-configured usage scenario.
Execution:
  Arrange: Dummy object where scheduled_revision is None or absent.
  Act: Call get_message inside pytest.raises(AttributeError).
  Assert: AttributeError is raised.
Validation:
  Although not part of the “happy path”, this documents expected failure behaviour, ensuring developers are alerted when required data is missing.

"""

# ********RoostGPT********
import importlib
from datetime import datetime
from types import SimpleNamespace

import pytest
import pytz
from django.utils.safestring import SafeString
from django.utils import timezone

from wagtail.locks import ScheduledForPublishLock


# --------------------------------------------------------------------------- #
# Helper utilities
# --------------------------------------------------------------------------- #
def _patch_translation_identity(monkeypatch):
    """
    Ensure that gettext translation (_) is a no-op so that the raw
    English strings asserted in the tests are returned unchanged.
    """
    locks_module = importlib.import_module("wagtail.locks")
    monkeypatch.setattr(locks_module, "_", lambda s: s, raising=False)


def _make_lock(host_obj, model_name: str):
    """
    Build an instance of ScheduledForPublishLock **without** invoking its
    constructor (signature may vary between Wagtail versions). Only the
    attributes used by `get_message` are populated.
    """
    lock = ScheduledForPublishLock.__new__(ScheduledForPublishLock)  # type: ignore
    lock.object = host_obj
    lock.model_name = model_name
    return lock


# --------------------------------------------------------------------------- #
# Tests
# --------------------------------------------------------------------------- #
class Test_ScheduledForPublishLockGetMessage:
    # --------------------------------------------------------------------- #
    # Scenario 1
    # --------------------------------------------------------------------- #
    @pytest.mark.valid
    @pytest.mark.positive
    @pytest.mark.smoke
    def test_get_message_returns_expected_string(self, monkeypatch):
        _patch_translation_identity(monkeypatch)

        # Arrange
        expected_timestamp = "01 January 2025 10:00"
        monkeypatch.setattr(
            "wagtail.locks.render_timestamp",
            lambda ts: expected_timestamp,
        )

        scheduled_revision = SimpleNamespace(
            object_str="Home page",
            approved_go_live_at=datetime(2025, 1, 1, 10, 0, 0),
        )
        host_obj = SimpleNamespace(scheduled_revision=scheduled_revision)
        lock = _make_lock(host_obj, model_name="page")

        # Act
        result = lock.get_message(user=SimpleNamespace())  # user details irrelevant

        # Assert
        expected = (
            "Page 'Home page' is locked and has been scheduled to go live at "
            "01 January 2025 10:00"
        )
        assert str(result) == expected
        assert isinstance(result, SafeString)

    # --------------------------------------------------------------------- #
    # Scenario 2
    # --------------------------------------------------------------------- #
    @pytest.mark.valid
    @pytest.mark.regression
    def test_get_message_capitalises_model_name(self, monkeypatch):
        _patch_translation_identity(monkeypatch)

        expected_timestamp = "15 Mar 2025 09:30"
        monkeypatch.setattr(
            "wagtail.locks.render_timestamp",
            lambda ts: expected_timestamp,
        )

        scheduled_revision = SimpleNamespace(
            object_str="My Post",
            approved_go_live_at=datetime(2025, 3, 15, 9, 30, 0),
        )
        host_obj = SimpleNamespace(scheduled_revision=scheduled_revision)
        lock = _make_lock(host_obj, model_name="blog post")

        result = lock.get_message(user=SimpleNamespace())

        expected = (
            "Blog post 'My Post' is locked and has been scheduled to go live at "
            "15 Mar 2025 09:30"
        )
        assert str(result) == expected
        assert str(result).startswith("Blog post")

    # --------------------------------------------------------------------- #
    # Scenario 3
    # --------------------------------------------------------------------- #
    @pytest.mark.valid
    @pytest.mark.regression
    def test_get_message_preserves_existing_capitalisation(self, monkeypatch):
        _patch_translation_identity(monkeypatch)

        expected_timestamp = "01 Jan 2026 00:00"
        monkeypatch.setattr(
            "wagtail.locks.render_timestamp",
            lambda ts: expected_timestamp,
        )

        scheduled_revision = SimpleNamespace(
            object_str="Economy",
            approved_go_live_at=datetime(2026, 1, 1, 0, 0, 0),
        )
        host_obj = SimpleNamespace(scheduled_revision=scheduled_revision)
        lock = _make_lock(host_obj, model_name="Article")

        result = lock.get_message(user=SimpleNamespace())

        assert str(result).startswith("Article 'Economy'")

    # --------------------------------------------------------------------- #
    # Scenario 4
    # --------------------------------------------------------------------- #
    @pytest.mark.security
    @pytest.mark.negative
    def test_get_message_escapes_title_html(self, monkeypatch):
        _patch_translation_identity(monkeypatch)

        expected_timestamp = "10 Oct 2024 11:11"
        monkeypatch.setattr(
            "wagtail.locks.render_timestamp",
            lambda ts: expected_timestamp,
        )

        raw_title = "5 < 6 & 7 > 3"
        scheduled_revision = SimpleNamespace(
            object_str=raw_title,
            approved_go_live_at=datetime(2024, 10, 10, 11, 11, 0),
        )
        host_obj = SimpleNamespace(scheduled_revision=scheduled_revision)
        lock = _make_lock(host_obj, model_name="snippet")

        result = lock.get_message(user=SimpleNamespace())
        rendered = str(result)

        assert "5 &lt; 6 &amp; 7 &gt; 3" in rendered
        assert "<" not in rendered and ">" not in rendered

    # --------------------------------------------------------------------- #
    # Scenario 5
    # --------------------------------------------------------------------- #
    @pytest.mark.performance
    def test_get_message_formats_naive_datetime(self, monkeypatch):
        _patch_translation_identity(monkeypatch)

        expected_timestamp = "04 May 2027 12:00"

        # Confirm that a naive datetime is passed through as-is.
        def _stub_render_timestamp(ts):
            assert ts.tzinfo is None  # naive datetime
            return expected_timestamp

        monkeypatch.setattr("wagtail.locks.render_timestamp", _stub_render_timestamp)

        scheduled_revision = SimpleNamespace(
            object_str="May the 4th",
            approved_go_live_at=datetime(2027, 5, 4, 12, 0, 0),  # naïve
        )
        host_obj = SimpleNamespace(scheduled_revision=scheduled_revision)
        lock = _make_lock(host_obj, model_name="page")

        result = lock.get_message(user=SimpleNamespace())
        assert expected_timestamp in str(result)

    # --------------------------------------------------------------------- #
    # Scenario 6
    # --------------------------------------------------------------------- #
    @pytest.mark.performance
    @pytest.mark.regression
    def test_get_message_formats_aware_datetime(self, monkeypatch):
        _patch_translation_identity(monkeypatch)

        utc_dt = datetime(2028, 8, 8, 18, 0, 0, tzinfo=pytz.UTC)
        local_dt = datetime(2028, 8, 8, 20, 0, 0)  # assumed local time

        # Patch timezone.localtime so render_timestamp will receive `local_dt`
        monkeypatch.setattr(
            timezone, "localtime", lambda ts: local_dt
        )

        # Ensure render_timestamp sees the *local* value
        def _stub_render_timestamp(ts):
            assert ts == local_dt
            return "08 Aug 2028 20:00"

        monkeypatch.setattr("wagtail.locks.render_timestamp", _stub_render_timestamp)

        scheduled_revision = SimpleNamespace(
            object_str="International Post",
            approved_go_live_at=utc_dt,
        )
        host_obj = SimpleNamespace(scheduled_revision=scheduled_revision)
        lock = _make_lock(host_obj, model_name="page")

        result = lock.get_message(user=SimpleNamespace())
        assert "08 Aug 2028 20:00" in str(result)

    # --------------------------------------------------------------------- #
    # Scenario 7
    # --------------------------------------------------------------------- #
    @pytest.mark.valid
    def test_get_message_returns_safe_string(self, monkeypatch):
        _patch_translation_identity(monkeypatch)

        monkeypatch.setattr(
            "wagtail.locks.render_timestamp",
            lambda ts: "01 Jan 2030 00:00",
        )

        scheduled_revision = SimpleNamespace(
            object_str="Future",
            approved_go_live_at=datetime(2030, 1, 1, 0, 0, 0),
        )
        host_obj = SimpleNamespace(scheduled_revision=scheduled_revision)
        lock = _make_lock(host_obj, model_name="page")

        result = lock.get_message(user=SimpleNamespace())
        assert isinstance(result, SafeString)

    # --------------------------------------------------------------------- #
    # Scenario 8
    # --------------------------------------------------------------------- #
    @pytest.mark.invalid
    @pytest.mark.negative
    def test_get_message_without_scheduled_revision_raises(self):
        host_obj = SimpleNamespace()  # no scheduled_revision attribute
        lock = _make_lock(host_obj, model_name="page")

        with pytest.raises(AttributeError):
            _ = lock.get_message(user=SimpleNamespace())  # noqa: F841
