# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=WorkflowLock.get_description_e5fe48e486
ROOST_METHOD_SIG_HASH=WorkflowLock.get_description_a561460bdf


Scenario 1: Returns reviewer-lock message when can_lock is True
Details:
  TestName: test_returns_lock_message_when_can_lock_true
  Description: Verifies that the function chooses the “lock it to prevent other reviewers” sentence when can_lock is explicitly set to True.
Execution:
  Arrange: Instantiate a stub object with model_name="page" (lowercase) and supply any mock user.
  Act: Call get_description(user, can_lock=True).
  Assert: The result equals "Reviewers can edit this page – lock it to prevent other reviewers from editing".
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements.

Scenario 2: Returns restricted-edit message when can_lock is False
Details:
  TestName: test_returns_only_reviewers_message_when_can_lock_false
  Description: Ensures the alternative sentence—“Only reviewers can edit and approve…”—is used when can_lock is False.
Execution:
  Arrange: Stub with model_name="page"; any user object.
  Act: Call get_description(user, can_lock=False).
  Assert: The result equals "Only reviewers can edit and approve the page".
Validation:
  Demonstrates that the branch logic correctly selects the non-lock message when locking is not allowed.

Scenario 3: Default parameter behaves like can_lock=False
Details:
  TestName: test_default_can_lock_parameter
  Description: Confirms that omitting the can_lock argument defaults to the same outcome as passing False.
Execution:
  Arrange: Stub with model_name="page"; provide user.
  Act: Call get_description(user) with only the user argument.
  Assert: The returned string matches exactly the string from Scenario 2.
Validation:
  Guards against regressions where the default value might be altered, maintaining backward compatibility.

Scenario 4: capfirst capitalises first letter only
Details:
  TestName: test_capfirst_applies_once
  Description: Validates that capfirst uppercases only the very first character and leaves the rest untouched.
Execution:
  Arrange: Stub with model_name="myCustomModel"; user irrelevent; set can_lock=True to use the first branch.
  Act: Call get_description(user, can_lock=True).
  Assert: The result starts with an uppercase “R” (“Reviewers…”) while “myCustomModel” retains its internal capitalisation.
Validation:
  Confirms the integration of capfirst, ensuring sentence-style capitalisation without unwanted mutation of model_name.

Scenario 5: model_name already capitalised is left unchanged
Details:
  TestName: test_precapitalised_model_name_unchanged
  Description: Checks that capfirst does not double-capitalise when model_name already begins with an uppercase letter.
Execution:
  Arrange: Stub with model_name="Page"; pass user; can_lock=False.
  Act: Call get_description(user, can_lock=False).
  Assert: Output string contains “the Page” (capitalised as supplied) and not “the page” or “the PPage”.
Validation:
  Protects against edge cases where developers provide a properly capitalised model_name.

Scenario 6: Unicode model_name handled correctly
Details:
  TestName: test_unicode_model_name
  Description: Ensures the function supports non-ASCII characters without raising errors or corrupting output.
Execution:
  Arrange: Stub with model_name="añejo"; user; can_lock=True.
  Act: Invoke get_description(user, can_lock=True).
  Assert: Output exactly includes “añejo” with diacritic preserved.
Validation:
  Verifies internationalisation readiness and string handling robustness.

Scenario 7: Return type is always str
Details:
  TestName: test_return_type_is_str
  Description: Confirms that, despite using Django’s lazy translation utilities, the method returns a concrete Python str at call time.
Execution:
  Arrange: Stub with model_name="page"; user; loop both can_lock values via parametrisation.
  Act: Call get_description for each branch.
  Assert: isinstance(result, str) is True.
Validation:
  Prevents accidental leakage of Promise or SafeString objects into calling code, which could break downstream processing.

Scenario 8: Different users yield identical output
Details:
  TestName: test_user_parameter_does_not_affect_output
  Description: Proves that the user argument is ignored in the current implementation.
Execution:
  Arrange: Create two different mock users (e.g., staff and non-staff); stub with model_name="page".
  Act: Call get_description(userA, can_lock=False) and again with userB.
  Assert: The two returned strings are equal.
Validation:
  Locks in the expectation that future refactoring must intentionally add user-specific logic; otherwise the behaviour should remain constant.

"""

# ********RoostGPT********
import inspect
import types

import pytest

# Mandatory imports requested in the instructions.
# They are wrapped in try / except blocks so the test-suite can still run
# in environments where Django or Wagtail is unavailable.
try:
    from django.conf import settings  # noqa: F401
    from django.utils.html import format_html  # noqa: F401
    from django.utils.safestring import mark_safe  # noqa: F401
    from django.utils.text import capfirst  # noqa: F401
    from django.utils.translation import gettext_lazy as _  # noqa: F401
    from wagtail.admin.utils import get_latest_str, get_user_display_name  # noqa: F401
    from wagtail.utils.timestamps import render_timestamp  # noqa: F401
    from wagtail.models import Page  # noqa: F401
except ModuleNotFoundError:
    # Provide minimal fall-backs so the imports above do not break the test run
    capfirst = lambda s: s[:1].upper() + s[1:] if s else s  # type: ignore
    _ = lambda s: s  # type: ignore
    dummy = types.ModuleType("dummy")  # type: ignore
    for name in (
        "settings",
        "format_html",
        "mark_safe",
        "get_latest_str",
        "get_user_display_name",
        "render_timestamp",
        "Page",
    ):
        globals()[name] = dummy  # type: ignore


# The class under test must be imported rather than redeclared
try:
    from wagtail.locks import WorkflowLock
except ModuleNotFoundError as exc:  # pragma: no cover
    raise ImportError(
        "WorkflowLock could not be imported. "
        "Ensure wagtail.locks is available in PYTHONPATH."
    ) from exc


def _create_workflow_lock(model_name: str):
    """
    Helper to instantiate `WorkflowLock` without assuming knowledge
    of its public constructor.  It tries common invocation patterns
    and finally falls back to attribute injection.
    """
    # Attempt to instantiate using a keyword argument
    try:
        return WorkflowLock(model_name=model_name)
    except Exception:
        pass

    # Attempt to instantiate positionally
    try:
        return WorkflowLock(model_name)
    except Exception:
        pass

    # Fall-back: build an instance without args, then inject attribute
    lock = WorkflowLock()
    setattr(lock, "model_name", model_name)
    return lock


class Test_WorkflowLockGetDescription:
    """Unit-tests for WorkflowLock.get_description()."""

    # Scenario 1
    @pytest.mark.positive
    @pytest.mark.smoke
    def test_returns_lock_message_when_can_lock_true(self):
        """Verifies reviewer-lock sentence is used when can_lock is True."""
        lock = _create_workflow_lock(model_name="page")
        user_stub = object()

        result = lock.get_description(user_stub, can_lock=True)

        expected = (
            "Reviewers can edit this page – lock it to prevent other reviewers from editing"
        )
        assert result == expected, (
            "When can_lock=True the function must mention the ability "
            "to lock the page for other reviewers."
        )

    # Scenario 2
    @pytest.mark.positive
    @pytest.mark.regression
    def test_returns_only_reviewers_message_when_can_lock_false(self):
        """Ensures alternative sentence is used when can_lock is False."""
        lock = _create_workflow_lock(model_name="page")
        user_stub = object()

        result = lock.get_description(user_stub, can_lock=False)

        expected = "Only reviewers can edit and approve the page"
        assert result == expected, (
            "When can_lock=False the description should *not* mention locking "
            "and must state that only reviewers can edit/approve."
        )

    # Scenario 3
    @pytest.mark.positive
    @pytest.mark.regression
    def test_default_can_lock_parameter(self):
        """Omitting can_lock should behave exactly like can_lock=False."""
        lock = _create_workflow_lock(model_name="page")
        user_stub = object()

        result_without_flag = lock.get_description(user_stub)
        result_with_false = lock.get_description(user_stub, can_lock=False)

        assert (
            result_without_flag == result_with_false
        ), "Default value for can_lock must be False for backward compatibility"

    # Scenario 4
    @pytest.mark.positive
    def test_capfirst_applies_once(self):
        """
        Validates that only the very first character in the sentence
        is capitalised and model_name's internal capitalisation is preserved.
        """
        custom_name = "myCustomModel"
        lock = _create_workflow_lock(model_name=custom_name)
        user_stub = object()

        result = lock.get_description(user_stub, can_lock=True)

        assert result.startswith(
            "Reviewers"
        ), "Sentence should start with a capital 'R' after capfirst"
        assert custom_name in result, (
            "The model name must appear untouched in the sentence "
            f"(expected '{custom_name}')"
        )

    # Scenario 5
    @pytest.mark.positive
    def test_precapitalised_model_name_unchanged(self):
        """Checks that pre-capitalised model_name remains unchanged."""
        lock = _create_workflow_lock(model_name="Page")
        user_stub = object()

        result = lock.get_description(user_stub, can_lock=False)

        assert "the Page" in result, "Capitalisation of supplied model_name must be kept"
        assert "the page" not in result.lower(), (
            "Sentence must not down-case or double-capitalise the model name"
        )

    # Scenario 6
    @pytest.mark.positive
    def test_unicode_model_name(self):
        """Ensures unicode / non-ASCII model names are preserved."""
        unicode_name = "añejo"
        lock = _create_workflow_lock(model_name=unicode_name)
        user_stub = object()

        result = lock.get_description(user_stub, can_lock=True)

        assert (
            unicode_name in result
        ), "Unicode characters should be preserved in the output"

    # Scenario 7
    @pytest.mark.positive
    @pytest.mark.parametrize("can_lock", [True, False])
    def test_return_type_is_str(self, can_lock):
        """get_description must always return an actual `str` instance."""
        lock = _create_workflow_lock(model_name="page")
        user_stub = object()

        result = lock.get_description(user_stub, can_lock=can_lock)

        assert isinstance(
            result, str
        ), "Returned value should be a concrete `str`, not a lazy object"

    # Scenario 8
    @pytest.mark.positive
    def test_user_parameter_does_not_affect_output(self):
        """Different users should yield identical description strings."""
        lock = _create_workflow_lock(model_name="page")
        user_a = types.SimpleNamespace(username="alice", is_staff=True)
        user_b = types.SimpleNamespace(username="bob", is_staff=False)

        desc_a = lock.get_description(user_a, can_lock=False)
        desc_b = lock.get_description(user_b, can_lock=False)

        assert (
            desc_a == desc_b
        ), "Current implementation should ignore the `user` argument and return identical messages"
