# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=BaseLock.__init___40a1d0d220
ROOST_METHOD_SIG_HASH=BaseLock.__init___52fee328b7


Scenario 1: Page Instance – Attributes Set Correctly
Details:
  TestName: test_init_with_page_instance_sets_expected_attributes
  Description: Verify that passing a Wagtail Page (or subclass) instance flags the object as a page and stores the base Page model's verbose name.
Execution:
  Arrange: Create a concrete subclass of wagtail.models.Page (e.g., BlogPage) whose _meta.verbose_name differs from the base Page. Instantiate BlogPage.
  Act: Call the constructor with the BlogPage instance.
  Assert: 
    • self.object is the same BlogPage instance. 
    • self.is_page is True. 
    • self.model_name equals wagtail.models.Page._meta.verbose_name and not BlogPage._meta.verbose_name.
Validation:
  Rationalize that the business rule mandates using the generic Page label for brevity whenever a Page-derived object is supplied.

Scenario 2: Non-Page Django Model – Standard Attribute Resolution
Details:
  TestName: test_init_with_standard_model_sets_attributes
  Description: Ensure that a regular Django model instance leads to is_page == False and model_name reflecting that model’s own verbose_name.
Execution:
  Arrange: Create an instance of a simple Django model (e.g., Author) with a known verbose_name.
  Act: Call the constructor with the Author instance.
  Assert:
    • self.object is the Author instance.
    • self.is_page is False.
    • self.model_name equals Author._meta.verbose_name.
Validation:
  Confirms correct branching when the supplied object is not a Wagtail page.

Scenario 3: Subclass of Page – Still Uses Base Model Name
Details:
  TestName: test_page_subclass_still_uses_base_verbose_name
  Description: Demonstrate that even for deep subclasses of Page, model_name is taken from Page, not any intermediate subclass.
Execution:
  Arrange: Define a MultiLevelPage subclass (inherits BlogPage -> Page) with its own verbose_name. Instantiate it.
  Act: Construct the object with the MultiLevelPage instance.
  Assert:
    • self.is_page is True.
    • self.model_name equals wagtail.models.Page._meta.verbose_name.
Validation:
  Reinforces that subclass depth does not affect the constructor’s brevity logic.

Scenario 4: Object Without _meta Attribute – Raises AttributeError
Details:
  TestName: test_init_with_plain_object_raises_attribute_error
  Description: Validate that supplying an object lacking an _meta attribute triggers AttributeError when model_name is accessed.
Execution:
  Arrange: Define a simple dataclass or plain Python class instance (e.g., class Plain: pass).
  Act: Invoke the constructor with the Plain instance inside a pytest.raises(AttributeError) context.
  Assert: AttributeError is raised.
Validation:
  Documents current failure mode, guarding against silent behaviour changes and aiding future error handling considerations.

Scenario 5: None Input – Fails Predictably
Details:
  TestName: test_init_with_none_raises_attribute_error
  Description: Passing None should mimic the “no _meta” path and raise AttributeError.
Execution:
  Arrange: Define object = None.
  Act: Invoke the constructor within pytest.raises(AttributeError).
  Assert: AttributeError is raised.
Validation:
  Captures edge-case behaviour for null inputs, ensuring predictable exception handling across refactors.

Scenario 6: Mocked Non-Page Object With Custom Verbose Name
Details:
  TestName: test_init_with_mocked_model_uses_mock_verbose_name
  Description: Using a mock object that supplies an _meta.verbose_name lets us confirm the logic without a database-backed model.
Execution:
  Arrange: Create a Mock or SimpleNamespace whose _meta is another mock exposing verbose_name="mock model".
  Act: Pass this mock object to the constructor.
  Assert:
    • self.is_page is False.
    • self.model_name == "mock model".
Validation:
  Provides a lightweight, database-free assurance that non-Page handling solely depends on the presence of the _meta API.

"""

# ********RoostGPT********
import types
import pytest

# Mandatory imports required by the task – wrapped in a fallback so tests
# do not hard-fail if the full Django/Wagtail stack is absent.
try:
    from django.conf import settings  # noqa: F401
    from django.utils.html import format_html  # noqa: F401
    from django.utils.safestring import mark_safe  # noqa: F401
    from django.utils.text import capfirst  # noqa: F401
    from django.utils.translation import gettext_lazy as _  # noqa: F401
    from wagtail.admin.utils import (  # noqa: F401
        get_latest_str,
        get_user_display_name,
    )
    from wagtail.utils.timestamps import render_timestamp  # noqa: F401
    from wagtail.models import Page  # noqa: F401
except ModuleNotFoundError:
    # Provide minimal stand-ins so the test module can be imported even if
    # Django/Wagtail are not installed.  These stubs are only used when the
    # real libraries are missing and are intentionally lightweight.
    import sys

    Page = type(
        "Page",
        (),
        {"_meta": types.SimpleNamespace(verbose_name="page")},
    )
    sys.modules.setdefault("wagtail.models", types.ModuleType("wagtail.models"))
    setattr(sys.modules["wagtail.models"], "Page", Page)

    def _noop(*_args, **_kwargs):
        return ""

    settings = types.SimpleNamespace()
    format_html = mark_safe = capfirst = _noop
    _ = lambda s: s  # noqa: E731
    get_latest_str = get_user_display_name = render_timestamp = _noop

# Skip the entire test module if BaseLock cannot be imported.
wagtail_locks = pytest.importorskip(
    "wagtail.locks", reason="wagtail.locks (and BaseLock) must be importable"
)
BaseLock = wagtail_locks.BaseLock


class Test_BaseLockInit:
    @pytest.mark.positive
    @pytest.mark.valid
    def test_init_with_page_instance_sets_expected_attributes(self):
        """
        Scenario 1
        Verify that a concrete subclass of Page is recognised as a page and that
        BaseLock stores the *base* Page model’s verbose name rather than the
        subclass’s own value.
        """
        class BlogPage(Page):  # type: ignore
            _meta = types.SimpleNamespace(verbose_name="blog page")  # override

        blog_page_instance = BlogPage()  # noqa: E501

        lock = BaseLock(blog_page_instance)

        assert lock.object is blog_page_instance
        assert lock.is_page is True
        assert lock.model_name == Page._meta.verbose_name
        assert lock.model_name != BlogPage._meta.verbose_name

    @pytest.mark.positive
    @pytest.mark.valid
    def test_init_with_standard_model_sets_attributes(self):
        """
        Scenario 2
        Ensure a non-Page model instance results in is_page == False and that the
        object’s own verbose name is preserved.
        """
        class Author:
            _meta = types.SimpleNamespace(verbose_name="author")

        author_instance = Author()

        lock = BaseLock(author_instance)

        assert lock.object is author_instance
        assert lock.is_page is False
        assert lock.model_name == Author._meta.verbose_name

    @pytest.mark.positive
    @pytest.mark.valid
    def test_page_subclass_still_uses_base_verbose_name(self):
        """
        Scenario 3
        Even deep subclasses of Page must still use the base Page’s verbose name.
        """
        class BlogPage(Page):  # type: ignore
            _meta = types.SimpleNamespace(verbose_name="blog page")

        class MultiLevelPage(BlogPage):  # noqa: D401
            _meta = types.SimpleNamespace(verbose_name="multi level page")

        ml_page_instance = MultiLevelPage()

        lock = BaseLock(ml_page_instance)

        assert lock.is_page is True
        assert lock.model_name == Page._meta.verbose_name

    @pytest.mark.negative
    @pytest.mark.invalid
    def test_init_with_plain_object_raises_attribute_error(self):
        """
        Scenario 4
        A plain object that does not expose a `_meta` attribute should trigger an
        AttributeError from within BaseLock.__init__.
        """
        class Plain:
            pass

        with pytest.raises(AttributeError):
            BaseLock(Plain())  # noqa: PT011

    @pytest.mark.negative
    @pytest.mark.invalid
    def test_init_with_none_raises_attribute_error(self):
        """
        Scenario 5
        Passing `None` should behave like an object without _meta and raise an
        AttributeError.
        """
        with pytest.raises(AttributeError):
            BaseLock(None)  # type: ignore[arg-type]

    @pytest.mark.positive
    @pytest.mark.valid
    def test_init_with_mocked_model_uses_mock_verbose_name(self):
        """
        Scenario 6
        A lightweight mock object sporting an `_meta.verbose_name` property must
        be handled as a non-Page model.
        """
        mock_model = types.SimpleNamespace(
            _meta=types.SimpleNamespace(verbose_name="mock model")
        )

        lock = BaseLock(mock_model)

        assert lock.is_page is False
        assert lock.model_name == "mock model"
