# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=BaseLock.get_message_dab3319279
ROOST_METHOD_SIG_HASH=BaseLock.get_message_38d14a7494


Scenario 1: Message When the Current User Holds the Lock
Details:
  TestName: test_get_message_returns_self_lock_message
  Description: Verify that the function returns an informative, ​HTML-safe​ string indicating the page is locked by the same user that is requesting the message.
Execution:
  Arrange: 
    • Create a mock page object with a lock owned by user_A.  
    • Instantiate the class that implements get_message and set the lock metadata (locked_by=user_A, locked_at=now).  
    • Ensure user_A is passed as the current user to the method call.
  Act: 
    • Call get_message(user_A).
  Assert: 
    • The return value is truthy, is an instance of django.utils.safestring.SafeString, and contains the user’s display name retrieved via get_user_display_name(user_A).  
    • The string does NOT contain an “override” or “steal” lock hint, since the requester already owns the lock.
Validation:
  This scenario confirms the primary happy-path: a user who already owns the lock receives a clear, self-oriented message, satisfying usability requirements and preventing misleading prompts to override their own lock.

"""

# ********RoostGPT********
import pytest
from datetime import datetime, timezone

from django.contrib.auth import get_user_model
from django.utils.safestring import SafeString
from django.utils.timezone import now

# Third-party (Wagtail / Django) helpers that the production code is expected to use
from django.conf import settings  # noqa: F401 – imported as mandated
from django.utils.html import format_html  # noqa: F401
from django.utils.safestring import mark_safe  # noqa: F401
from django.utils.text import capfirst  # noqa: F401
from django.utils.translation import gettext as _  # noqa: F401
from wagtail.admin.utils import (  # noqa: F401
    get_latest_str,
    get_user_display_name,
)
from wagtail.utils.timestamps import render_timestamp  # noqa: F401
from wagtail.models import Page

# The subject under test
from wagtail.locks import BaseLock


@pytest.mark.django_db
@pytest.mark.regression
@pytest.mark.positive
class Test_BaseLockGetMessage:
    @pytest.mark.smoke
    def test_get_message_returns_self_lock_message(self):
        """
        Scenario 1:
        Verify that when the current user holds the lock, ``get_message`` returns
        a truthy, HTML-safe string that references the requesting user and does
        not suggest overriding / stealing the lock.
        """

        # ---------- Arrange ----------
        # Create a test user
        User = get_user_model()
        user_a = User.objects.create_user(
            username="user_a",
            password="testpass123",
            first_name="Alice",
            last_name="Anderson",
        )

        # Obtain (or create) a page instance to lock.
        # The Wagtail DB is expected to have a root page created by migrations,
        # so we can safely fetch the first page available.
        page = Page.objects.first()
        assert (
            page is not None
        ), "The test database must contain at least one Page instance."

        # Manually apply a lock owned by `user_a`
        page.locked = True
        page.locked_at = now()
        page.locked_by = user_a
        page.save()  # Persist the lock attributes

        # Some BaseLock implementations require the locked object to be passed
        # to the constructor, others take no arguments.  This `try / except`
        # keeps the test flexible across variants without redefining the class.
        try:
            lock = BaseLock(page)  # type: ignore[arg-type]
        except TypeError:
            lock = BaseLock()  # type: ignore[call-arg]

        # ---------- Act ----------
        message = lock.get_message(user_a)

        # ---------- Assert ----------
        # The message must be present and HTML-safe
        assert message, "Expected a non-empty string to be returned."
        assert isinstance(
            message, SafeString
        ), "The returned value should be a Django SafeString."

        # It must reference the current (locking) user's display name
        expected_display_name = get_user_display_name(user_a)
        assert (
            expected_display_name in str(message)
        ), "User's display name is missing from the lock message."

        # It must NOT suggest overriding / stealing the lock
        forbidden_phrases = ["override", "steal"]
        lowered_msg = str(message).lower()
        for phrase in forbidden_phrases:
            assert (
                phrase not in lowered_msg
            ), f"The lock message wrongly contains the phrase '{phrase}'."
