# ********RoostGPT********
"""
Test generated by RoostGPT for test python_wagtail using AI Type Open AI and AI Model o3

ROOST_METHOD_HASH=get_task_types_9415af7f72
ROOST_METHOD_SIG_HASH=get_task_types_95ca67b8e2


 
Scenario 1: Returns concrete descendants on the initial call  
Details:  
  TestName: test_first_call_populates_and_returns_descendants  
  Description: Verify that, when TASK_TYPES is uninitialized, get_task_types retrieves concrete descendants via get_concrete_descendants, stores them in TASK_TYPES, and returns that list.  
Execution:  
  Arrange:  
    • monkeypatch TASK_TYPES to an empty falsy value (e.g., None).  
    • monkeypatch get_concrete_descendants to return a predetermined list of two concrete dummy classes.  
  Act:  
    • Call get_task_types() without arguments.  
  Assert:  
    • The returned value equals the list supplied by the stub.  
    • TASK_TYPES now holds the same list object (identity check).  
Validation:  
  Proves that the function performs the discovery logic exactly once and caches the result, satisfying the core business requirement of lazy initialisation.  

Scenario 2: Subsequent call uses the cache, skipping discovery  
Details:  
  TestName: test_second_call_uses_cached_result  
  Description: Confirm that if TASK_TYPES already holds data, the helper function is not executed again and the existing list is returned untouched.  
Execution:  
  Arrange:  
    • Pre-populate TASK_TYPES with a sentinel list object.  
    • monkeypatch get_concrete_descendants with a stub that would raise or increment a counter if invoked.  
  Act:  
    • Call get_task_types() a second time.  
  Assert:  
    • Returned object is the exact sentinel list (identity equality).  
    • The stubbed helper is never called.  
Validation:  
  Validates the performance optimisation/caching contract of the function.  

Scenario 3: Parameter task_class is ignored  
Details:  
  TestName: test_parameter_is_ignored  
  Description: Ensure that supplying a task_class argument does not influence the outcome; get_task_types behaves identically regardless of the argument’s value.  
Execution:  
  Arrange:  
    • Reset TASK_TYPES to falsy.  
    • Stub get_concrete_descendants to return a known list.  
  Act:  
    • Call get_task_types(task_class=object()).  
  Assert:  
    • The returned list equals the stubbed result.  
    • get_concrete_descendants is called with the original Task model, not the supplied argument (inspect call args).  
Validation:  
  Confirms that the public signature’s optional parameter is presently non-functional, preventing false assumptions by future developers.  

Scenario 4: Returned list does not include the base Task class  
Details:  
  TestName: test_base_task_class_excluded_due_to_inclusive_false  
  Description: Check that the list of descendants excludes the Task model itself, reflecting the inclusive=False flag handed to get_concrete_descendants.  
Execution:  
  Arrange:  
    • Reset TASK_TYPES.  
    • Provide a stub of get_concrete_descendants that returns [DummyChildTask, Task].  
  Act:  
    • Invoke get_task_types().  
  Assert:  
    • The resulting list contains DummyChildTask but not Task.  
Validation:  
  Demonstrates correct adherence to the inclusive=False requirement in the discovery process.  

Scenario 5: Only concrete (non-abstract) subclasses are cached  
Details:  
  TestName: test_abstract_classes_filtered_out  
  Description: Ensure that abstract subclasses yielded by get_concrete_descendants are filtered out or never appear, consistent with the helper’s purpose and the function’s documentation.  
Execution:  
  Arrange:  
    • Create two dummy classes: AbstractChild (abstract flag True) and ConcreteChild (abstract flag False).  
    • Stub get_concrete_descendants to return [AbstractChild, ConcreteChild].  
  Act:  
    • Call get_task_types().  
  Assert:  
    • Returned list contains ConcreteChild only.  
Validation:  
  Affirms that business logic mandates exposing only actionable (concrete) task types to downstream consumers.  

Scenario 6: Empty descendant set is handled gracefully  
Details:  
  TestName: test_no_descendants_returns_empty_list  
  Description: Verify that the function copes with an empty descendant list, caching and returning an empty list without raising errors.  
Execution:  
  Arrange:  
    • Reset TASK_TYPES.  
    • Stub get_concrete_descendants to return an empty list.  
  Act:  
    • Call get_task_types().  
  Assert:  
    • Function returns [] (empty list).  
    • TASK_TYPES now references that empty list.  
Validation:  
  Ensures robustness when the system has no custom Task subclasses, a legitimate production scenario.  

Scenario 7: Cached list instance remains stable across multiple accesses  
Details:  
  TestName: test_cached_list_identity_stable  
  Description: Confirm that repeated calls after caching always return the same list instance, not a copy, thereby allowing safe reference equality checks in caller code.  
Execution:  
  Arrange:  
    • Reset TASK_TYPES and perform an initial call to populate it (using a stubbed descendant list).  
  Act:  
    • Call get_task_types() two more times.  
  Assert:  
    • id(result_first_call) == id(result_second_call) == id(result_third_call).  
Validation:  
  Verifies consistent caching semantics and prevents subtle bugs where consumers might rely on object identity.  

"""

# ********RoostGPT********
# test_workflows_get_task_types.py
import importlib
import sys
import types
import pytest

# Import the function under test (must already exist in the environment)
from wagtail.workflows import get_task_types

# Keep a handle to the actual workflows module so we can monkey-patch internals
workflows_module = importlib.import_module("wagtail.workflows")


@pytest.fixture(autouse=True)
def restore_global_state(monkeypatch):
    """
    Ensures that TASK_TYPES and get_concrete_descendants are restored to a
    pristine state before every test runs.
    """
    # Reset the TASK_TYPES cache before each test
    monkeypatch.setattr(workflows_module, "TASK_TYPES", [], raising=False)

    yield  # Test runs here

    # Extra safety: clear any remaining state after the test
    monkeypatch.setattr(workflows_module, "TASK_TYPES", [], raising=False)


# --------------------------------------------------------------------------- #
#  Scenario 1                                                                 #
# --------------------------------------------------------------------------- #
@pytest.mark.regression
@pytest.mark.positive
def test_first_call_populates_and_returns_descendants(monkeypatch):
    """Verify lazy initialisation and caching on first call."""
    sentinel_descendants = ["DummyA", "DummyB"]

    # TASK_TYPES is currently [], change it to a falsy value (None)
    monkeypatch.setattr(workflows_module, "TASK_TYPES", None, raising=False)

    # Stub get_concrete_descendants to deliver our sentinel list
    def stub_get_descendants(_task_class, inclusive=False):
        return sentinel_descendants

    monkeypatch.setattr(
        workflows_module, "get_concrete_descendants", stub_get_descendants, raising=False
    )

    returned = get_task_types()

    assert returned == sentinel_descendants  # Returned value is correct
    # Same list instance cached
    assert workflows_module.TASK_TYPES is returned is sentinel_descendants


# --------------------------------------------------------------------------- #
#  Scenario 2                                                                 #
# --------------------------------------------------------------------------- #
@pytest.mark.smoke
@pytest.mark.positive
def test_second_call_uses_cached_result(monkeypatch):
    """Confirm that discovery helper is skipped when cache is warm."""
    sentinel_cache = ["cached_item"]

    # Pre-populate the cache with a sentinel object
    monkeypatch.setattr(workflows_module, "TASK_TYPES", sentinel_cache, raising=False)

    # Stub that MUST NOT be called – raise if it is
    def forbidden_stub(*_args, **_kwargs):
        raise AssertionError("get_concrete_descendants should NOT be called")

    monkeypatch.setattr(
        workflows_module, "get_concrete_descendants", forbidden_stub, raising=False
    )

    returned = get_task_types()

    # Same identity proves cached path taken
    assert returned is sentinel_cache


# --------------------------------------------------------------------------- #
#  Scenario 3                                                                 #
# --------------------------------------------------------------------------- #
@pytest.mark.regression
@pytest.mark.positive
def test_parameter_is_ignored(monkeypatch):
    """
    Supplying task_class argument must not affect outcome; helper should still
    be called with the original Task model.
    """
    sentinel_descendants = ["OnlyResult"]
    call_args = {}

    from wagtail.models import Task  # Current Task model

    # Stub helper to record call arguments
    def recorder(model_class, *, inclusive=False):
        call_args["model_class"] = model_class
        call_args["inclusive"] = inclusive
        return sentinel_descendants

    monkeypatch.setattr(workflows_module, "TASK_TYPES", None, raising=False)
    monkeypatch.setattr(
        workflows_module, "get_concrete_descendants", recorder, raising=False
    )

    random_param = object()  # This value should be ignored
    returned = get_task_types(task_class=random_param)

    assert returned == sentinel_descendants
    # Called with original Task, not the supplied random object
    assert call_args["model_class"] is Task
    assert call_args["inclusive"] is False


# --------------------------------------------------------------------------- #
#  Scenario 4                                                                 #
# --------------------------------------------------------------------------- #
@pytest.mark.regression
@pytest.mark.positive
def test_base_task_class_excluded_due_to_inclusive_false(monkeypatch):
    """
    Ensure that the list does not include the `Task` class itself because
    inclusive=False is passed down.
    """
    from wagtail.models import Task

    class DummyChildTask(Task):
        pass

    expected_list = [DummyChildTask]

    # Stub helper to mimic behaviour: exclude Task when inclusive=False
    def stub_helper(model_class, *, inclusive=False):
        # Verify helper receives the correct flag
        assert inclusive is False
        # Return DummyChildTask only when inclusive is False
        return expected_list if not inclusive else [DummyChildTask, Task]

    monkeypatch.setattr(
        workflows_module, "get_concrete_descendants", stub_helper, raising=False
    )
    monkeypatch.setattr(workflows_module, "TASK_TYPES", None, raising=False)

    result = get_task_types()

    assert DummyChildTask in result
    assert Task not in result
    assert result == expected_list


# --------------------------------------------------------------------------- #
#  Scenario 5                                                                 #
# --------------------------------------------------------------------------- #
@pytest.mark.regression
@pytest.mark.positive
def test_abstract_classes_filtered_out(monkeypatch):
    """Only concrete task types must be exposed/cached."""
    from wagtail.models import Task

    # Concrete and abstract dummy subclasses -------------------------------
    class AbstractChild(Task):
        pass

    class ConcreteChild(Task):
        pass

    # Manually attach _meta.abstract flags
    AbstractChild._meta = types.SimpleNamespace(abstract=True)
    ConcreteChild._meta = types.SimpleNamespace(abstract=False)

    # Helper that returns both classes – real-life helper would filter but we
    # want to ensure get_task_types only exposes the concrete one.
    def stub_helper(_model_class, *, inclusive=False):
        # The stub pretends to have already filtered out `Task`
        return [AbstractChild, ConcreteChild]

    monkeypatch.setattr(
        workflows_module, "get_concrete_descendants", stub_helper, raising=False
    )
    monkeypatch.setattr(workflows_module, "TASK_TYPES", None, raising=False)

    result = get_task_types()

    assert ConcreteChild in result
    assert AbstractChild not in result
    assert result == [ConcreteChild]


# --------------------------------------------------------------------------- #
#  Scenario 6                                                                 #
# --------------------------------------------------------------------------- #
@pytest.mark.regression
@pytest.mark.negative
def test_no_descendants_returns_empty_list(monkeypatch):
    """Function must gracefully handle an empty descendant set."""
    monkeypatch.setattr(workflows_module, "TASK_TYPES", None, raising=False)

    # Helper that returns an empty list
    monkeypatch.setattr(
        workflows_module, "get_concrete_descendants", lambda *_a, **_kw: [], raising=False
    )

    result = get_task_types()

    assert result == []
    assert workflows_module.TASK_TYPES is result  # Cached the same empty list


# --------------------------------------------------------------------------- #
#  Scenario 7                                                                 #
# --------------------------------------------------------------------------- #
@pytest.mark.smoke
@pytest.mark.positive
def test_cached_list_identity_stable(monkeypatch):
    """Repeated calls should always return the very same cached object."""
    sentinel_descendants = ["Persisted"]

    monkeypatch.setattr(workflows_module, "TASK_TYPES", None, raising=False)
    monkeypatch.setattr(
        workflows_module,
        "get_concrete_descendants",
        lambda *_a, **_kw: sentinel_descendants,
        raising=False,
    )

    first = get_task_types()
    second = get_task_types()
    third = get_task_types()

    assert first is second is third is workflows_module.TASK_TYPES
